def Alerts():
    
       testSettings.logScreenshotOnFail = True
       testSettings.logScreenshotOnError = True
       
       
       clickButton(waitForObject(":Market-Q (qa).Alerts_MonsoonNewPadButton"))
       test.compare(waitForObjectExists(":Market-Q (qa).Alerts_LCLabel").name, "Alerts")
       test.passes("Verify Alerts is opening or not is pass")
       
       #Add Button And Quote Alerts
       clickButton(waitForObject(":Market-Q (qa).Add_SmallButton"))
       type(waitForObject(":Add Quote Alert_LCTextField_2"), "I")
       type(waitForObject(":Add Quote Alert_LCTextField_3"), "B")
       type(waitForObject(":Add Quote Alert_LCTextField_4"), "M")
       clickButton(waitForObject(":Add Quote Alert.Recent_SmallButton"))
       mouseClick(waitForObject(":Add Quote Alert.com.futuresource.livecharts.dialogs.GridPanel$2_LCPanel"), 132, 2, 0, Button.Button1)
       mouseClick(waitForObject(":Add Quote Alert.com.futuresource.livecharts.common.LCComboBox_LCComboBox"), 71, 8, 0, Button.Button1)
       mouseClick(waitForObjectItem(":Add Quote Alert.ComboBox.list_JList", "Net Change"), 41, 6, 0, Button.Button1)
       mouseClick(waitForObject(":Add Quote Alert.com.futuresource.livecharts.common.LCComboBox_LCComboBox"), 73, 8, 0, Button.Button1)
       mouseClick(waitForObjectItem(":Add Quote Alert.ComboBox.list_JList", "Last"), 56, 3, 0, Button.Button1)
       mouseClick(waitForObject(":Add Quote Alert_LCTextField"), 45, 6, 0, Button.Button1)
       type(waitForObject(":Add Quote Alert_LCTextField"), "152")
       type(waitForObject(":Add Quote Alert_LCTextField"), "<Tab>")
       type(waitForObject(":Add Quote Alert_LCTextField_5"), "150")
       mouseClick(waitForObject(":Add Quote Alert_LCTextArea"), 56, 13, 0, Button.Button1)
       type(waitForObject(":Add Quote Alert_LCTextArea"), "Test")
       clickButton(waitForObject(":Add Quote Alert.OK_FixedSizeButton"))
       test.passes("Verify Add button is pass")
       snooze(1)
       test.passes("Verify Quote Alerts is pass")
       
       #Condition Alerts
       clickTab(waitForObject(":Market-Q (qa).Condition Alerts_TabProxy"))
       clickButton(waitForObject(":Market-Q (qa).Add_SmallButton"))
       type(waitForObject(":Add Condition Alerts_LCUppercaseTextField"), "d")
       type(waitForObject(":Add Condition Alerts_LCUppercaseTextField"), "<Backspace>")
       type(waitForObject(":Add Condition Alerts_LCUppercaseTextField"), "<#20>")
       type(waitForObject(":Add Condition Alerts_LCUppercaseTextField"), "DAILY(INTERSECT(GOOG,AAPL0")
       type(waitForObject(":Add Condition Alerts_LCUppercaseTextField"), "<Backspace>")
       type(waitForObject(":Add Condition Alerts_LCUppercaseTextField"), "))")
       mouseClick(waitForObject(":Add Condition Alerts_LCTextArea"), 78, 14, 0, Button.Button1)
       type(waitForObject(":Add Condition Alerts_LCTextArea"), "tEST")
       clickButton(waitForObject(":Add Condition Alerts.OK_FixedSizeButton"))
       test.passes("Verify Condition Alert is pass")
       clickButton(waitForObject(":Market-Q (qa).Add_SmallButton"))
       type(waitForObject(":Add Condition Alerts_LCUppercaseTextField"), "CSCO>100")
       mouseClick(waitForObject(":Add Condition Alerts_LCTextArea"), 41, 1, 0, Button.Button1)
       type(waitForObject(":Add Condition Alerts_LCTextArea"), "Test CSCO")
       clickButton(waitForObject(":Add Condition Alerts.OK_FixedSizeButton"))

       snooze(5)
       #Time Alerts
       clickTab(waitForObject(":Market-Q (qa).Time Alerts_TabProxy"))
       clickButton(waitForObject(":Market-Q (qa).Add_SmallButton"))
       test.compare(waitForObjectExists(":Add Time Alerts.Day: _LCLabel").name, "Day: ")
       mouseClick(waitForObject(":Add Time Alerts.com.futuresource.livecharts.common.LCComboBox_LCComboBox"), 48, 4, 0, Button.Button1)
       mouseClick(waitForObjectItem(":Add Time Alerts.ComboBox.list_JList", "Tomorrow"), 38, 5, 0, Button.Button1)
       setValue(waitForObject(":Add Time Alerts_LCSpinner"), 21)
       setValue(waitForObject(":Add Time Alerts_LCSpinner"), 20)
       mouseClick(waitForObject(":Add Time Alerts_LCTextArea"), 38, 32, 0, Button.Button1)
       type(waitForObject(":Add Time Alerts_LCTextArea"), "tOMORROW")
       type(waitForObject(":Add Time Alerts_LCTextArea"), "<Backspace>")
       type(waitForObject(":Add Time Alerts_LCTextArea"), "<Backspace>")
       type(waitForObject(":Add Time Alerts_LCTextArea"), "<Backspace>")
       type(waitForObject(":Add Time Alerts_LCTextArea"), "<Backspace>")
       type(waitForObject(":Add Time Alerts_LCTextArea"), "<Backspace>")
       type(waitForObject(":Add Time Alerts_LCTextArea"), "<Backspace>")
       type(waitForObject(":Add Time Alerts_LCTextArea"), "<Backspace>")
       type(waitForObject(":Add Time Alerts_LCTextArea"), "<Backspace>")
       type(waitForObject(":Add Time Alerts_LCTextArea"), "<#20>")
       type(waitForObject(":Add Time Alerts_LCTextArea"), "Tomorrow Time Alert")
       clickButton(waitForObject(":Add Time Alerts.OK_FixedSizeButton"))
       test.passes("Verify Time Alerts is pass")
       
       #Selection
       clickTab(waitForObject(":Market-Q (qa).Condition Alerts_TabProxy"))
       clickTab(waitForObject(":Market-Q (qa).Quote Alerts_TabProxy"))
       clickButton(waitForObject(":Market-Q (qa).Add_SmallButton"))
       type(waitForObject(":Add Quote Alert_LCTextField_2"), "AAPL")
       type(waitForObject(":Add Quote Alert_LCTextField_2"), "<Return>")
       mouseClick(waitForObject(":Add Quote Alert_LCTextField"), 35, 5, 0, Button.Button1)
       type(waitForObject(":Add Quote Alert_LCTextField"), "210")
       mouseClick(waitForObject(":Add Quote Alert_LCTextField_5"), 71, 3, 0, Button.Button1)
       type(waitForObject(":Add Quote Alert_LCTextField_5"), "204")
       mouseClick(waitForObject(":Add Quote Alert_LCTextArea"), 130, 32, 0, Button.Button1)
       type(waitForObject(":Add Quote Alert_LCTextArea"), "Test1")
       clickButton(waitForObject(":Add Quote Alert.OK_FixedSizeButton"))
       clickButton(waitForObject(":Market-Q (qa).Add_SmallButton"))
       type(waitForObject(":Add Quote Alert_LCTextField_2"), "MSFT")
       mouseClick(waitForObject(":Add Quote Alert.com.futuresource.livecharts.common.LCPanel_LCPanel"), 222, 120, 0, Button.Button1)
       mouseClick(waitForObject(":Add Quote Alert_LCTextField"), 38, 1, 0, Button.Button1)
       type(waitForObject(":Add Quote Alert_LCTextField"), "135")
       type(waitForObject(":Add Quote Alert_LCTextField"), "<Backspace>")
       type(waitForObject(":Add Quote Alert_LCTextField"), "9")
       mouseClick(waitForObject(":Add Quote Alert_LCTextField_5"), 75, 9, 0, Button.Button1)
       type(waitForObject(":Add Quote Alert_LCTextField_5"), "135")
       mouseClick(waitForObject(":Add Quote Alert_LCTextArea"), 67, 8, 0, Button.Button1)
       type(waitForObject(":Add Quote Alert_LCTextArea"), "Test2")
       clickButton(waitForObject(":Add Quote Alert.OK_FixedSizeButton"))
       
       mouseClick(waitForObjectItem(":Quote Alerts.com.futuresource.livecharts.newquotes.alerts.QuoteAlertTable_QuoteAlertTable", "0/1"), 23, 2, 4, Button.Button3)
       activateItem(waitForObjectItem(":Quote Alerts.com.futuresource.livecharts.newquotes.alerts.QuoteAlertTable_QuoteAlertTable", "Select"))
       activateItem(waitForObjectItem(":Quote Alerts.Select_JMenu", "All"))
       mouseClick(waitForObjectItem(":Quote Alerts.com.futuresource.livecharts.newquotes.alerts.QuoteAlertTable_QuoteAlertTable", "0/1"), 42, 6, 4, Button.Button3)
       activateItem(waitForObjectItem(":Quote Alerts.com.futuresource.livecharts.newquotes.alerts.QuoteAlertTable_QuoteAlertTable", "Select"))
       activateItem(waitForObjectItem(":Quote Alerts.Select_JMenu", "Active"))
       mouseClick(waitForObjectItem(":Quote Alerts.com.futuresource.livecharts.newquotes.alerts.QuoteAlertTable_QuoteAlertTable", "0/1"), 18, 4, 4, Button.Button3)
       activateItem(waitForObjectItem(":Quote Alerts.com.futuresource.livecharts.newquotes.alerts.QuoteAlertTable_QuoteAlertTable", "Select"))
       activateItem(waitForObjectItem(":Quote Alerts.Select_JMenu", "Clear"))
       mouseClick(waitForObjectItem(":Quote Alerts.com.futuresource.livecharts.newquotes.alerts.QuoteAlertTable_QuoteAlertTable", "0/1"), 27, 7, 4, Button.Button3)
       activateItem(waitForObjectItem(":Quote Alerts.com.futuresource.livecharts.newquotes.alerts.QuoteAlertTable_QuoteAlertTable", "Select"))
       activateItem(waitForObjectItem(":Quote Alerts.Select_JMenu", "Active"))
       mouseClick(waitForObjectItem(":Quote Alerts.com.futuresource.livecharts.newquotes.alerts.QuoteAlertTable_QuoteAlertTable", "0/1"), 54, 5, 4, Button.Button3)
       activateItem(waitForObjectItem(":Quote Alerts.com.futuresource.livecharts.newquotes.alerts.QuoteAlertTable_QuoteAlertTable", "Select"))
       activateItem(waitForObjectItem(":Quote Alerts.Select_JMenu", "Clear"))
       test.passes("Verify Selection button is pass")
       
       mouseClick(waitForObjectItem(":Quote Alerts.com.futuresource.livecharts.newquotes.alerts.QuoteAlertTable_QuoteAlertTable", "0/1"), 24, 7, 4, Button.Button3)
       activateItem(waitForObjectItem(":Quote Alerts.com.futuresource.livecharts.newquotes.alerts.QuoteAlertTable_QuoteAlertTable", "Edit"))
       type(waitForObject(":Edit Quote Alert_LCTextField"), "<Backspace>")
       type(waitForObject(":Edit Quote Alert_LCTextField"), "3")
       clickButton(waitForObject(":Edit Quote Alert.OK_FixedSizeButton"))
       test.passes("Verify Edit option is pass")
       
       mouseClick(waitForObjectItem(":Quote Alerts.com.futuresource.livecharts.newquotes.alerts.QuoteAlertTable_QuoteAlertTable", "0/1"), 53, 5, 4, Button.Button3)
       activateItem(waitForObjectItem(":Quote Alerts.com.futuresource.livecharts.newquotes.alerts.QuoteAlertTable_QuoteAlertTable", "Dismiss"))
       test.passes("Verify Dismiss option is pass")
       
       mouseClick(waitForObjectItem(":Quote Alerts.com.futuresource.livecharts.newquotes.alerts.QuoteAlertTable_QuoteAlertTable", "0/1"), 34, 1, 4, Button.Button3)
       activateItem(waitForObjectItem(":Quote Alerts.com.futuresource.livecharts.newquotes.alerts.QuoteAlertTable_QuoteAlertTable", "Reactivate"))
       test.passes("Verify Reactivate option is pass")
       
       mouseClick(waitForObjectItem(":Quote Alerts.com.futuresource.livecharts.newquotes.alerts.QuoteAlertTable_QuoteAlertTable", "1/1"), 19, 2, 4, Button.Button3)
       activateItem(waitForObjectItem(":Quote Alerts.com.futuresource.livecharts.newquotes.alerts.QuoteAlertTable_QuoteAlertTable", "Delete"))
       clickButton(waitForObject(":Question.Yes_FixedSizeButton"))
       test.passes("Verify Delete option is pass")



       clickButton(waitForObject(":Market-Q (qa).Action_SmallButton"))
       activateItem(waitForObjectItem(":Market-Q (qa).Action_SmallButton", "Edit"))
       type(waitForObject(":Edit Quote Alert_LCTextField"), "<Backspace>")
       type(waitForObject(":Edit Quote Alert_LCTextField"), "<Backspace>")
       type(waitForObject(":Edit Quote Alert_LCTextField"), "40")
       clickButton(waitForObject(":Edit Quote Alert.OK_FixedSizeButton"))
       test.passes("Verify Edit option is pass")
       
       clickButton(waitForObject(":Market-Q (qa).Action_SmallButton"))
       activateItem(waitForObjectItem(":Market-Q (qa).Action_SmallButton", "Dismiss"))
       test.passes("Verify dismiss option is pass")
       
       clickButton(waitForObject(":Market-Q (qa).Action_SmallButton"))
       activateItem(waitForObjectItem(":Market-Q (qa).Action_SmallButton", "Reactivate"))
       test.passes("Verify Reactivate option is pass")
       
       clickButton(waitForObject(":Market-Q (qa).Action_SmallButton"))
       activateItem(waitForObjectItem(":Market-Q (qa).Action_SmallButton", "Delete"))
       clickButton(waitForObject(":Question.Yes_FixedSizeButton"))
       test.passes("Verify Delete option is pass")
       
       clickButton(waitForObject(":Market-Q (qa).Export to CSV_SmallButton"))
       mouseClick(waitForObject(":Save.Save In:_JButton"), 6, 7, 0, Button.Button1)
       mouseClick(waitForObjectItem(":Save.ComboBox.list_JList", "Desktop"), 50, 13, 0, Button.Button1)
       mouseClick(waitForObject(":Save.File Name:_JTextField"), 67, 7, 0, Button.Button1)
       type(waitForObject(":Save.File Name:_JTextField"), "exporttocsv")
       clickButton(waitForObject(":Save.Save_JButton"))
       clickButton(waitForObject(":Information.OK_FixedSizeButton"))
       test.passes("Verify Export to csv option is pass")
       clickButton(waitForObject(":Market-Q (qa).Log_SmallButton"))
       

       clickButton(waitForObject(":Alert Log.Workspace_LCDropDownButton"))
       activateItem(waitForObjectItem(":Alert Log.Workspace_LCDropDownButton", "July, 2019"))
       test.passes("Verify Select Log option from dropdown is pass")
       
       clickButton(waitForObject(":Alert Log.Quote Alerts_LCDropDownButton"))
       activateItem(waitForObjectItem(":Alert Log.Quote Alerts_LCDropDownButton", "News Alerts"))
       snooze(1)
       clickButton(waitForObject(":Alert Log.News Alerts_LCDropDownButton"))
       activateItem(waitForObjectItem(":Alert Log.News Alerts_LCDropDownButton", "Condition Alerts"))
       snooze(1)
       clickButton(waitForObject(":Alert Log.Condition Alerts_LCDropDownButton"))
       activateItem(waitForObjectItem(":Alert Log.Condition Alerts_LCDropDownButton", "Time Alerts"))
       test.passes("Verify Quotes, News & Condition Alerts option is pass")
       snooze(1)
       clickButton(waitForObject(":Alert Log.Export to CSV_FixedSizeButton"))
       type(waitForObject(":Save.File Name:_JTextField"), "alertcsv")
       clickButton(waitForObject(":Save.Save_JButton"))
       clickButton(waitForObject(":Information.OK_FixedSizeButton"))
       test.passes("Verify Export to csv option is pass")
       
       clickButton(waitForObject(":Alert Log.Print_FixedSizeButton"))
       clickButton(waitForObject(":Print Alert Log.OK_FixedSizeButton"))
       clickButton(waitForObject(":Print.Cancel_JButton"))
       test.passes("Verify print option is pass")
       clickButton(waitForObject(":Alert Log.Close_FixedSizeButton"))

       snooze(2)
       #Right click
       clickButton(waitForObject(":Market-Q (qa).Add_SmallButton"))
       type(waitForObject(":Add Quote Alert_LCTextField_2"), "AApl")
       mouseClick(waitForObject(":Add Quote Alert.com.futuresource.livecharts.dialogs.GridPanel$2_LCPanel"), 206, 7, 0, Button.Button1)
       mouseClick(waitForObject(":Add Quote Alert_LCTextField"), 29, 6, 0, Button.Button1)
       type(waitForObject(":Add Quote Alert_LCTextField"), "210")
       mouseClick(waitForObject(":Add Quote Alert_LCTextField_5"), 27, 7, 0, Button.Button1)
       type(waitForObject(":Add Quote Alert_LCTextField_5"), "203")
       clickButton(waitForObject(":Add Quote Alert.OK_FixedSizeButton"))
       clickButton(waitForObject(":Market-Q (qa).Add_SmallButton"))
       type(waitForObject(":Add Quote Alert_LCTextField_2"), "msft")
       mouseClick(waitForObject(":Add Quote Alert.com.futuresource.livecharts.dialogs.GridPanel$2_LCPanel"), 125, 14, 0, Button.Button1)
       mouseClick(waitForObject(":Add Quote Alert_LCTextField"), 40, 10, 0, Button.Button1)
       type(waitForObject(":Add Quote Alert_LCTextField"), "139")
       mouseClick(waitForObject(":Add Quote Alert_LCTextField_5"), 34, 1, 0, Button.Button1)
       type(waitForObject(":Add Quote Alert_LCTextField_5"), "130")
       clickButton(waitForObject(":Add Quote Alert.OK_FixedSizeButton"))
       
       mouseClick(waitForObjectItem(":Quote Alerts.com.futuresource.livecharts.newquotes.alerts.QuoteAlertTable_QuoteAlertTable_2", "0/1"), 24, 6, 4, Button.Button3)
       activateItem(waitForObjectItem(":Quote Alerts.com.futuresource.livecharts.newquotes.alerts.QuoteAlertTable_QuoteAlertTable_2", "View"))
       activateItem(waitForObjectItem(":Quote Alerts.View_JMenu", "Stock Options"))
       clickButton(waitForObject(":Stock Options_JButton"))
       test.passes("Verify View option is pass")
       
       mouseClick(waitForObjectItem(":Quote Alerts.com.futuresource.livecharts.newquotes.alerts.QuoteAlertTable_QuoteAlertTable_2", "0/1"), 71, 4, 4, Button.Button3)
       activateItem(waitForObjectItem(":Quote Alerts.com.futuresource.livecharts.newquotes.alerts.QuoteAlertTable_QuoteAlertTable_2", "Add To Symbol list"))
       activateItem(waitForObjectItem(":Quote Alerts.Add To Symbol list_JMenu", "Workspace Symbol Lists"))
       activateItem(waitForObjectItem(":Workspace Symbol Lists_JMenu_3", "Futures"))
       clickButton(waitForObject(":Information.OK_FixedSizeButton"))
       test.passes("Verify Add to symbol list option is pass")
       
       mouseClick(waitForObjectItem(":Quote Alerts.com.futuresource.livecharts.newquotes.alerts.QuoteAlertTable_QuoteAlertTable_2", "0/1"), 14, 7, 4, Button.Button3)
       activateItem(waitForObjectItem(":Quote Alerts.com.futuresource.livecharts.newquotes.alerts.QuoteAlertTable_QuoteAlertTable_2", "Notes"))
       type(waitForObject(":Note - INTERNATIONAL BUSINESS MACHS_JTextPane"), "Test Notes")
       clickButton(waitForObject(":Note - INTERNATIONAL BUSINESS MACHS.OK_FixedSizeButton"))
       test.passes("Verify Notes option is pass")
       
       mouseClick(waitForObjectItem(":Quote Alerts.com.futuresource.livecharts.newquotes.alerts.QuoteAlertTable_QuoteAlertTable_2", "0/1"), 25, 10, 4, Button.Button3)
       activateItem(waitForObjectItem(":Quote Alerts.com.futuresource.livecharts.newquotes.alerts.QuoteAlertTable_QuoteAlertTable_2", "Add"))
       clickButton(waitForObject(":Add Quote Alert.Cancel_FixedSizeButton"))
       test.passes("Verify Add option is pass")
       
       mouseClick(waitForObjectItem(":Quote Alerts.com.futuresource.livecharts.newquotes.alerts.QuoteAlertTable_QuoteAlertTable_2", "0/1"), 13, 5, 4, Button.Button3)
       activateItem(waitForObjectItem(":Quote Alerts.com.futuresource.livecharts.newquotes.alerts.QuoteAlertTable_QuoteAlertTable_2", "Edit"))
       type(waitForObject(":Edit Quote Alert_LCTextField"), "<Backspace>")
       type(waitForObject(":Edit Quote Alert_LCTextField"), "7")
       clickButton(waitForObject(":Edit Quote Alert.OK_FixedSizeButton"))
       test.passes("Verify Edit option is pass")
       
       mouseClick(waitForObjectItem(":Quote Alerts.com.futuresource.livecharts.newquotes.alerts.QuoteAlertTable_QuoteAlertTable_2", "0/1"), 18, 7, 4, Button.Button3)
       activateItem(waitForObjectItem(":Quote Alerts.com.futuresource.livecharts.newquotes.alerts.QuoteAlertTable_QuoteAlertTable_2", "Dismiss"))
       test.passes("Verify Dismiss option is pass")
       
       mouseClick(waitForObjectItem(":Quote Alerts.com.futuresource.livecharts.newquotes.alerts.QuoteAlertTable_QuoteAlertTable_2", "0/1"), 13, 2, 4, Button.Button3)
       activateItem(waitForObjectItem(":Quote Alerts.com.futuresource.livecharts.newquotes.alerts.QuoteAlertTable_QuoteAlertTable_2", "Reactivate"))
       test.passes("Verify Reactivate option is pass")
       
       mouseClick(waitForObjectItem(":Quote Alerts.com.futuresource.livecharts.newquotes.alerts.QuoteAlertTable_QuoteAlertTable_2", "0/1"), 11, 7, 4, Button.Button3)
       activateItem(waitForObjectItem(":Quote Alerts.com.futuresource.livecharts.newquotes.alerts.QuoteAlertTable_QuoteAlertTable_2", "Delete"))
       clickButton(waitForObject(":Question.Yes_FixedSizeButton"))
       test.passes("Verify Delete option is pass")
       
       mouseClick(waitForObjectItem(":Quote Alerts.com.futuresource.livecharts.newquotes.alerts.QuoteAlertTable_QuoteAlertTable_2", "0/1"), 22, 8, 4, Button.Button3)
       activateItem(waitForObjectItem(":Quote Alerts.com.futuresource.livecharts.newquotes.alerts.QuoteAlertTable_QuoteAlertTable_2", "Sort Ascending By"))
       activateItem(waitForObjectItem(":Quote Alerts.Sort Ascending By_JMenu", "Symbol"))
       test.passes("Verify Sort ascending by option is pass")
       
       mouseClick(waitForObjectItem(":Quote Alerts.com.futuresource.livecharts.newquotes.alerts.QuoteAlertTable_QuoteAlertTable_2", "0/1"), 19, 0, 4, Button.Button3)
       activateItem(waitForObjectItem(":Quote Alerts.com.futuresource.livecharts.newquotes.alerts.QuoteAlertTable_QuoteAlertTable_2", "Sort Descending By"))
       activateItem(waitForObjectItem(":Quote Alerts.Sort Descending By_JMenu", "Symbol"))
       test.passes("Verify Sort descending by option is pass")
       
       mouseClick(waitForObjectItem(":Quote Alerts.com.futuresource.livecharts.newquotes.alerts.QuoteAlertTable_QuoteAlertTable_2", "0/1"), 20, 8, 4, Button.Button3)
       activateItem(waitForObjectItem(":Quote Alerts.com.futuresource.livecharts.newquotes.alerts.QuoteAlertTable_QuoteAlertTable_2", "Select"))
       activateItem(waitForObjectItem(":Quote Alerts.Select_JMenu_2", "All"))
       mouseClick(waitForObjectItem(":Quote Alerts.com.futuresource.livecharts.newquotes.alerts.QuoteAlertTable_QuoteAlertTable_2", "0/1"), 7, 2, 4, Button.Button3)
       activateItem(waitForObjectItem(":Quote Alerts.com.futuresource.livecharts.newquotes.alerts.QuoteAlertTable_QuoteAlertTable_2", "Select"))
       activateItem(waitForObjectItem(":Quote Alerts.Select_JMenu_2", "Clear"))
       mouseClick(waitForObjectItem(":Quote Alerts.com.futuresource.livecharts.newquotes.alerts.QuoteAlertTable_QuoteAlertTable_2", "0/1"), 16, 1, 4, Button.Button3)
       activateItem(waitForObjectItem(":Quote Alerts.com.futuresource.livecharts.newquotes.alerts.QuoteAlertTable_QuoteAlertTable_2", "Select"))
       activateItem(waitForObjectItem(":Quote Alerts.Select_JMenu_2", "Active"))
       mouseClick(waitForObjectItem(":Quote Alerts.com.futuresource.livecharts.newquotes.alerts.QuoteAlertTable_QuoteAlertTable_2", "0/1"), 15, 10, 4, Button.Button3)
       activateItem(waitForObjectItem(":Quote Alerts.com.futuresource.livecharts.newquotes.alerts.QuoteAlertTable_QuoteAlertTable_2", "Select"))
       activateItem(waitForObjectItem(":Quote Alerts.Select_JMenu_2", "Clear"))
       test.passes("Verify Select option is pass")
       
       mouseClick(waitForObjectItem(":Quote Alerts.com.futuresource.livecharts.newquotes.alerts.QuoteAlertTable_QuoteAlertTable_2", "0/1"), 7, 5, 4, Button.Button3)
       activateItem(waitForObjectItem(":Quote Alerts.com.futuresource.livecharts.newquotes.alerts.QuoteAlertTable_QuoteAlertTable_2", "Set Date"))
       mouseClick(waitForObjectItem(":Quote Alerts.com.futuresource.livecharts.newquotes.alerts.QuoteAlertTable_QuoteAlertTable_2", "0/1"), 21, 7, 4, Button.Button3)
       activateItem(waitForObjectItem(":Quote Alerts.com.futuresource.livecharts.newquotes.alerts.QuoteAlertTable_QuoteAlertTable_2", "Set Date"))
       test.passes("Verify set date option is pass")
       
       mouseClick(waitForObjectItem(":Quote Alerts.com.futuresource.livecharts.newquotes.alerts.QuoteAlertTable_QuoteAlertTable_2", "0/1"), 25, 11, 4, Button.Button3)
       activateItem(waitForObjectItem(":Quote Alerts.com.futuresource.livecharts.newquotes.alerts.QuoteAlertTable_QuoteAlertTable_2", "Fired"))
       mouseClick(waitForObjectItem(":Quote Alerts.com.futuresource.livecharts.newquotes.alerts.QuoteAlertTable_QuoteAlertTable_2", "0/1"), 31, 0, 4, Button.Button3)
       activateItem(waitForObjectItem(":Quote Alerts.com.futuresource.livecharts.newquotes.alerts.QuoteAlertTable_QuoteAlertTable_2", "Fired"))
       test.passes("Verify fired option is pass")
       
       mouseClick(waitForObject(":Symbol_TableHeaderItemProxy_4"), 16, 13, 4, Button.Button3)
       activateItem(waitForObjectItem(":Quote Alerts_LCTableHeader", "Fired Date"))
       mouseClick(waitForObjectItem(":Quote Alerts.com.futuresource.livecharts.newquotes.alerts.QuoteAlertTable_QuoteAlertTable_2", "0/1"), 17, 4, 4, Button.Button3)
       activateItem(waitForObjectItem(":Quote Alerts.com.futuresource.livecharts.newquotes.alerts.QuoteAlertTable_QuoteAlertTable_2", "Fired Date"))
       test.passes("Verify fired date option is pass")
       
       mouseClick(waitForObjectItem(":Quote Alerts.com.futuresource.livecharts.newquotes.alerts.QuoteAlertTable_QuoteAlertTable_2", "0/1"), 10, 3, 4, Button.Button3)
       activateItem(waitForObjectItem(":Quote Alerts.com.futuresource.livecharts.newquotes.alerts.QuoteAlertTable_QuoteAlertTable_2", "Comment"))
       mouseClick(waitForObjectItem(":Quote Alerts.com.futuresource.livecharts.newquotes.alerts.QuoteAlertTable_QuoteAlertTable_2", "0/1"), 8, 6, 4, Button.Button3)
       activateItem(waitForObjectItem(":Quote Alerts.com.futuresource.livecharts.newquotes.alerts.QuoteAlertTable_QuoteAlertTable_2", "Comment"))
       test.passes("Verify comment option is pass")
       
       mouseClick(waitForObjectItem(":Quote Alerts.com.futuresource.livecharts.newquotes.alerts.QuoteAlertTable_QuoteAlertTable_2", "0/1"), 8, 2, 4, Button.Button3)
       activateItem(waitForObjectItem(":Quote Alerts.com.futuresource.livecharts.newquotes.alerts.QuoteAlertTable_QuoteAlertTable_2", "Fit Table to Window Width"))
       mouseClick(waitForObjectItem(":Quote Alerts.com.futuresource.livecharts.newquotes.alerts.QuoteAlertTable_QuoteAlertTable_2", "0/1"), 16, 5, 4, Button.Button3)
       activateItem(waitForObjectItem(":Quote Alerts.com.futuresource.livecharts.newquotes.alerts.QuoteAlertTable_QuoteAlertTable_2", "Fit Table to Window Width"))
       test.passes("Verify Fit Table to window width is pass")
       
       mouseClick(waitForObjectItem(":Quote Alerts.com.futuresource.livecharts.newquotes.alerts.QuoteAlertTable_QuoteAlertTable_2", "0/1"), 17, 9, 4, Button.Button3)
       activateItem(waitForObjectItem(":Quote Alerts.com.futuresource.livecharts.newquotes.alerts.QuoteAlertTable_QuoteAlertTable_2", "Print"))
       clickButton(waitForObject(":Print Quote Alerts.OK_FixedSizeButton"))
       clickButton(waitForObject(":Print.Cancel_JButton"))
       test.passes("Verify the print option is pass")
       
       mouseClick(waitForObjectItem(":Quote Alerts.com.futuresource.livecharts.newquotes.alerts.QuoteAlertTable_QuoteAlertTable_2", "0/1"), 18, 5, 4, Button.Button3)
       activateItem(waitForObjectItem(":Quote Alerts.com.futuresource.livecharts.newquotes.alerts.QuoteAlertTable_QuoteAlertTable_2", "Defaults"))
       activateItem(waitForObjectItem(":Quote Alerts.Defaults_JMenu", "Save Alerts Properties As Default"))
       clickButton(waitForObject(":Information.OK_FixedSizeButton"))
       test.passes("Save Alerts As Default is pass")
       
       mouseClick(waitForObjectItem(":Quote Alerts.com.futuresource.livecharts.newquotes.alerts.QuoteAlertTable_QuoteAlertTable_2", "0/1"), 12, 4, 4, Button.Button3)
       activateItem(waitForObjectItem(":Quote Alerts.com.futuresource.livecharts.newquotes.alerts.QuoteAlertTable_QuoteAlertTable_2", "Defaults"))
       activateItem(waitForObjectItem(":Quote Alerts.Defaults_JMenu", "Apply Default Properties to the Alerts"))
       test.passes("Apply default properties to alert windows is pass")
       
       mouseClick(waitForObjectItem(":Quote Alerts.com.futuresource.livecharts.newquotes.alerts.QuoteAlertTable_QuoteAlertTable_2", "0/1"), 17, 4, 4, Button.Button3)
       activateItem(waitForObjectItem(":Quote Alerts.com.futuresource.livecharts.newquotes.alerts.QuoteAlertTable_QuoteAlertTable_2", "Defaults"))
       activateItem(waitForObjectItem(":Quote Alerts.Defaults_JMenu", "Apply Default Properties to all Alerts Windows"))
       test.passes("Apply default properties to all alert windows is pass")
       
       mouseClick(waitForObjectItem(":Quote Alerts.com.futuresource.livecharts.newquotes.alerts.QuoteAlertTable_QuoteAlertTable_2", "0/1"), 16, 7, 4, Button.Button3)
       activateItem(waitForObjectItem(":Quote Alerts.com.futuresource.livecharts.newquotes.alerts.QuoteAlertTable_QuoteAlertTable_2", "Defaults"))
       activateItem(waitForObjectItem(":Quote Alerts.Defaults_JMenu", "Remove Default Alerts Properties"))
       clickButton(waitForObject(":Question.Yes_FixedSizeButton"))
       clickButton(waitForObject(":Information.OK_FixedSizeButton"))
       test.passes("Remove default Alert properties option is pass")
       
       #Display Properties
       mouseClick(waitForObjectItem(":Quote Alerts.com.futuresource.livecharts.newquotes.alerts.QuoteAlertTable_QuoteAlertTable_2", "0/1"), 3, 3, 4, Button.Button3)
       activateItem(waitForObjectItem(":Quote Alerts.com.futuresource.livecharts.newquotes.alerts.QuoteAlertTable_QuoteAlertTable_2", "Display Properties..."))
       test.compare(waitForObjectExists(":com.futuresource.livecharts.common.LCCardList$1.Text & Colors  _ListItemProxy_3").text, "Text & Colors")
       clickButton(waitForObject(":Alerts Display Properties.OK_FixedSizeButton"))

       mouseClick(waitForObject(":Quote Alerts_JViewport"), 62, 74, 4, Button.Button3)
       activateItem(waitForObjectItem(":Quote Alerts_JViewport", "Display Properties..."))
       mouseClick(waitForObject(":Alerts Display Properties.com.futuresource.livecharts.common.LCComboBox_LCComboBox"), 75, 6, 0, Button.Button1)
       mouseClick(waitForObjectItem(":Alerts Display Properties.ComboBox.list_JList", "Times New Roman"), 62, 1, 0, Button.Button1)
       mouseClick(waitForObject(":Alerts Display Properties.com.futuresource.livecharts.common.LCComboBox_LCComboBox_2"), 18, 5, 0, Button.Button1)
       mouseClick(waitForObjectItem(":Alerts Display Properties.ComboBox.list_JList", "12"), 10, 10, 0, Button.Button1)
       mouseClick(waitForObject(":Alerts Display Properties.Bold_LCCheckBox"), 4, 11, 0, Button.Button1)
       mouseClick(waitForObject(":Alerts Display Properties.Italic_LCCheckBox"), 8, 6, 0, Button.Button1)
       clickButton(waitForObject(":Alerts Display Properties. _FixedSizeButton"))
       clickButton(waitForObject(":Alerts Display Properties_FixedSizeButton"))
       clickButton(waitForObject(":Alerts Display Properties. _FixedSizeButton_2"))
       clickButton(waitForObject(":Alerts Display Properties_FixedSizeButton_2"))
       clickButton(waitForObject(":Alerts Display Properties. _FixedSizeButton_3"))
       clickButton(waitForObject(":Alerts Display Properties_FixedSizeButton_3"))
       clickButton(waitForObject(":Alerts Display Properties. _FixedSizeButton_3"))
       clickButton(waitForObject(":Alerts Display Properties_FixedSizeButton_4"))
       clickButton(waitForObject(":Alerts Display Properties.OK_FixedSizeButton"))
       test.passes("Verify Text&Colors option is pass")
       
       mouseClick(waitForObject(":Quote Alerts_JViewport"), 113, 104, 4, Button.Button3)
       activateItem(waitForObjectItem(":Quote Alerts_JViewport", "Display Properties..."))
       mouseClick(waitForObjectItem(":Alerts Display Properties.com.futuresource.livecharts.common.LCCardList$1_LCList", "Gridlines  "), 39, 0, 0, Button.Button1)
       mouseClick(waitForObject(":Alerts Display Properties.Show Horizontal Gridlines_LCCheckBox"), 2, 5, 0, Button.Button1)
       mouseClick(waitForObject(":Alerts Display Properties.Show Vertical Gridlines_LCCheckBox"), 3, 9, 0, Button.Button1)
       clickButton(waitForObject(":Alerts Display Properties.OK_FixedSizeButton"))
       mouseClick(waitForObject(":Quote Alerts_JViewport"), 132, 154, 4, Button.Button3)
       activateItem(waitForObjectItem(":Quote Alerts_JViewport", "Display Properties..."))
       mouseClick(waitForObject(":Alerts Display Properties.Show Horizontal Gridlines_LCCheckBox"), 3, 3, 0, Button.Button1)
       mouseClick(waitForObject(":Alerts Display Properties.Show Vertical Gridlines_LCCheckBox"), 0, 5, 0, Button.Button1)
       clickButton(waitForObject(":Alerts Display Properties. _FixedSizeButton_4"))
       clickButton(waitForObject(":Alerts Display Properties_FixedSizeButton_5"))
       clickButton(waitForObject(":Alerts Display Properties.OK_FixedSizeButton"))
       test.passes("Verify Gridlines option is pass")
       
       mouseClick(waitForObject(":Quote Alerts_JViewport"), 111, 126, 4, Button.Button3)
       activateItem(waitForObjectItem(":Quote Alerts_JViewport", "Display Properties..."))
       mouseClick(waitForObjectItem(":Alerts Display Properties.com.futuresource.livecharts.common.LCCardList$1_LCList", "Formatting  "), 26, 13, 0, Button.Button1)
       mouseClick(waitForObject(":Alerts Display Properties.Fit Alerts Table to Window Width_LCCheckBox"), 6, 6, 0, Button.Button1)
       clickButton(waitForObject(":Alerts Display Properties.OK_FixedSizeButton"))
       
       
       mouseClick(waitForObject(":Quote Alerts_JViewport"), 30, 118, 4, Button.Button3)
       activateItem(waitForObjectItem(":Quote Alerts_JViewport", "Display Properties..."))
       mouseClick(waitForObject(":Alerts Display Properties.Fit Alerts Table to Window Width_LCCheckBox"), 8, 11, 0, Button.Button1)
       clickButton(waitForObject(":Alerts Display Properties.OK_FixedSizeButton"))
       test.passes("Verify formatting option is pass")
       
       mouseClick(waitForObject(":Market-Q (qa).Alerts_LCLabel"), 22, 8, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_AlertTitlebarPanel", "New"))
       activateItem(waitForObjectItem(":Market-Q (qa).New_JMenu_10", "Alerts"))
       activateItem(waitForObjectItem(":Alerts_JMenu", "To the left"))
       test.compare(waitForObjectExists(":Market-Q (qa).Alerts_LCLabel").name, "Alerts")
       clickButton(waitForObject(":Market-Q (qa)_JButton_2"))
       
       mouseClick(waitForObject(":Market-Q (qa).Alerts_LCLabel"), 21, 5, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_AlertTitlebarPanel", "Show Window Title"))
       mouseClick(waitForObject(":Market-Q (qa). _LCLabel_4"), 6, 11, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_AlertTitlebarPanel", "Show Window Title"))
       test.compare(waitForObjectExists(":Market-Q (qa).Alerts_LCLabel").name, "Alerts")
       
       mouseClick(waitForObject(":Market-Q (qa).Alerts_LCLabel"), 10, 0, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_AlertTitlebarPanel", "Show Titlebar description"))
       test.compare(waitForObjectExists(":Market-Q (qa).Alerts_LCLabel_2").text, "Alerts")
       mouseClick(waitForObject(":Market-Q (qa).com.futuresource.livecharts.common.LCPanel_LCPanel_3"), 2, 4, 4, Button.Button3)
       
       mouseClick(waitForObject(":Market-Q (qa).Alerts_LCLabel_2"), 24, 11, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_AlertTitlebarPanel", "Customize Titlebar Description..."))
       mouseClick(waitForObject(":Titlebar Description Settings.Alerts_LCTextArea"), 37, 10, 0, Button.Button1)
       type(waitForObject(":Titlebar Description Settings.Alerts_LCTextArea"), "1")
       clickButton(waitForObject(":Titlebar Description Settings.OK_FixedSizeButton"))
       mouseDrag(waitForObject(":Market-Q (qa)_LCRootPane"), 741, 726, -4, 8, Modifier.None, Button.Button1)
       test.compare(waitForObjectExists(":Market-Q (qa).Alerts1_LCLabel").text, "Alerts1")
       
       mouseClick(waitForObject(":Market-Q (qa).Alerts1_LCLabel"), 12, 9, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_AlertTitlebarPanel", "Copy Out"))
       test.compare(waitForObjectExists(":Alerts.Alerts1_LCLabel").text, "Alerts1")
       mouseClick(waitForObject(":Alerts.Alerts1_LCLabel"), 1203, 8, 0, Button.Button1)
       clickButton(waitForObject(":Alerts_JButton"))
       
       mouseClick(waitForObject(":Market-Q (qa).Alerts1_LCLabel"), 26, 5, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_AlertTitlebarPanel_2", "Cut Window"))
       mouseClick(waitForObject(":Market-Q (qa).Empty Window_LCLabel"), 92, 8, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_9", "Paste Alerts"))
       activateItem(waitForObjectItem(":Market-Q (qa).Paste Alerts_JMenu_3", "In this window"))
       test.compare(waitForObjectExists(":Market-Q (qa).Alerts1_LCLabel").text, "Alerts1")
       dragItemBy(waitForObject(":Triggered Alerts_LCTitlePane"), 278, 6, -484, 196, Modifier.None, Button.Button1)

       snooze(2)
       mouseClick(waitForObject(":Market-Q (qa).Alerts1_LCLabel"), 27, 2, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_AlertTitlebarPanel", "Copy Window"))
       mouseClick(waitForObject(":Market-Q (qa).Alerts1_LCLabel"), 351, 10, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_AlertTitlebarPanel", "Paste Alerts"))
       activateItem(waitForObjectItem(":Market-Q (qa).Paste Alerts_JMenu", "To the left"))
       test.compare(waitForObjectExists(":Market-Q (qa).Alerts1_LCLabel").text, "Alerts1")
       mouseClick(waitForObject(":Market-Q (qa).Alerts1_LCLabel"), 618, 11, 0, Button.Button1)
       clickButton(waitForObject(":Market-Q (qa)_JButton_2"))
       
       mouseClick(waitForObject(":Market-Q (qa).Alerts1_LCLabel"), 31, 10, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_AlertTitlebarPanel", "Copy Window Image"))
       mouseClick(waitForObject(":Market-Q (qa).Alerts1_LCLabel"), 454, 2, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_AlertTitlebarPanel", "Paste Alerts"))
       activateItem(waitForObjectItem(":Market-Q (qa).Paste Alerts_JMenu", "To the left"))
       test.compare(waitForObjectExists(":Market-Q (qa).Alerts1_LCLabel").text, "Alerts1")
       mouseClick(waitForObject(":Market-Q (qa).Alerts1_LCLabel"), 598, 4, 0, Button.Button1)
       clickButton(waitForObject(":Market-Q (qa)_JButton_2"))
       
       mouseClick(waitForObject(":Market-Q (qa).Alerts1_LCLabel"), 5, 7, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_AlertTitlebarPanel", "Send Image by E-mail..."))
       test.passes("Verify Send Image By Email option is pass")
       
       mouseClick(waitForObject(":Market-Q (qa).Alerts1_LCLabel"), 10, 7, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_AlertTitlebarPanel", "Take Custom Screenshot"))
       mouseDrag(waitForObject(":Market-Q (qa).Alerts1_LCLabel"), 2, 2, 1260, 558, Modifier.None, Button.Button1)
       test.passes("Verify Take Custom Screenshot option is pass")
       
       mouseClick(waitForObject(":Market-Q (qa).Alerts1_LCLabel"), 27, 9, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_AlertTitlebarPanel", "Print"))
       clickButton(waitForObject(":Print Quote Alerts.OK_FixedSizeButton"))
       clickButton(waitForObject(":Print.Cancel_JButton"))
       test.passes("Verify Print option is pass")
       
       mouseClick(waitForObject(":Market-Q (qa).Alerts1_LCLabel"), 13, 16, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_AlertTitlebarPanel", "Display Properties"))
       test.compare(waitForObjectExists(":com.futuresource.livecharts.common.LCCardList$1.Text & Colors  _ListItemProxy_3").text, "Text & Colors")
       clickButton(waitForObject(":Alerts Display Properties.OK_FixedSizeButton"))
       
       mouseClick(waitForObject(":Market-Q (qa).Alerts1_LCLabel"), 18, 7, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_AlertTitlebarPanel", "Empty"))
       clickButton(waitForObject(":Market-Q (qa).Alerts_MonsoonNewPadButton"))
       test.passes("Verify Empty option is working is pass")
       
       mouseClick(waitForObject(":Market-Q (qa).Alerts_LCLabel"), 15, 3, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_AlertTitlebarPanel", "Close"))
       test.passes("Verify Close option is working is pass")

       snooze(40)
