def Calendar():
    
       testSettings.logScreenshotOnFail = True
       testSettings.logScreenshotOnError = True
       
       clickButton(waitForObject(":Market-Q (qa).Calendar_MonsoonNewPadButton"))
       snooze(5)
       list = waitForObject(":Market-Q (qa).com.futuresource.livecharts.common.LCComboBox_LCComboBox").itemcount
       for i in range(list):
        test.log("Value at index " + str(i) + ": " + list[i])
       #test.log("Selected index: %d: %s" % (list.selectedIndex, list.selectedOption))
       snooze(5)
       
#        clickButton(waitForObject(":Market-Q (qa).Calendar_MonsoonNewPadButton"))
#        test.compare(waitForObjectExists(":Market-Q (qa).Calendar_LCLabel").name, "Calendar")
#        
#        mouseClick(waitForObject(":Market-Q (qa)_CommonButton"), 10, 5, 0, Button.Button1)
#        snooze(2)
#        mouseClick(waitForObjectItem(":Market-Q (qa).ComboBox.list_JList", "Yesterday"), 63, 10, 0, Button.Button1)
#        snooze(1)

         
       
#        mouseClick(waitForObject(":Market-Q (qa).Calendar_LCLabel"), 15, 1, 4, Button.Button3)
#        activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "New"))
#        activateItem(waitForObjectItem(":Market-Q (qa).New_JMenu_6", "Chart"))
#        activateItem(waitForObjectItem(":Chart_JMenu_2", "To the left"))
#        test.compare(waitForObjectExists(":Market-Q (qa).Chart_LCLabel").name, "Chart")
#        clickButton(waitForObject(":Market-Q (qa)_JButton_5"))
#        
#        mouseClick(waitForObject(":Market-Q (qa)_JPanel_11"), 25, 0, 4, Button.Button3)
#        mouseClick(waitForObject(":Market-Q (qa).Calendar_LCLabel"), 9, 7, 4, Button.Button3)
#        activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Show Window Title"))
#        mouseClick(waitForObject(":Market-Q (qa). _LCLabel_4"), 7, 6, 4, Button.Button3)
#        activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Show Window Title"))
#        test.compare(waitForObjectExists(":Market-Q (qa).Calendar_LCLabel").name, "Calendar")
#        
#        mouseClick(waitForObject(":Market-Q (qa).Calendar_LCLabel"), 21, 2, 4, Button.Button3)
#        activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Show Titlebar description"))
#        test.compare(waitForObjectExists(":Market-Q (qa).Calendar_LCLabel_2").text, "Calendar")
#        
#        mouseClick(waitForObject(":Market-Q (qa).Calendar_LCLabel_2"), 16, 14, 4, Button.Button3)
#        activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Customize Titlebar Description..."))
#        type(waitForObject(":Titlebar Description Settings.Calendar_LCTextArea"), "Test ")
#        mouseClick(waitForObject(":Titlebar Description Settings.Foreground: _LCCheckBox"), 5, 13, 0, Button.Button1)
#        clickButton(waitForObject(":Titlebar Description Settings. _FixedSizeButton"))
#        clickButton(waitForObject(":Titlebar Description Settings_FixedSizeButton_3"))
#        mouseClick(waitForObject(":Titlebar Description Settings.Background: _LCCheckBox"), 5, 9, 0, Button.Button1)
#        clickButton(waitForObject(":Titlebar Description Settings. _FixedSizeButton_2"))
#        clickButton(waitForObject(":Titlebar Description Settings_FixedSizeButton_2"))
#        mouseClick(waitForObject(":Titlebar Description Settings.Font: _LCCheckBox"), 12, 8, 0, Button.Button1)
#        mouseClick(waitForObject(":Titlebar Description Settings.com.futuresource.livecharts.common.LCComboBox_LCComboBox_2"), 100, 9, 0, Button.Button1)
#        mouseClick(waitForObjectItem(":Titlebar Description Settings.ComboBox.list_JList", "Times New Roman"), 80, 4, 0, Button.Button1)
#        mouseClick(waitForObject(":Titlebar Description Settings_CommonButton_2"), 9, 4, 0, Button.Button1)
#        mouseClick(waitForObjectItem(":Titlebar Description Settings.ComboBox.list_JList", "13"), 19, 5, 0, Button.Button1)
#        mouseClick(waitForObject(":Titlebar Description Settings.Bold_LCCheckBox"), 7, 6, 0, Button.Button1)
#        mouseClick(waitForObject(":Titlebar Description Settings.com.futuresource.livecharts.common.FontChooser_FontChooser"), 222, 9, 0, Button.Button1)
#        mouseClick(waitForObject(":Titlebar Description Settings.Italic_LCCheckBox"), 2, 10, 0, Button.Button1)
#        clickButton(waitForObject(":Titlebar Description Settings.OK_FixedSizeButton"))
#        
#        mouseClick(waitForObject(":Market-Q (qa).Test Calendar_LCLabel"), 23, 7, 4, Button.Button3)
#        activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Copy Out"))
#        test.compare(waitForObjectExists(":Calendar.Test Calendar_LCLabel").text, "Test Calendar")
#        
#        mouseClick(waitForObject(":Calendar.Test Calendar_LCLabel"), 1196, 19, 0, Button.Button1)
#        clickButton(waitForObject(":Calendar_JButton"))
#        mouseClick(waitForObject(":Market-Q (qa).Test Calendar_LCLabel"), 32, 7, 4, Button.Button3)
#        activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Cut Window"))
#        mouseClick(waitForObject(":Market-Q (qa).Empty Window_LCLabel"), 27, 1, 4, Button.Button3)
#        activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Paste Calendar"))
#        activateItem(waitForObjectItem(":Market-Q (qa).Paste Calendar_JMenu", "In this window"))
#        test.compare(waitForObjectExists(":Market-Q (qa).Test Calendar_LCLabel").text, "Test Calendar")
#        
#        mouseClick(waitForObject(":Market-Q (qa).Test Calendar_LCLabel"), 9, 4, 4, Button.Button3)
#        activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Copy Window"))
#        mouseClick(waitForObject(":Market-Q (qa).Test Calendar_LCLabel"), 19, 10, 4, Button.Button3)
#        activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Paste Calendar"))
#        activateItem(waitForObjectItem(":Market-Q (qa).Paste Calendar_JMenu", "To the left"))
#        test.compare(waitForObjectExists(":Market-Q (qa).Test Calendar_LCLabel").text, "Test Calendar")
#        
#        mouseClick(waitForObject(":Market-Q (qa).Test Calendar_LCLabel"), 553, 9, 0, Button.Button1)
#        clickButton(waitForObject(":Market-Q (qa)_JButton_5"))
#        
#        mouseClick(waitForObject(":Market-Q (qa).Test Calendar_LCLabel"), 46, 7, 4, Button.Button3)
#        activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Copy Window Image"))
#        mouseClick(waitForObject(":Market-Q (qa).Test Calendar_LCLabel"), 10, 9, 4, Button.Button3)
#        activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Paste Calendar"))
#        activateItem(waitForObjectItem(":Market-Q (qa).Paste Calendar_JMenu", "To the left"))
#        test.compare(waitForObjectExists(":Market-Q (qa).Test Calendar_LCLabel").text, "Test Calendar")
#        
#        mouseClick(waitForObject(":Market-Q (qa).Test Calendar_LCLabel"), 15, 7, 4, Button.Button3)
#        activateItem(waitForObjectItem(":Market-Q (qa)_JPanel_4", "Send Image by E-mail..."))
#        
#        mouseClick(waitForObject(":Market-Q (qa).Test Calendar_LCLabel"), 585, 11, 0, Button.Button1)
#        clickButton(waitForObject(":Market-Q (qa)_JButton_5"))
#        mouseClick(waitForObject(":Market-Q (qa).Test Calendar_LCLabel"), 18, 9, 4, Button.Button3)
#        activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Take Custom Screenshot"))
#        mouseDrag(waitForObject(":Market-Q (qa).Calendar_CalendarPad"), 2, 2, 1338, 574, Modifier.None, Button.Button1)
#        
#        mouseClick(waitForObject(":Market-Q (qa).Test Calendar_LCLabel"), 10, 5, 4, Button.Button3)
#        activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Print"))
#        mouseClick(waitForObject(":Market-Q (qa).Test Calendar_LCLabel"), 18, 11, 4, Button.Button3)
#        activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Print"))
#        
#        mouseClick(waitForObject(":Market-Q (qa).Test Calendar_LCLabel"), 9, 12, 4, Button.Button3)
#        activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Display Properties"))
#        test.compare(waitForObjectExists(":com.futuresource.livecharts.common.LCCardList$1.General  _ListItemProxy").text, "General")
#        clickButton(waitForObject(":Calendar Properties.OK_FixedSizeButton"))
#        
#        mouseClick(waitForObject(":Market-Q (qa).Test Calendar_LCLabel"), 19, 1, 4, Button.Button3)
#        activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Empty"))
#        
#        clickButton(waitForObject(":Market-Q (qa).Calendar_MonsoonNewPadButton"))
#        mouseClick(waitForObject(":Market-Q (qa).Calendar_LCLabel"), 11, 2, 4, Button.Button3)
#        activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Close"))
#        
#        clickButton(waitForObject(":Market-Q (qa).Calendar_MonsoonNewPadButton"))
#        mouseClick(waitForObject(":Market-Q (qa)_LCTextField_17"), 60, 4, 0, Button.Button1)
#        type(waitForObject(":Market-Q (qa)_LCTextField_17"), "<#20>")
#        type(waitForObject(":Market-Q (qa)_LCTextField_17"), "I")
#        type(waitForObject(":Market-Q (qa)_LCTextField_24"), "BM,")
#        type(waitForObject(":Market-Q (qa)_LCTextField_18"), "M")
#        type(waitForObject(":Market-Q (qa)_LCTextField_24"), "SFT,ORCL,GOOGL,GOOG,ICE")
#        type(waitForObject(":Market-Q (qa)_LCTextField_24"), "<Return>")
#        clickButton(waitForObject(":Market-Q (qa)_LCAppendedButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", "All Events"), 3, 8, 0, Button.Button1)
#        
#        clickButton(waitForObject(":Market-Q (qa)_LCAppendedButton_2"))
#        type(waitForObject(":Symbol Lookup_LCTextField"), "<Backspace>")
#        type(waitForObject(":Symbol Lookup_LCTextField"), "IBM")
#        clickButton(waitForObject(":Symbol Lookup.Search_FixedSizeButton"))
#        test.compare(waitForObjectExists(":com.futuresource.livecharts.dialogs.symbollookup.SymbolLookupDialog$SymbolsTable.IBM_TableItemProxy").text, "IBM")
#        dragItemBy(waitForObject(":Symbol Lookup_LCTitlePane"), 165, 12, -696, -540, Modifier.None, Button.Button1)
#        clickButton(waitForObject(":Symbol Lookup.OK_FixedSizeButton"))
#        
#        clickButton(waitForObject(":Market-Q (qa)_LCAppendedButton"))
#        mouseClick(waitForObject(":Market-Q (qa)_CommonButton"), 3, 3, 0, Button.Button1)
#        snooze(1)
#        mouseClick(waitForObjectItem(":Market-Q (qa).ComboBox.list_JList", "Today"), 72, 5, 0, Button.Button1)
#        mouseClick(waitForObject(":Market-Q (qa)_LCTextField_24"), 51, 2, 0, Button.Button1)
#        type(waitForObject(":Market-Q (qa)_LCTextField_24"), "<Right>")
#        type(waitForObject(":Market-Q (qa)_LCTextField_24"), ",")
#        type(waitForObject(":Market-Q (qa)_LCTextField_18"), "M")
#        type(waitForObject(":Market-Q (qa)_LCTextField_24"), "SFT,ORCL,GOOGL,GOOG,ICE")
#        clickButton(waitForObject(":Market-Q (qa)_LCAppendedButton"))
#        
#        mouseClick(waitForObject(":Market-Q (qa).com.futuresource.livecharts.common.LCComboBox_LCComboBox"), 104, 5, 0, Button.Button1)
#        snooze(2)
#        test.compare(str(waitForObjectExists(":Market-Q (qa).com.futuresource.livecharts.common.LCComboBox_LCComboBox").selecteditem), "Today")
#        test.compare(waitForObjectExists(":Market-Q (qa).com.futuresource.livecharts.common.LCComboBox_LCComboBox").selecteditem["class"], "com.futuresource.livecharts.calendar.CalendarPad$MyQuickViewComponent$MyQuickViewOption")
#        test.compare(waitForObjectExists(":Market-Q (qa).com.futuresource.livecharts.common.LCComboBox_LCComboBox").selecteditem.upcomingrange, False)
#        
#        mouseClick(waitForObject(":Market-Q (qa)_CommonButton"), 10, 5, 0, Button.Button1)
#        snooze(2)
#        mouseClick(waitForObjectItem(":Market-Q (qa).ComboBox.list_JList", "Yesterday"), 63, 10, 0, Button.Button1)
#        snooze(1)
#        test.compare(str(waitForObjectExists(":Market-Q (qa).com.futuresource.livecharts.common.LCComboBox_LCComboBox").selecteditem), "Yesterday")
#        test.compare(waitForObjectExists(":Market-Q (qa).com.futuresource.livecharts.common.LCComboBox_LCComboBox").selecteditem["class"], "com.futuresource.livecharts.calendar.CalendarPad$MyQuickViewComponent$MyQuickViewOption")
#        test.compare(waitForObjectExists(":Market-Q (qa).com.futuresource.livecharts.common.LCComboBox_LCComboBox").selecteditem.upcomingrange, False)
#        
#        mouseClick(waitForObject(":Market-Q (qa).com.futuresource.livecharts.common.LCComboBox_LCComboBox"), 75, 1, 0, Button.Button1)
#        snooze(2)
#        mouseClick(waitForObjectItem(":Market-Q (qa).ComboBox.list_JList", "Last 7 Days"), 51, 7, 0, Button.Button1)
#        snooze(1)
#        test.compare(str(waitForObjectExists(":Market-Q (qa).com.futuresource.livecharts.common.LCComboBox_LCComboBox").selecteditem), "Last 7 Days")
#        test.compare(waitForObjectExists(":Market-Q (qa).com.futuresource.livecharts.common.LCComboBox_LCComboBox").selecteditem["class"], "com.futuresource.livecharts.calendar.CalendarPad$MyQuickViewComponent$MyQuickViewOption")
#        test.compare(waitForObjectExists(":Market-Q (qa).com.futuresource.livecharts.common.LCComboBox_LCComboBox").selecteditem.upcomingrange, False)
#        
#        mouseClick(waitForObject(":Market-Q (qa).com.futuresource.livecharts.common.LCComboBox_LCComboBox"), 63, 11, 0, Button.Button1)
#        snooze(2)
#        mouseClick(waitForObjectItem(":Market-Q (qa).ComboBox.list_JList", "Last 30 Days"), 64, 3, 0, Button.Button1)
#        snooze(1)
#        test.compare(str(waitForObjectExists(":Market-Q (qa).com.futuresource.livecharts.common.LCComboBox_LCComboBox").selecteditem), "Last 30 Days")
#        test.compare(waitForObjectExists(":Market-Q (qa).com.futuresource.livecharts.common.LCComboBox_LCComboBox").selecteditem["class"], "com.futuresource.livecharts.calendar.CalendarPad$MyQuickViewComponent$MyQuickViewOption")
#        test.compare(waitForObjectExists(":Market-Q (qa).com.futuresource.livecharts.common.LCComboBox_LCComboBox").selecteditem.upcomingrange, False)
#        
#        mouseClick(waitForObject(":Market-Q (qa).com.futuresource.livecharts.common.LCComboBox_LCComboBox"), 90, 5, 0, Button.Button1)
#        snooze(2)
#        mouseClick(waitForObjectItem(":Market-Q (qa).ComboBox.list_JList", "Last 12 Months"), 77, 10, 0, Button.Button1)
#        snooze(1)
#        test.compare(str(waitForObjectExists(":Market-Q (qa).com.futuresource.livecharts.common.LCComboBox_LCComboBox").selecteditem), "Last 12 Months")
#        test.compare(waitForObjectExists(":Market-Q (qa).com.futuresource.livecharts.common.LCComboBox_LCComboBox").selecteditem["class"], "com.futuresource.livecharts.calendar.CalendarPad$MyQuickViewComponent$MyQuickViewOption")
#        test.compare(waitForObjectExists(":Market-Q (qa).com.futuresource.livecharts.common.LCComboBox_LCComboBox").selecteditem.upcomingrange, False)
#        
#        mouseClick(waitForObject(":Market-Q (qa).com.futuresource.livecharts.common.LCComboBox_LCComboBox"), 96, 2, 0, Button.Button1)
#        snooze(2)
#        mouseClick(waitForObjectItem(":Market-Q (qa).ComboBox.list_JList", "Upcoming Events"), 66, 9, 0, Button.Button1)
#        snooze(1)
#        test.compare(str(waitForObjectExists(":Market-Q (qa).com.futuresource.livecharts.common.LCComboBox_LCComboBox").selecteditem), "Upcoming Events")
#        test.compare(waitForObjectExists(":Market-Q (qa).com.futuresource.livecharts.common.LCComboBox_LCComboBox").selecteditem["class"], "com.futuresource.livecharts.calendar.CalendarPad$MyQuickViewComponent$MyQuickViewOption")
#        test.compare(waitForObjectExists(":Market-Q (qa).com.futuresource.livecharts.common.LCComboBox_LCComboBox").selecteditem.upcomingrange, True)
#        
#        mouseClick(waitForObject(":Market-Q (qa).com.futuresource.livecharts.common.LCComboBox_LCComboBox"), 101, 8, 0, Button.Button1)
#        snooze(1)
#        mouseClick(waitForObjectItem(":Market-Q (qa).ComboBox.list_JList", "Custom Range"), 79, 4, 0, Button.Button1)
#        snooze(1)
#        clickButton(waitForObject(":Market-Q (qa)_LCAppendedButton_3"))
#        mouseClick(waitForObject(":Market-Q (qa).1_JLabel"), 12, 7, 0, Button.Button1)
#        clickButton(waitForObject(":Market-Q (qa)_LCAppendedButton_8"))
#        mouseClick(waitForObject(":Market-Q (qa).6_JLabel"), 16, 12, 0, Button.Button1)
#        clickButton(waitForObject(":Market-Q (qa)_LCAppendedButton"))
#        test.compare(str(waitForObjectExists(":Market-Q (qa).com.futuresource.livecharts.common.LCComboBox_LCComboBox").selecteditem), "Custom Range")
#        test.compare(waitForObjectExists(":Market-Q (qa).com.futuresource.livecharts.common.LCComboBox_LCComboBox").selecteditem["class"], "com.futuresource.livecharts.calendar.CalendarPad$MyQuickViewComponent$2")
#        test.compare(waitForObjectExists(":Market-Q (qa).com.futuresource.livecharts.common.LCComboBox_LCComboBox").selecteditem.upcomingrange, False)
#        
#        clickButton(waitForObject(":Market-Q (qa).Refresh_TitlebarButton"))
#        
#        mouseClick(waitForObject(":Market-Q (qa)_CommonButton"), 6, 5, 0, Button.Button1)
#        snooze(1)
#        mouseClick(waitForObjectItem(":Market-Q (qa).ComboBox.list_JList", "Last 12 Months"), 78, 1, 0, Button.Button1)
#        
#        clickButton(waitForObject(":Market-Q (qa).Calendar_LCDropDownButton"))
#        snooze(1)
#        activateItem(waitForObjectItem(":Market-Q (qa).Calendar_LCDropDownButton", "Agenda"))
#        test.compare(waitForObjectExists(":Market-Q (qa).Agenda_LCDropDownButton").actioncommand, "Agenda")
#        
#        mouseClick(waitForObject(":Market-Q (qa).Upcoming Events_LCToggleButton"), 60, 10, 0, Button.Button1)
#        clickButton(waitForObject(":Market-Q (qa).Agenda_LCDropDownButton"))
#        activateItem(waitForObjectItem(":Market-Q (qa).Agenda_LCDropDownButton", "Calendar"))
#        mouseClick(waitForObject(":Market-Q (qa)_CommonButton"), 8, 8, 0, Button.Button1)
#        mouseClick(waitForObjectItem(":Market-Q (qa).ComboBox.list_JList", "Last 30 Days"), 77, 3, 0, Button.Button1)
#        mouseClick(waitForObject(":Market-Q (qa).Upcoming Events_LCToggleButton"), 12, 4, 0, Button.Button1)
#        mouseClick(waitForObject(":Market-Q (qa).Upcoming Events_LCToggleButton"), 34, 12, 0, Button.Button1)

       snooze(40)
