def DataTable():
    
       testSettings.logScreenshotOnFail = True
       testSettings.logScreenshotOnError = True
       

       clickButton(waitForObject(":Market-Q (qa).Data Table_MonsoonNewPadButton"))
       test.compare(waitForObjectExists(":Market-Q (qa).Data Table_LCLabel").name, "Data Table")
       
       clickButton(waitForObject(":Market-Q (qa)_JButton_2"))
       clickButton(waitForObject(":Market-Q (qa).Data Table_MonsoonNewPadButton"))
       dragAndDrop(waitForObject(":Market-Q (qa).Data Table_MonsoonNewPadButton"), 25, 8, ":Market-Q (qa)_JPanel_6", 1054, 30, DnD.DropNone)
       test.compare(waitForObjectExists(":Market-Q (qa).Data Table_LCLabel").name, "Data Table")
       clickButton(waitForObject(":Market-Q (qa)_JButton"))
       
       #Interval Dropdown
       mouseClick(waitForObject(":Market-Q (qa)_CommonButton"), 7, 6, 0, Button.Button1)
       mouseClick(waitForObjectItem(":Market-Q (qa).ComboBox.list_JList", "15 Minutes"), 65, 3, 0, Button.Button1)
       test.compare(waitForObjectExists(":Market-Q (qa)_LCTextField_2").text, "15 Minutes")
       mouseClick(waitForObject(":Market-Q (qa)_CommonButton"), 8, 6, 0, Button.Button1)
       mouseClick(waitForObjectItem(":Market-Q (qa).ComboBox.list_JList", "30 Minutes"), 53, 10, 0, Button.Button1)
       test.compare(waitForObjectExists(":Market-Q (qa)_LCTextField_2").text, "30 Minutes")
       mouseClick(waitForObject(":Market-Q (qa)_CommonButton"), 4, 7, 0, Button.Button1)
       mouseClick(waitForObjectItem(":Market-Q (qa).ComboBox.list_JList", "60 Minutes"), 63, 2, 0, Button.Button1)
       test.compare(waitForObjectExists(":Market-Q (qa)_LCTextField_2").text, "60 Minutes")
       mouseClick(waitForObject(":Market-Q (qa)_CommonButton"), 10, 6, 0, Button.Button1)
       mouseClick(waitForObjectItem(":Market-Q (qa).ComboBox.list_JList", "Daily"), 56, 7, 0, Button.Button1)
       test.compare(waitForObjectExists(":Market-Q (qa)_LCTextField_2").text, "Daily")
       mouseClick(waitForObject(":Market-Q (qa)_CommonButton"), 6, 5, 0, Button.Button1)
       mouseClick(waitForObjectItem(":Market-Q (qa).ComboBox.list_JList", "Weekly"), 54, 12, 0, Button.Button1)
       test.compare(waitForObjectExists(":Market-Q (qa)_LCTextField_2").text, "Weekly")
       mouseClick(waitForObject(":Market-Q (qa)_CommonButton"), 10, 3, 0, Button.Button1)
       mouseClick(waitForObjectItem(":Market-Q (qa).ComboBox.list_JList", "Monthly"), 44, 2, 0, Button.Button1)
       test.compare(waitForObjectExists(":Market-Q (qa)_LCTextField_2").text, "Monthly")
       mouseClick(waitForObject(":Market-Q (qa)_CommonButton"), 8, 4, 0, Button.Button1)
       mouseClick(waitForObjectItem(":Market-Q (qa).ComboBox.list_JList", "Quarterly"), 64, 2, 0, Button.Button1)
       test.compare(waitForObjectExists(":Market-Q (qa)_LCTextField_2").text, "Quarterly")
       mouseClick(waitForObject(":Market-Q (qa)_CommonButton"), 2, 3, 0, Button.Button1)
       mouseClick(waitForObjectItem(":Market-Q (qa).ComboBox.list_JList", "Yearly"), 48, 8, 0, Button.Button1)
       test.compare(waitForObjectExists(":Market-Q (qa)_LCTextField_2").text, "Yearly")
       test.passes("Verify Time Interval in the dropdown pass")
       
       clickButton(waitForObject(":Market-Q (qa)_TitlebarButton_6"))
       mouseClick(waitForObject(":Market-Q (qa).10T_LCLabel"), 11, 10, 0, Button.Button1)
       snooze(3)
       clickButton(waitForObject(":Market-Q (qa)_TitlebarButton_6"))
       mouseClick(waitForObject(":Market-Q (qa).10S_LCLabel"), 2, 9, 0, Button.Button1)
       snooze(3)
       clickButton(waitForObject(":Market-Q (qa)_TitlebarButton_6"))
       mouseClick(waitForObject(":Market-Q (qa).1_LCLabel"), 3, 0, 0, Button.Button1)
       snooze(3)
       clickButton(waitForObject(":Market-Q (qa)_TitlebarButton_6"))
       mouseClick(waitForObject(":Market-Q (qa).1000V_LCLabel"), 30, 9, 0, Button.Button1)
       snooze(3)
       mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.common.datatablecomp.DTAbstractColumn$1_PrinterFriendlyTable_2", "0/6"), 76, 13, 0, Button.Button1)
       test.compare(waitForObjectExists(":com.futuresource.livecharts.common.datatablecomp.DTAbstractColumn$1.1,000_TableItemProxy").text, "1,000")
       clickButton(waitForObject(":Market-Q (qa)_TitlebarButton_6"))
       mouseClick(waitForObject(":Market-Q (qa).2P_LCLabel"), 7, 4, 0, Button.Button1)
       snooze(3)
       clickButton(waitForObject(":Market-Q (qa)_TitlebarButton_6"))
       mouseClick(waitForObject(":Market-Q (qa).0.1R_LCLabel"), 9, 14, 0, Button.Button1)
       snooze(3)
       clickButton(waitForObject(":Market-Q (qa)_TitlebarButton_6"))
       mouseClick(waitForObject(":Market-Q (qa).D_LCLabel"), 5, 5, 0, Button.Button1)
       snooze(3)
       clickButton(waitForObject(":Market-Q (qa)_TitlebarButton_6"))
       mouseClick(waitForObject(":Market-Q (qa).W_LCLabel"), 14, 11, 0, Button.Button1)
       snooze(3)
       clickButton(waitForObject(":Market-Q (qa)_TitlebarButton_6"))
       mouseClick(waitForObject(":Market-Q (qa).M_LCLabel"), 3, 13, 0, Button.Button1)
       snooze(3)
       test.passes("Verify clock like icon which has different intervals in it is pass")
       
       #TitleBar Options
       mouseClick(waitForObject(":Market-Q (qa).Data Table_LCLabel"), 17, 4, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "New"))
       activateItem(waitForObjectItem(":Market-Q (qa).New_JMenu_8", "Data Table"))
       activateItem(waitForObjectItem(":Data Table_JMenu", "In this window"))
       test.compare(waitForObjectExists(":Market-Q (qa).Data Table_LCLabel_2").name, "Data Table")
       
       mouseClick(waitForObject(":Market-Q (qa)_JPanel_8"), 62, 1, 4, Button.Button3)
       mouseClick(waitForObject(":Market-Q (qa).Data Table_LCLabel_2"), 30, 3, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_2", "Show Window Title"))
       mouseClick(waitForObject(":Market-Q (qa). _LCLabel_2"), 8, 2, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_2", "Show Window Title"))
       test.compare(waitForObjectExists(":Market-Q (qa).Data Table_LCLabel_2").name, "Data Table")
       
       mouseClick(waitForObject(":Market-Q (qa).Data Table_LCLabel_2"), 34, 5, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_2", "Show Titlebar description"))
       test.compare(waitForObjectExists(":Market-Q (qa).Data Table_LCLabel_3").text, "Data Table")
       
       mouseClick(waitForObject(":Market-Q (qa).Data Table_LCLabel_3"), 22, 6, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_2", "Customize Titlebar Description..."))
       mouseClick(waitForObject(":Titlebar Description Settings.Data Table_LCTextArea"), 117, 11, 0, Button.Button1)
       type(waitForObject(":Titlebar Description Settings.Data Table_LCTextArea"), "1")
       clickButton(waitForObject(":Titlebar Description Settings.OK_FixedSizeButton"))
       test.compare(waitForObjectExists(":Market-Q (qa).Data Table1_LCLabel").text, "Data Table1")
       
       mouseClick(waitForObject(":Market-Q (qa).Data Table1_LCLabel"), 6, 5, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_2", "Copy Out"))
       test.compare(waitForObjectExists(":Market-Q (qa).Data Table1_LCLabel").text, "Data Table1")
       
       clickButton(waitForObject(":Market-Q (qa).Data Table-1_MonsoonTabButton"))
       clickButton(waitForObject(":Market-Q (qa)_JButton_2"))
       clickButton(waitForObject(":Question.Yes_FixedSizeButton"))
       clickButton(waitForObject(":Market-Q (qa).Data Table_MonsoonNewPadButton"))
       
       mouseClick(waitForObject(":Market-Q (qa).Data Table_LCLabel"), 25, 1, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Cut Window"))
       mouseClick(waitForObject(":Market-Q (qa)_JPanel_3"), 516, 62, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Paste Data Table"))
       activateItem(waitForObjectItem(":Market-Q (qa).Paste Data Table_JMenu", "In this window"))
       test.compare(waitForObjectExists(":Market-Q (qa).Data Table_LCLabel").name, "Data Table")
       
       mouseClick(waitForObject(":Market-Q (qa).Data Table_LCLabel"), 35, 1, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Copy Window"))      
       mouseClick(waitForObject(":Market-Q (qa).Data Table_LCLabel"), 19, 8, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Paste Data Table"))
       activateItem(waitForObjectItem(":Market-Q (qa).Paste Data Table_JMenu_2", "In this window"))
       test.compare(waitForObjectExists(":Market-Q (qa).Data Table_DataTablePad").name, "Data Table")
       
       mouseClick(waitForObject(":Market-Q (qa)_JPanel_8"), 41, 1, 4, Button.Button3)
       mouseClick(waitForObject(":Market-Q (qa).Data Table_LCLabel_2"), 23, 10, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_2", "Copy Window Image"))
       mouseClick(waitForObject(":Market-Q (qa).Data Table_LCLabel_2"), 34, 2, 4, Button.Button3)
       mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.common.datatablecomp.DTAbstractColumn$1_PrinterFriendlyTable", "15/0"), 269, 1, 0, Button.Button1)
       mouseClick(waitForObject(":Market-Q (qa).Data Table_LCLabel_2"), 12, 5, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_2", "Paste Data Table"))
       activateItem(waitForObjectItem(":Market-Q (qa).Paste Data Table_JMenu_3", "In this window"))
       test.compare(waitForObjectExists(":Market-Q (qa).Data Table_LCLabel_4").name, "Data Table")
       snooze(2)
       
       mouseClick(waitForObject(":Market-Q (qa).Data Table_LCLabel_4"), 32, 2, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_8", "Send Image by E-mail..."))
       test.passes("Verify Send Image By Email.. is pass")
       snooze(1)
       
       mouseClick(waitForObject(":Market-Q (qa).Data Table_LCLabel_4"), 30, 0, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_8", "Take Custom Screenshot"))
       dragItemBy(waitForObject(":Market-Q (qa).Data Table_DataTablePad"), 24, 2, 1290, 560, Modifier.None, Button.Button1)
       test.passes("Verify Take Custom Screenshot is pass")
       
       mouseClick(waitForObject(":Market-Q (qa).Data Table_LCLabel_4"), 10, 4, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_8", "Print"))
       clickButton(waitForObject(":Print Data Table.OK_FixedSizeButton"))
       clickButton(waitForObject(":Print.Cancel_JButton"))
       test.passes("Verify print option is pass")
       
       mouseClick(waitForObject(":Market-Q (qa).Data Table_LCLabel_4"), 5, 2, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_8", "Display Properties"))
       test.compare(waitForObjectExists(":com.futuresource.livecharts.common.LCCardList$1.Text & Colors  _ListItemProxy_2").text, "Text & Colors")
       clickButton(waitForObject(":Data Table Display Properties.OK_FixedSizeButton"))
       
       mouseClick(waitForObject(":Market-Q (qa).Data Table_LCLabel_4"), 18, 4, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_8", "Empty"))
       test.passes("Verify Empty option pass")
       
       clickButton(waitForObject(":Market-Q (qa).Data Table_MonsoonNewPadButton"))
       mouseClick(waitForObject(":Market-Q (qa)_JPanel_6"), 40, 0, 4, Button.Button3)
       mouseClick(waitForObject(":Market-Q (qa).Data Table_LCLabel"), 20, 7, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Close"))
       test.passes("Verify Close Option is pass")
       clickButton(waitForObject(":Market-Q (qa).Data Table_MonsoonNewPadButton"))

       #Right click options
       mouseClick(waitForObject(":Close_TableHeaderItemProxy"), 37, 3, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_JTableHeader", "View"))
       activateItem(waitForObjectItem(":Market-Q (qa).View_JMenu_2", "Data Table"))
       clickButton(waitForObject(":Data Table.Data Table-2_MonsoonTabButton"))
       clickButton(waitForObject(":Data Table.Data Table-1_MonsoonTabButton"))
       clickButton(waitForObject(":Data Table_JButton"))
       clickButton(waitForObject(":Question.Yes_FixedSizeButton"))
       test.passes("Right click and check view individual window is opening or not is pass")
       
       mouseClick(waitForObject(":Close_TableHeaderItemProxy"), 39, 4, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_JTableHeader", "Add To Symbol list"))
       activateItem(waitForObjectItem(":Market-Q (qa).Add To Symbol list_JMenu", "Workspace Symbol Lists"))
       activateItem(waitForObjectItem(":Workspace Symbol Lists_JMenu_2", "Futures"))
       clickButton(waitForObject(":Information.OK_FixedSizeButton"))
       
       mouseClick(waitForObject(":Close_TableHeaderItemProxy"), 26, 10, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_JTableHeader", "Notes"))
       type(waitForObject(":Note - AGILENT TECHNOLOGIES INC_JTextPane"), "aa")
       clickButton(waitForObject(":Note - AGILENT TECHNOLOGIES INC.OK_FixedSizeButton"))
       test.passes("Notes option working or not is pass")

       mouseClick(waitForObject(":Close_TableHeaderItemProxy"), 12, 10, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_JTableHeader", "Studies..."))
       mouseClick(waitForObjectItem(":Studies.com.futuresource.livecharts.common.LCList_LCList", "Ask Price Line"), 31, 4, 0, Button.Button1)
       clickButton(waitForObject(":Add Studies/Expression Shortcuts.Add_LCMultiButton"))
       test.compare(waitForObjectExists(":Market-Q (qa).ASK (A)_LCLabel").text, "ASK (A)")
       
       mouseClick(waitForObject(":Close_TableHeaderItemProxy"), 50, 0, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_JTableHeader", "Add/Remove Fields"))
       mouseClick(waitForObjectItem(":Add/Remove Fields.com.futuresource.livecharts.common.List2List$2_LCList", "Midpoint"), 23, 5, 0, Button.Button1)
       clickButton(waitForObject(":Add/Remove Fields.Add_FixedSizeButton"))
       mouseClick(waitForObjectItem(":Add/Remove Fields.com.futuresource.livecharts.common.List2List$5_LCList", "OpenInterest"), 52, 8, 0, Button.Button1)
       mouseClick(waitForObjectItem(":Add/Remove Fields.com.futuresource.livecharts.common.List2List$5_LCList", "Midpoint"), 50, 3, 0, Button.Button1)
       clickButton(waitForObject(":Add/Remove Fields.Remove_FixedSizeButton"))
       clickButton(waitForObject(":Add/Remove Fields.OK_FixedSizeButton"))
       test.passes("Add/Remove fields otpions is working or not is pass")
       
       mouseClick(waitForObject(":Close_TableHeaderItemProxy"), 34, 10, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_JTableHeader", "Sync Fields"))
       test.passes("Verify Sync Fields option is pass")

       mouseClick(waitForObject(":Close_TableHeaderItemProxy"), 48, 5, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_JTableHeader", "Reset Fields"))
       test.passes("Verify Reset Fields option is pass")
       
       mouseClick(waitForObject(":Close_TableHeaderItemProxy"), 31, 6, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_JTableHeader", "Header Display"))
       activateItem(waitForObjectItem(":Market-Q (qa).Header Display_JMenu", "Company Name"))
       test.compare(waitForObjectExists(":Market-Q (qa).AGILENT TECHNOLOGIES INC_LCLabel").text, "AGILENT TECHNOLOGIES INC")
       
       mouseClick(waitForObject(":Close_TableHeaderItemProxy"), 42, 4, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_JTableHeader", "Sort"))
       activateItem(waitForObjectItem(":Market-Q (qa).Sort_JMenu_2", "Sort Ascending by \"Time\""))
       test.passes("Verify Sort option is pass")
       
       mouseClick(waitForObject(":Market-Q (qa).AGILENT TECHNOLOGIES INC_LCLabel"), 392, 7, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa).AGILENT TECHNOLOGIES INC_LCLabel", "Conversion"))
       mouseClick(waitForObject(":Currency and Unit Conversion.com.futuresource.livecharts.common.dropdown.CurrencyDropDown_CurrencyDropDown"), 63, 0, 0, Button.Button1)
       mouseClick(waitForObject(":Currency and Unit Conversion_CommonButton"), 7, 6, 0, Button.Button1)
       mouseClick(waitForObjectItem(":Currency and Unit Conversion.ComboBox.list_JList", "USD"), 140, 6, 0, Button.Button1)
       mouseClick(waitForObject(":Currency and Unit Conversion_LCTextField"), 52, 8, 0, Button.Button1)
       mouseClick(waitForObject(":Currency and Unit Conversion_CommonButton_2"), 4, 5, 0, Button.Button1)
       mouseClick(waitForObjectItem(":Currency and Unit Conversion.ComboBox.list_JList", "DEFAULT"), 37, 0, 0, Button.Button1)
       clickButton(waitForObject(":Currency and Unit Conversion.OK_FixedSizeButton"))
       test.passes("Verify Conversion option for particular symbolis working or not is pass")
       


       mouseClick(waitForObject(":Close_TableHeaderItemProxy"), 68, 7, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_JTableHeader", "Time Template"))
       activateItem(waitForObjectItem(":Market-Q (qa).Time Template_JMenu", "Customize..."))
       clickButton(waitForObject(":Time Template_SmallButton"))
       mouseClick(waitForObject(":Time Template.Session 0:_LCCheckBox"), 3, 8, 0, Button.Button1)
       setValue(waitForObject(":Time Template.Start Time:_LCSpinner"), 1)
       setValue(waitForObject(":Time Template.End Time:_LCSpinner"), 1)
       setValue(waitForObject(":Time Template.End Time:_LCSpinner"), 2)
       mouseClick(waitForObject(":Time Template.Session 1:_LCCheckBox"), 6, 8, 0, Button.Button1)
       setValue(waitForObject(":Time Template_LCSpinner"), 1)
       setValue(waitForObject(":Time Template_LCSpinner"), 2)
       setValue(waitForObject(":Time Template.End Time:_LCSpinner_2"), 1)
       setValue(waitForObject(":Time Template.End Time:_LCSpinner_2"), 2)
       setValue(waitForObject(":Time Template_LCSpinner_2"), 3)
       clickButton(waitForObject(":Time Template.OK_FixedSizeButton"))
       test.passes("Verify Time Template and customization is pass")
       snooze(3)
       
       mouseClick(waitForObject(":Close_TableHeaderItemProxy"), 26, 11, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_JTableHeader", "Find..."))
       mouseClick(waitForObject(":Market-Q (qa).Find:_LCTextField"), 29, 4, 0, Button.Button1)
       type(waitForObject(":Market-Q (qa).Find:_LCTextField"), "Data")
       clickButton(waitForObject(":Market-Q (qa)_SmallButton"))
       test.passes("Verify Find.. option pass")
       
       mouseClick(waitForObject(":Close_TableHeaderItemProxy"), 43, 8, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_JTableHeader", "Copy to Clipboard"))
       mouseClick(waitForObject(":Copy Data Table To Clipboard.com.futuresource.livecharts.common.LCComboBox_LCComboBox"), 102, 5, 0, Button.Button1)
       mouseClick(waitForObjectItem(":Copy Data Table To Clipboard.ComboBox.list_JList", "Date Range"), 84, 8, 0, Button.Button1)
       clickButton(waitForObject(":Copy Data Table To Clipboard_LCAppendedButton"))
       clickButton(waitForObject(":Copy Data Table To Clipboard. > _SmallButton"))
       mouseClick(waitForObject(":Copy Data Table To Clipboard.15_JLabel"), 11, 4, 0, Button.Button1)
       clickButton(waitForObject(":Copy Data Table To Clipboard.OK_FixedSizeButton"))
       test.passes("Verify Copy to Clipboard option pass")
       
       mouseClick(waitForObject(":Close_TableHeaderItemProxy"), 52, 10, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_JTableHeader", "Export Data"))
       activateItem(waitForObjectItem(":Market-Q (qa).Export Data_JMenu", "Bar Data to Excel"))
       mouseClick(waitForObject(":Export Data File.Save In:_JButton"), 10, 6, 0, Button.Button1)
       mouseClick(waitForObjectItem(":Export Data File.ComboBox.list_JList", "Desktop"), 38, 12, 0, Button.Button1)
       mouseClick(waitForObject(":Export Data File.File Name:_JTextField"), 62, 7, 0, Button.Button1)
       type(waitForObject(":Export Data File.File Name:_JTextField"), "Excelmarketq")
       clickButton(waitForObject(":Export Data File.Save_JButton"))
       clickButton(waitForObject(":Information.OK_FixedSizeButton"))
       test.passes("Verify Export Data option pass")
       
       mouseClick(waitForObject(":Close_TableHeaderItemProxy"), 49, 8, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_JTableHeader", "Close A"))
       test.passes("Verify Close Symbol option is pass")
       mouseClick(waitForObject(":Market-Q (qa)_CommonButton_2"), 7, 3, 0, Button.Button1)
       mouseClick(waitForObjectItem(":Market-Q (qa).ComboBox.list_JList", "A"), 48, 1, 0, Button.Button1)
       type(waitForObject(":Market-Q (qa)_LCTextField"), "<Return>")
       snooze(3)
       mouseClick(waitForObject(":Market-Q (qa)_CommonButton_3"), 2, 7, 0, Button.Button1)
       mouseClick(waitForObjectItem(":Market-Q (qa).ComboBox.list_JList", "=ASK(A)"), 109, 6, 0, Button.Button1)
       type(waitForObject(":Market-Q (qa)_LCTextField"), "<Return>")
       snooze(3)
       mouseClick(waitForObject(":Market-Q (qa)_CommonButton_2"), 3, 3, 0, Button.Button1)
       mouseClick(waitForObjectItem(":Market-Q (qa).ComboBox.list_JList", "A"), 7, 8, 0, Button.Button1)
       type(waitForObject(":Market-Q (qa)_LCTextField"), "<Return>")
       snooze(5)
       
       #Bottom Options
       clickButton(waitForObject(":Market-Q (qa).Find..._FixedSizeButton"))
       test.passes("Verify Find option pass")
       
       clickButton(waitForObject(":Market-Q (qa).Print_FixedSizeButton"))
       clickButton(waitForObject(":Print Data Table.OK_FixedSizeButton"))
       clickButton(waitForObject(":Print.Cancel_JButton"))
       test.passes("Verify Print option pass")
       


       clickButton(waitForObject(":Market-Q (qa).Copy to Clipboard_FixedSizeButton"))
       mouseClick(waitForObject(":Copy Data Table To Clipboard_CommonButton"), 8, 5, 0, Button.Button1)
       mouseClick(waitForObjectItem(":Copy Data Table To Clipboard.ComboBox.list_JList", "Number Of Records"), 103, 4, 0, Button.Button1)
       mouseClick(waitForObject(":Copy Data Table To Clipboard.Spinner.formattedTextField_LCFormattedTextField"), 38, 5, 0, Button.Button1)
       type(waitForObject(":Copy Data Table To Clipboard.Spinner.formattedTextField_LCFormattedTextField"), "<Right>")
       type(waitForObject(":Copy Data Table To Clipboard.Spinner.formattedTextField_LCFormattedTextField"), "<Backspace>")
       type(waitForObject(":Copy Data Table To Clipboard.Spinner.formattedTextField_LCFormattedTextField"), "1")
       mouseClick(waitForObject(":Copy Data Table To Clipboard.com.futuresource.livecharts.common.LCPanel_LCPanel"), 111, 17, 0, Button.Button1)
       mouseClick(waitForObject(":Copy Data Table To Clipboard.Four Digit Years (If Default formatting)_LCCheckBox"), 6, 6, 0, Button.Button1)
       clickButton(waitForObject(":Copy Data Table To Clipboard.OK_FixedSizeButton"))
       test.passes("Verify Copy to Clipoboard pass")
       
       clickButton(waitForObject(":Market-Q (qa).Export to CSV_FixedSizeButton"))
       mouseClick(waitForObject(":Export Data File.Save In:_JButton"), 8, 5, 0, Button.Button1)
       mouseClick(waitForObjectItem(":Export Data File.ComboBox.list_JList", "Desktop"), 36, 9, 0, Button.Button1)
       mouseClick(waitForObject(":Export Data File.File Name:_JTextField"), 59, 5, 0, Button.Button1)
       type(waitForObject(":Export Data File.File Name:_JTextField"), "MArketQcsv")
       clickButton(waitForObject(":Export Data File.Save_JButton"))
       clickButton(waitForObject(":Information.OK_FixedSizeButton"))
       test.passes("Verify Expert to csv pass")
       
       #Display Properties
       mouseClick(waitForObject(":Market-Q (qa).Data Table_LCLabel"), 31, 11, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Display Properties"))
       mouseClick(waitForObject(":Data Table Display Properties_CommonButton"), 6, 5, 0, Button.Button1)
       mouseClick(waitForObjectItem(":Data Table Display Properties.ComboBox.list_JList", "Times New Roman"), 67, 9, 0, Button.Button1)
       mouseClick(waitForObject(":Data Table Display Properties.com.futuresource.livecharts.common.LCComboBox_LCComboBox"), 11, 10, 0, Button.Button1)
       mouseClick(waitForObjectItem(":Data Table Display Properties.ComboBox.list_JList", "12"), 11, 3, 0, Button.Button1)
       clickButton(waitForObject(":Data Table Display Properties.OK_FixedSizeButton"))
       test.passes("Verify Font options and its types pass")
       
       mouseClick(waitForObject(":Market-Q (qa)_JPanel_6"), 34, 0, 4, Button.Button3)
       mouseClick(waitForObject(":Market-Q (qa).Data Table_LCLabel"), 15, 7, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Display Properties"))
       mouseClick(waitForObject(":Data Table Display Properties.Bold_LCCheckBox"), 10, 7, 0, Button.Button1)
       mouseClick(waitForObject(":Data Table Display Properties.Italic_LCCheckBox"), 7, 7, 0, Button.Button1)
       clickButton(waitForObject(":Data Table Display Properties.OK_FixedSizeButton"))
       test.passes("Verify Bold & Italic options pass")
       
       mouseClick(waitForObject(":Market-Q (qa).Data Table_LCLabel"), 31, 7, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Display Properties"))
       clickButton(waitForObject(":Data Table Display Properties. _FixedSizeButton"))
       clickButton(waitForObject(":Data Table Display Properties_FixedSizeButton"))
       clickButton(waitForObject(":Data Table Display Properties.OK_FixedSizeButton"))
       test.passes("Verify Text color dropdown pass")
       
       mouseClick(waitForObject(":Market-Q (qa).Data Table_LCLabel"), 21, 6, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Display Properties"))
       clickButton(waitForObject(":Data Table Display Properties. _FixedSizeButton_2"))
       clickButton(waitForObject(":Data Table Display Properties_FixedSizeButton_2"))
       clickButton(waitForObject(":Data Table Display Properties. _FixedSizeButton_3"))
       clickButton(waitForObject(":Data Table Display Properties_FixedSizeButton_3"))
       clickButton(waitForObject(":Data Table Display Properties.OK_FixedSizeButton"))
       test.passes("Verify Background color1 & color2 Options pass")
       
       mouseClick(waitForObject(":Market-Q (qa).Data Table_LCLabel"), 34, 3, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Display Properties"))
       clickButton(waitForObject(":Data Table Display Properties. _FixedSizeButton_4"))
       clickButton(waitForObject(":Data Table Display Properties_FixedSizeButton_6"))
       clickButton(waitForObject(":Data Table Display Properties.OK_FixedSizeButton"))
       test.passes("Verify Section Background dropdown pass")
       
       mouseClick(waitForObject(":Market-Q (qa).Data Table_LCLabel"), 37, 6, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Display Properties"))
       clickButton(waitForObject(":Data Table Display Properties. _FixedSizeButton_5"))
       clickButton(waitForObject(":Data Table Display Properties_FixedSizeButton_7"))
       clickButton(waitForObject(":Data Table Display Properties.OK_FixedSizeButton"))
       test.passes("Verify Section Foreground dropdown pass")
       
       mouseClick(waitForObject(":Market-Q (qa).Data Table_LCLabel"), 43, 6, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Display Properties"))
       mouseClick(waitForObject(":Data Table Display Properties.Show Horizontal Gridlines_LCCheckBox"), 9, 10, 0, Button.Button1)
       clickButton(waitForObject(":Data Table Display Properties.OK_FixedSizeButton"))
       test.passes("Verify Show Horizontal Gridlines pass")
       
       mouseClick(waitForObject(":Market-Q (qa).Data Table_LCLabel"), 17, 5, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Display Properties"))
       mouseClick(waitForObject(":Data Table Display Properties.Show Vertical Gridlines_LCCheckBox"), 5, 7, 0, Button.Button1)
       clickButton(waitForObject(":Data Table Display Properties.OK_FixedSizeButton"))
       test.passes("Verify Show Vertical Gridlines pass")
       
       mouseClick(waitForObject(":Market-Q (qa).Data Table_LCLabel"), 37, 5, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Display Properties"))
       mouseClick(waitForObject(":Data Table Display Properties.Show Horizontal Gridlines_LCCheckBox"), 7, 6, 0, Button.Button1)
       mouseClick(waitForObject(":Data Table Display Properties.Show Vertical Gridlines_LCCheckBox"), 8, 4, 0, Button.Button1)
       clickButton(waitForObject(":Data Table Display Properties. _FixedSizeButton_6"))
       clickButton(waitForObject(":Data Table Display Properties_FixedSizeButton_8"))
       clickButton(waitForObject(":Data Table Display Properties.OK_FixedSizeButton"))
       test.passes("Verify Grid Color dropdown pass")
       
       mouseClick(waitForObject(":Market-Q (qa).Data Table_LCLabel"), 15, 1, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Display Properties"))
       mouseClick(waitForObjectItem(":Data Table Display Properties.com.futuresource.livecharts.common.LCCardList$1_LCList", "Conversion  "), 40, 8, 0, Button.Button1)
       mouseClick(waitForObject(":Data Table Display Properties.Use Global Settings_LCCheckBox"), 7, 6, 0, Button.Button1)
       clickButton(waitForObject(":Data Table Display Properties.OK_FixedSizeButton"))
       mouseClick(waitForObject(":Market-Q (qa).Data Table_LCLabel"), 56, 2, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Display Properties"))
       mouseClick(waitForObject(":Data Table Display Properties.Use Global Settings_LCCheckBox"), 5, 5, 0, Button.Button1)
       mouseClick(waitForObject(":Data Table Display Properties.Overwrite Individual Symbol Settings_LCCheckBox"), 2, 11, 0, Button.Button1)
       clickButton(waitForObject(":Data Table Display Properties.OK_FixedSizeButton"))
       test.passes("Verify checkboxes use global settings & overwrite individual symbol settings pass")

       mouseClick(waitForObject(":Market-Q (qa).Data Table_LCLabel"), 38, 0, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Display Properties"))
       mouseClick(waitForObject(":Data Table Display Properties.Use Global Settings_LCCheckBox"), 6, 4, 0, Button.Button1)
       mouseClick(waitForObject(":Data Table Display Properties_CommonButton_2"), 2, 9, 0, Button.Button1)
       mouseClick(waitForObjectItem(":Data Table Display Properties.ComboBox.list_JList", "USX"), 135, 10, 0, Button.Button1)
       clickButton(waitForObject(":Data Table Display Properties.OK_FixedSizeButton"))
       snooze(3)
       mouseClick(waitForObject(":Market-Q (qa).Data Table_LCLabel"), 40, 6, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Display Properties"))
       mouseClick(waitForObject(":Data Table Display Properties_CommonButton_2"), 4, 3, 0, Button.Button1)
       mouseClick(waitForObjectItem(":Data Table Display Properties.ComboBox.list_JList", "EUR"), 114, 7, 0, Button.Button1)
       clickButton(waitForObject(":Data Table Display Properties.OK_FixedSizeButton"))
       snooze(3)
       mouseClick(waitForObject(":Market-Q (qa).Data Table_LCLabel"), 41, 7, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Display Properties"))
       mouseClick(waitForObject(":Data Table Display Properties_CommonButton_2"), 7, 10, 0, Button.Button1)
       mouseClick(waitForObjectItem(":Data Table Display Properties.ComboBox.list_JList", "JPY"), 120, 7, 0, Button.Button1)
       clickButton(waitForObject(":Data Table Display Properties.OK_FixedSizeButton"))
       snooze(3)
       mouseClick(waitForObject(":Market-Q (qa).Data Table_LCLabel"), 26, 11, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Display Properties"))
       mouseClick(waitForObject(":Data Table Display Properties_CommonButton_2"), 4, 6, 0, Button.Button1)
       mouseClick(waitForObjectItem(":Data Table Display Properties.ComboBox.list_JList", "AUD"), 142, 8, 0, Button.Button1)
       clickButton(waitForObject(":Data Table Display Properties.OK_FixedSizeButton"))
       snooze(3)
       mouseClick(waitForObject(":Market-Q (qa).Data Table_LCLabel"), 48, 3, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Display Properties"))
       mouseClick(waitForObject(":Data Table Display Properties_CommonButton_2"), 2, 7, 0, Button.Button1)
       mouseClick(waitForObjectItem(":Data Table Display Properties.ComboBox.list_JList", "CNY"), 171, 9, 0, Button.Button1)
       clickButton(waitForObject(":Data Table Display Properties.OK_FixedSizeButton"))
       snooze(3)
       mouseClick(waitForObject(":Market-Q (qa).Data Table_LCLabel"), 46, 1, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Display Properties"))
       mouseClick(waitForObject(":Data Table Display Properties_CommonButton_2"), 1, 2, 0, Button.Button1)
       mouseClick(waitForObjectItem(":Data Table Display Properties.ComboBox.list_JList", "CAD"), 143, 2, 0, Button.Button1)
       clickButton(waitForObject(":Data Table Display Properties.OK_FixedSizeButton"))
       snooze(3)
       test.passes("Verify All options under currency dropdown pass")
       
       mouseClick(waitForObject(":Market-Q (qa).Data Table_LCLabel"), 18, 4, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Display Properties"))
       mouseClick(waitForObject(":Data Table Display Properties_CommonButton_3"), 8, 7, 0, Button.Button1)
       mouseClick(waitForObjectItem(":Data Table Display Properties.ComboBox.list_JList", "BALE"), 70, 6, 0, Button.Button1)
       mouseClick(waitForObject(":Data Table Display Properties_CommonButton_4"), 8, 4, 0, Button.Button1)
       mouseClick(waitForObjectItem(":Data Table Display Properties.ComboBox.list_JList", "PIG"), 74, 7, 0, Button.Button1)
       mouseClick(waitForObject(":Data Table Display Properties_CommonButton_5"), 8, 2, 0, Button.Button1)
       mouseClick(waitForObjectItem(":Data Table Display Properties.ComboBox.list_JList", "RA"), 65, 13, 0, Button.Button1)
       mouseClick(waitForObject(":Data Table Display Properties_CommonButton_6"), 5, 7, 0, Button.Button1)
       mouseClick(waitForObjectItem(":Data Table Display Properties.ComboBox.list_JList", "LB"), 104, 6, 0, Button.Button1)
       mouseClick(waitForObject(":Data Table Display Properties_CommonButton_7"), 11, 7, 0, Button.Button1)
       mouseClick(waitForObject(":Data Table Display Properties_CommonButton_7"), 8, 7, 0, Button.Button1)
       mouseClick(waitForObjectItem(":Data Table Display Properties.ComboBox.list_JList", "RIN"), 82, 9, 0, Button.Button1)
       mouseClick(waitForObject(":Data Table Display Properties_CommonButton_6"), 7, 7, 0, Button.Button1)
       mouseClick(waitForObjectItem(":Data Table Display Properties.ComboBox.list_JList", "MMLB"), 103, 3, 0, Button.Button1)
       mouseClick(waitForObject(":Data Table Display Properties_CommonButton_8"), 9, 8, 0, Button.Button1)
       mouseClick(waitForObjectItem(":Data Table Display Properties.ComboBox.list_JList", "DAY"), 87, 6, 0, Button.Button1)
       mouseClick(waitForObject(":Data Table Display Properties_CommonButton_5"), 1, 7, 0, Button.Button1)
       mouseClick(waitForObjectItem(":Data Table Display Properties.ComboBox.list_JList", "RA"), 63, 6, 0, Button.Button1)
       mouseClick(waitForObject(":Data Table Display Properties_CommonButton_9"), 3, 5, 0, Button.Button1)
       mouseClick(waitForObjectItem(":Data Table Display Properties.ComboBox.list_JList", "KM3"), 122, 2, 0, Button.Button1)
       mouseClick(waitForObject(":Data Table Display Properties_LCTextField"), 53, 6, 0, Button.Button1)
       mouseClick(waitForObject(":Data Table Display Properties_CommonButton_10"), 6, 7, 0, Button.Button1)
       mouseClick(waitForObjectItem(":Data Table Display Properties.ComboBox.list_JList", "SHAR"), 74, 5, 0, Button.Button1)
       mouseClick(waitForObject(":Data Table Display Properties_CommonButton_11"), 4, 9, 0, Button.Button1)
       mouseClick(waitForObjectItem(":Data Table Display Properties.ComboBox.list_JList", "IND"), 84, 4, 0, Button.Button1)
       mouseClick(waitForObject(":Data Table Display Properties_CommonButton_12"), 10, 1, 0, Button.Button1)
       mouseClick(waitForObjectItem(":Data Table Display Properties.ComboBox.list_JList", "CAL"), 97, 9, 0, Button.Button1)
       mouseClick(waitForObject(":Data Table Display Properties_CommonButton_13"), 6, 6, 0, Button.Button1)
       mouseClick(waitForObjectItem(":Data Table Display Properties.ComboBox.list_JList", "BPS"), 78, 9, 0, Button.Button1)
       clickButton(waitForObject(":Data Table Display Properties.OK_FixedSizeButton"))
       test.passes("Verify All options under Unit section pass")

       snooze(40)
