def Econoday():
    
       testSettings.logScreenshotOnFail = True
       testSettings.logScreenshotOnError = True


       clickButton(waitForObject(":Market-Q (qa)_JButton_4"))
       activateItem(waitForObjectItem(":Market-Q (qa)_JButton_4", "Econoday"))
       test.compare(waitForObjectExists(":Market-Q (qa).Econoday_LCLabel").text, "Econoday")
       snooze(3)

       clickLink(waitForObject(":Event Definitions_HTML_Object"))
       clickLink(waitForObject(":Today's Calendar_HTML_Object"))
       snooze(2)
       
       clickButton(waitForObject(":Market-Q (qa)_LCAppendedButton_7"))
       snooze(2)
       clickButton(waitForObject(":Market-Q (qa)_LCAppendedButton_7"))
       snooze(2)
       clickButton(waitForObject(":Market-Q (qa)_LCAppendedButton_7"))
       snooze(2)
       clickButton(waitForObject(":Market-Q (qa)_LCAppendedButton_6"))
       snooze(2)
       clickButton(waitForObject(":Market-Q (qa)_LCAppendedButton_6"))
       snooze(2)
       test.passes("Pass")
       mouseClick(waitForObject(":Market-Q (qa).Econoday_LCLabel"), 23, 6, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "New"))
       activateItem(waitForObjectItem(":Market-Q (qa).New_JMenu_5", "Watch List"))
       activateItem(waitForObjectItem(":Watch List_JMenu_4", "To the left"))
       mouseClick(waitForObject(":Market-Q (qa). _LCLabel"), 7, 5, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_JPanel_4", "Show Window Title"))
       test.compare(waitForObjectExists(":Market-Q (qa).Watch List_LCLabel").name, "Watch List")
       clickButton(waitForObject(":Market-Q (qa)_JButton_5"))
       test.passes("Pass")
       
       mouseClick(waitForObject(":Market-Q (qa).Econoday_LCLabel"), 16, 4, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Show Window Title"))
       mouseClick(waitForObject(":Market-Q (qa). _LCLabel_3"), 7, 4, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Show Window Title"))
       test.compare(waitForObjectExists(":Market-Q (qa).Econoday_LCLabel").text, "Econoday")
       test.passes("Pass")
       snooze(1)
       
       mouseClick(waitForObject(":Market-Q (qa).Econoday_LCLabel"), 7, 1, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Show Titlebar description"))
       test.compare(waitForObjectExists(":Market-Q (qa).Econoday_LCLabel_2").text, "Econoday")
       test.passes("Pass")
       
       mouseClick(waitForObject(":Market-Q (qa).Econoday_LCLabel_2"), 18, 11, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Customize Titlebar Description..."))
       mouseClick(waitForObject(":Titlebar Description Settings.Econoday_LCTextArea"), 101, 17, 0, Button.Button1)
       type(waitForObject(":Titlebar Description Settings.Econoday_LCTextArea"), " Test")
       mouseClick(waitForObject(":Titlebar Description Settings.Foreground: _LCCheckBox"), 6, 15, 0, Button.Button1)
       clickButton(waitForObject(":Titlebar Description Settings. _FixedSizeButton"))
       clickButton(waitForObject(":Titlebar Description Settings_FixedSizeButton"))
       mouseClick(waitForObject(":Titlebar Description Settings.Background: _LCCheckBox"), 1, 7, 0, Button.Button1)
       clickButton(waitForObject(":Titlebar Description Settings. _FixedSizeButton_2"))
       clickButton(waitForObject(":Titlebar Description Settings_FixedSizeButton_2"))
       mouseClick(waitForObject(":Titlebar Description Settings.Font: _LCCheckBox"), 11, 9, 0, Button.Button1)
       mouseClick(waitForObject(":Titlebar Description Settings_CommonButton"), 5, 5, 0, Button.Button1)
       mouseClick(waitForObjectItem(":Titlebar Description Settings.ComboBox.list_JList", "Times New Roman"), 71, 1, 0, Button.Button1)
       mouseClick(waitForObject(":Titlebar Description Settings.com.futuresource.livecharts.common.LCComboBox_LCComboBox"), 20, 12, 0, Button.Button1)
       mouseClick(waitForObjectItem(":Titlebar Description Settings.ComboBox.list_JList", "13"), 17, 15, 0, Button.Button1)
       mouseClick(waitForObject(":Titlebar Description Settings.Bold_LCCheckBox"), 8, 5, 0, Button.Button1)
       mouseClick(waitForObject(":Titlebar Description Settings.Bold_LCCheckBox"), 50, 6, 0, Button.Button1)
       mouseClick(waitForObject(":Titlebar Description Settings.Bold_LCCheckBox"), 8, 9, 0, Button.Button1)
       mouseClick(waitForObject(":Titlebar Description Settings.Italic_LCCheckBox"), 9, 7, 0, Button.Button1)
       clickButton(waitForObject(":Titlebar Description Settings.OK_FixedSizeButton"))
       test.passes("Pass")
       
       mouseClick(waitForObject(":Market-Q (qa).Econoday Test_LCLabel"), 14, 5, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Copy Out"))
       test.compare(waitForObjectExists(":Econoday.Econoday Test_LCLabel").text, "Econoday Test")
       
       mouseClick(waitForObject(":Econoday.Econoday Test_LCLabel"), 13, 8, 4, Button.Button3)
       mouseClick(waitForObject(":Econoday.Econoday Test_LCLabel"), 1287, 0, 0, Button.Button1)
       clickButton(waitForObject(":Econoday_JButton"))
       
       mouseClick(waitForObject(":Market-Q (qa).Econoday Test_LCLabel"), 14, 5, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Cut Window"))
       mouseClick(waitForObject(":Market-Q (qa).Empty Window_LCLabel"), 22, 11, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Paste Econoday"))
       activateItem(waitForObjectItem(":Market-Q (qa).Paste Econoday_JMenu", "In this window"))
       test.passes("Pass")
       
       mouseClick(waitForObject(":Market-Q (qa).Econoday Test_LCLabel"), 18, 7, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Copy Window"))
       mouseClick(waitForObject(":Market-Q (qa).Econoday Test_LCLabel"), 29, 2, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Paste Econoday"))
       activateItem(waitForObjectItem(":Market-Q (qa).Paste Econoday_JMenu", "To the left"))
       test.compare(waitForObjectExists(":Market-Q (qa).Econoday Test_LCLabel").text, "Econoday Test")
       
       mouseClick(waitForObject(":Market-Q (qa).Econoday Test_LCLabel"), 604, 14, 0, Button.Button1)
       clickButton(waitForObject(":Market-Q (qa)_JButton_5"))
       mouseClick(waitForObject(":Market-Q (qa).Econoday Test_LCLabel"), 6, 10, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Take Custom Screenshot"))
       dragItemBy(waitForObject(":Market-Q (qa).Web Browser_BrowserPad"), 6, 3, 1280, 286, Modifier.None, Button.Button1)
       
       mouseClick(waitForObject(":Market-Q (qa).Econoday Test_LCLabel"), 23, 3, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Print"))
       
       mouseClick(waitForObject(":Market-Q (qa).Econoday Test_LCLabel"), 13, 15, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Empty"))
       
       clickButton(waitForObject(":Market-Q (qa)_JButton_4"))
       activateItem(waitForObjectItem(":Market-Q (qa)_JButton_4", "Econoday"))
       mouseClick(waitForObject(":Market-Q (qa)_JPanel_10"), 15, 0, 4, Button.Button3)
       mouseClick(waitForObject(":Market-Q (qa).Econoday_LCLabel"), 20, 8, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Close"))
       
       clickButton(waitForObject(":Market-Q (qa)_JButton_4"))
       activateItem(waitForObjectItem(":Market-Q (qa)_JButton_4", "Econoday"))
       snooze(2)
       clickLink(waitForObject(":Event Definitions_HTML_Object"))
       test.compare(waitForObjectExists(":Event Definitions_HTML_Object").innerText, "Event Definitions")
       snooze(2)
       clickLink(waitForObject(":Today's Calendar_HTML_Object"))
       test.compare(waitForObjectExists(":Today's Calendar_HTML_Object").innerText, "Today's Calendar")
       snooze(2)
       clickLink(waitForObject(":Monthly_HTML_Object"))
       test.compare(waitForObjectExists(":Monthly_HTML_Object_2").innerText, "Monthly")
       snooze(2)
       clickLink(waitForObject(":Weekly_HTML_Object"))
       test.compare(waitForObjectExists(":Weekly_HTML_Object_2").innerText, "Weekly")
       snooze(2)
       clickLink(waitForObject(":Daily_HTML_Object"))
       test.compare(waitForObjectExists(":Daily_HTML_Object_2").innerText, "Daily")
       snooze(2)
       clickLink(waitForObject(":Today_HTML_Object"))
       test.compare(waitForObjectExists(":Tuesday August 6, 2019_HTML_Object").innerText, "Tuesday August 6,  2019")
       snooze(2)
       clickLink(waitForObject(":Change Timezone_HTML_Object"))
       selectOption(waitForObject(":timezoneoffset_select-one"), "(GMT -8:00) Pacific Time (US & Canada)")
       mouseClick(waitForObject(":_request_submit"))


       snooze(40)
