def Forex():
    
    testSettings.logScreenshotOnFail = True
    testSettings.logScreenshotOnError = True


    clickButton(waitForObject(":Market-Q (qa)_JButton_4"))
    activateItem(waitForObjectItem(":Market-Q (qa)_JButton_4", "Forex"))
    test.compare(waitForObjectExists(":Market-Q (qa).Forex_LCLabel").name, "Forex")
    
    clickButton(waitForObject(":Market-Q (qa)_SmallButton_5"))
    clickButton(waitForObject(":Symbol Lookup.Search_FixedSizeButton"))
    test.compare(waitForObjectExists(":com.futuresource.livecharts.dialogs.symbollookup.SymbolLookupDialog$SymbolsTable.USD A0-FX_TableItemProxy").text, "USD A0-FX")
    dragItemBy(waitForObject(":Symbol Lookup_LCTitlePane"), 96, 14, -416, -482, Modifier.None, Button.Button1)
    clickButton(waitForObject(":Symbol Lookup.OK_FixedSizeButton"))
    snooze(2)
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/1"), 104, 50, 0, Button.Button1)
    doubleClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/1"), 104, 50, 0, Button.Button1)
    type(waitForObject(":Market-Q (qa)_LCTextField_24"), "inr a0-fx")
    type(waitForObject(":Market-Q (qa)_LCTextField_24"), "<Return>")
    
    mouseClick(waitForObject(":Market-Q (qa).Forex_LCLabel"), 16, 4, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "New"))
    activateItem(waitForObjectItem(":Market-Q (qa).New_JMenu_8", "Watch List"))
    activateItem(waitForObjectItem(":Watch List_JMenu_5", "To the left"))
    mouseClick(waitForObject(":Market-Q (qa). _LCLabel"), 9, 8, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa)_JPanel_4", "Show Window Title"))
    test.compare(waitForObjectExists(":Market-Q (qa).Watch List_LCLabel").text, "Watch List")
    clickButton(waitForObject(":Market-Q (qa)_JButton_5"))
    test.passes("Pass")
    snooze(1)
    
    mouseClick(waitForObject(":Market-Q (qa).Forex_LCLabel"), 13, 2, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Show Window Title"))
    mouseClick(waitForObject(":Market-Q (qa). _LCLabel_6"), 10, 7, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Show Window Title"))
    test.compare(waitForObjectExists(":Market-Q (qa).Forex_LCLabel").text, "Forex")
    snooze(1)
    
    mouseClick(waitForObject(":Market-Q (qa).Forex_LCLabel"), 6, 7, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Show Titlebar description"))
    test.compare(waitForObjectExists(":Market-Q (qa).Forex_LCLabel_2").text, "Forex")
    snooze(1)
    
    mouseClick(waitForObject(":Market-Q (qa).Forex_LCLabel_2"), 11, 15, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Customize Titlebar Description..."))
    type(waitForObject(":Titlebar Description Settings.Forex_LCTextArea"), "Test ")
    mouseClick(waitForObject(":Titlebar Description Settings.Foreground: _LCCheckBox"), 14, 11, 0, Button.Button1)
    clickButton(waitForObject(":Titlebar Description Settings. _FixedSizeButton"))
    clickButton(waitForObject(":Titlebar Description Settings_FixedSizeButton_2"))
    mouseClick(waitForObject(":Titlebar Description Settings.Background: _LCCheckBox"), 7, 13, 0, Button.Button1)
    clickButton(waitForObject(":Titlebar Description Settings. _FixedSizeButton_2"))
    clickButton(waitForObject(":Titlebar Description Settings_FixedSizeButton"))
    mouseClick(waitForObject(":Titlebar Description Settings.Font: _LCCheckBox"), 14, 6, 0, Button.Button1)
    mouseClick(waitForObject(":Titlebar Description Settings_CommonButton"), 9, 12, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Titlebar Description Settings.ComboBox.list_JList", "Times New Roman"), 73, 10, 0, Button.Button1)
    mouseClick(waitForObject(":Titlebar Description Settings_CommonButton_2"), 7, 5, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Titlebar Description Settings.ComboBox.list_JList", "13"), 18, 1, 0, Button.Button1)
    mouseClick(waitForObject(":Titlebar Description Settings.Bold_LCCheckBox"), 10, 9, 0, Button.Button1)
    mouseClick(waitForObject(":Titlebar Description Settings.Italic_LCCheckBox"), 6, 11, 0, Button.Button1)
    clickButton(waitForObject(":Titlebar Description Settings.OK_FixedSizeButton"))
    test.passes("Pass")
    snooze(1)
    
    mouseClick(waitForObject(":Market-Q (qa).Test Forex_LCLabel"), 10, 12, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Customize Titlebar Description..."))
    clickButton(waitForObject(":Titlebar Description Settings.OK_FixedSizeButton"))
    
    mouseClick(waitForObject(":Market-Q (qa).Test Forex_LCLabel"), 16, 8, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Copy Out"))
    test.compare(waitForObjectExists(":Forex.Test Forex_LCLabel").text, "Test Forex")
    mouseClick(waitForObject(":Forex.Test Forex_LCLabel"), 1145, 8, 0, Button.Button1)
    clickButton(waitForObject(":Forex_JButton"))
    snooze(1)
    
    mouseClick(waitForObject(":Market-Q (qa).Test Forex_LCLabel"), 21, 9, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Cut Window"))
    mouseClick(waitForObject(":Market-Q (qa).Empty Window_LCLabel"), 36, 0, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Paste Forex"))
    activateItem(waitForObjectItem(":Market-Q (qa).Paste Forex_JMenu", "In this window"))
    test.compare(waitForObjectExists(":Market-Q (qa).Test Forex_LCLabel").text, "Test Forex")
    snooze(1)
    
    mouseClick(waitForObject(":Market-Q (qa).Test Forex_LCLabel"), 16, 14, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Copy Window"))
    mouseClick(waitForObject(":Market-Q (qa).Test Forex_LCLabel"), 12, 2, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Paste Forex"))
    activateItem(waitForObjectItem(":Market-Q (qa).Paste Forex_JMenu", "To the left"))
    test.compare(waitForObjectExists(":Market-Q (qa).Test Forex_LCLabel").text, "Test Forex")
    mouseClick(waitForObject(":Market-Q (qa).Test Forex_LCLabel"), 556, 10, 0, Button.Button1)
    clickButton(waitForObject(":Market-Q (qa)_JButton_5"))
    
    mouseClick(waitForObject(":Market-Q (qa).Test Forex_LCLabel"), 21, 8, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Copy Window Image"))
    mouseClick(waitForObject(":Market-Q (qa).Test Forex_LCLabel"), 13, 10, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Paste Forex"))
    activateItem(waitForObjectItem(":Market-Q (qa).Paste Forex_JMenu", "To the left"))
    test.compare(waitForObjectExists(":Market-Q (qa).Test Forex_LCLabel").text, "Test Forex")
    mouseClick(waitForObject(":Market-Q (qa).Test Forex_LCLabel"), 573, 19, 0, Button.Button1)
    clickButton(waitForObject(":Market-Q (qa)_JButton_5"))
    snooze(1)
    
    mouseClick(waitForObject(":Market-Q (qa).Test Forex_LCLabel"), 6, 11, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Send Image by E-mail..."))
    test.passes("Pass")
    snooze(1)
    
    mouseClick(waitForObject(":Market-Q (qa).Test Forex_LCLabel"), 19, 8, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Take Custom Screenshot"))
    test.passes("Pass")
    snooze(1)
    
    mouseDrag(waitForObject(":Market-Q (qa).Test Forex_LCLabel"), 1, 0, 1334, 560, Modifier.None, Button.Button1)
    mouseClick(waitForObject(":Market-Q (qa).Test Forex_LCLabel"), 11, 2, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Print"))
    clickButton(waitForObject(":Print Forex.OK_FixedSizeButton"))
    clickButton(waitForObject(":Print.Cancel_JButton"))
    test.passes("Pass")
    snooze(1)
    
    mouseClick(waitForObject(":Market-Q (qa).Test Forex_LCLabel"), 11, 13, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Display Properties"))
    test.compare(waitForObjectExists(":com.futuresource.livecharts.common.LCCardList$1.Text & Colors  _ListItemProxy_6").text, "Text & Colors")
    clickButton(waitForObject(":Forex Display Properties.OK_FixedSizeButton"))
    snooze(1)
    
    mouseClick(waitForObject(":Market-Q (qa).Test Forex_LCLabel"), 8, 3, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Empty"))
    snooze(1)
    
    clickButton(waitForObject(":Market-Q (qa)_JButton_4"))
    activateItem(waitForObjectItem(":Market-Q (qa)_JButton_4", "Forex"))
    
    mouseClick(waitForObject(":Market-Q (qa).Forex_LCLabel"), 11, 4, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Close"))
    test.passes("Pass")
    snooze(1)
    
    clickButton(waitForObject(":Market-Q (qa)_JButton_4"))
    activateItem(waitForObjectItem(":Market-Q (qa)_JButton_4", "Forex"))
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 83, 52, 0, Button.Button1)
    doubleClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 83, 52, 0, Button.Button1)
    type(waitForObject(":Market-Q (qa)_LCTextField_24"), "inr a0-fx")
    type(waitForObject(":Market-Q (qa)_LCTextField_24"), "<Return>")
    snooze(1)
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/1"), 78, 65, 0, Button.Button1)
    doubleClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/1"), 78, 65, 0, Button.Button1)
    type(waitForObject(":Market-Q (qa)_LCTextField_24"), "gbp a0-fx")
    type(waitForObject(":Market-Q (qa)_LCTextField_24"), "<Return>")
    snooze(1)
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/2"), 83, 52, 0, Button.Button1)
    doubleClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/2"), 83, 52, 0, Button.Button1)
    type(waitForObject(":Market-Q (qa)_LCTextField_24"), "usd a0-fx")
    type(waitForObject(":Market-Q (qa)_LCTextField_24"), "<Return>")
    snooze(1)
    
#     mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 43, 21, 4, Button.Button3)
#     activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "View"))
#     snooze(1)
#     activateItem(waitForObjectItem(":Market-Q (qa).View_JMenu_5", "Chart"))
#     test.compare(waitForObjectExists(":Market-Q (qa).Chart_LCLabel").text, "Chart")
#     clickButton(waitForObject(":Market-Q (qa)_JButton_7"))
#     snooze(1)
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 60, 14, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "Add To Symbol list"))
    activateItem(waitForObjectItem(":Market-Q (qa).Add To Symbol list_JMenu_6", "Workspace Symbol Lists"))
    activateItem(waitForObjectItem(":Workspace Symbol Lists_JMenu_6", "EIA - Stocks"))
    clickButton(waitForObject(":Information.OK_FixedSizeButton"))
    clickButton(waitForObject(":Market-Q (qa).Watch List_MonsoonNewPadButton"))
    clickButton(waitForObject(":Market-Q (qa).Symbol List_LCTreeButton"))
    mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Workspace Symbol Lists.EIA - Stocks"), 49, 7, 0, Button.Button1)
    test.compare(waitForObjectExists(":com.futuresource.livecharts.newquotes.QuotePad$2.29_0_TableItemProxy").text, "INR A0-FX")
    snooze(1)
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 95, 15, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "Add To Symbol list"))
    activateItem(waitForObjectItem(":Market-Q (qa).Add To Symbol list_JMenu_6", "Mobile Home Page (Phone Only)"))
    activateItem(waitForObjectItem(":Mobile Home Page (Phone Only)_JMenu_5", "Futures"))
    clickButton(waitForObject(":Information.OK_FixedSizeButton"))
    clickButton(waitForObject(":Market-Q (qa).EIA - Stocks_LCTreeButton"))
    mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Mobile Home Page (Phone Only).Futures"), 32, 7, 0, Button.Button1)
    test.compare(waitForObjectExists(":com.futuresource.livecharts.newquotes.QuotePad$2.13_0_TableItemProxy").text, "INR A0-FX")
    snooze(1)
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 88, 15, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "Add To Symbol list"))
    activateItem(waitForObjectItem(":Market-Q (qa).Add To Symbol list_JMenu_6", "Shared Symbol Lists"))
    activateItem(waitForObjectItem(":Shared Symbol Lists_JMenu_3", "tEST List 2"))
    clickButton(waitForObject(":Information.OK_FixedSizeButton"))
    clickButton(waitForObject(":Market-Q (qa).Futures_LCTreeButton"))
    mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Shared Symbol Lists.tEST List 2"), 70, 7, 0, Button.Button1)
    test.compare(waitForObjectExists(":com.futuresource.livecharts.newquotes.QuotePad$2.13_0_TableItemProxy").text, "INR A0-FX")
    clickButton(waitForObject(":Market-Q (qa)_JButton_7"))
    snooze(1)
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 62, 9, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "Alerts"))
    activateItem(waitForObjectItem(":Market-Q (qa).Alerts_JMenu_3", "Add Quote Alert"))
    type(waitForObject(":Add Quote Alert_LCTextField_3"), "73")
    mouseClick(waitForObject(":Add Quote Alert_LCTextArea"), 59, 32, 0, Button.Button1)
    type(waitForObject(":Add Quote Alert_LCTextArea"), "test quote")
    clickButton(waitForObject(":Add Quote Alert.OK_FixedSizeButton"))
    test.passes("Pass")
    snooze(1)
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 63, 11, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "Alerts"))
    activateItem(waitForObjectItem(":Market-Q (qa).Alerts_JMenu_3", "Add News Alert"))
    mouseClick(waitForObject(":Add News Alert_LCTextArea"), 132, 41, 0, Button.Button1)
    type(waitForObject(":Add News Alert_LCTextArea"), "test news")
    clickButton(waitForObject(":Add News Alert.OK_FixedSizeButton"))
    test.passes("Pass")
    snooze(1)
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 66, 13, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "Alerts"))
    activateItem(waitForObjectItem(":Market-Q (qa).Alerts_JMenu_3", "Triggered Alerts"))
    clickButton(waitForObject(":Alert Log.Workspace_LCDropDownButton"))
    activateItem(waitForObjectItem(":Alert Log.Workspace_LCDropDownButton", "Workspace"))
    clickButton(waitForObject(":Alert Log.Quote Alerts_LCDropDownButton"))
    activateItem(waitForObjectItem(":Alert Log.Quote Alerts_LCDropDownButton", "News Alerts"))
    clickButton(waitForObject(":Alert Log.News Alerts_LCDropDownButton"))
    activateItem(waitForObjectItem(":Alert Log.News Alerts_LCDropDownButton", "Condition Alerts"))
    clickButton(waitForObject(":Alert Log.Condition Alerts_LCDropDownButton"))
    activateItem(waitForObjectItem(":Alert Log.Condition Alerts_LCDropDownButton", "Time Alerts"))
    clickButton(waitForObject(":Alert Log.Export to CSV_FixedSizeButton"))
    type(waitForObject(":Save.File Name:_JTextField"), "forex")
    clickButton(waitForObject(":Save.Save_JButton"))
    mouseClick(waitForObject(":Information.com.futuresource.livecharts.dialogs.DialogButtonPanel_DialogButtonPanel"), 148, 30, 0, Button.Button1)
    clickButton(waitForObject(":Information.OK_FixedSizeButton"))
    clickButton(waitForObject(":Alert Log.Print_FixedSizeButton"))
    clickButton(waitForObject(":Print Alert Log.OK_FixedSizeButton"))
    clickButton(waitForObject(":Print.Cancel_JButton"))
    clickButton(waitForObject(":Alert Log.Clear_FixedSizeButton"))
    snooze(1)
    clickButton(waitForObject(":Alert Log.Close_FixedSizeButton"))
    test.passes("Pass")
    snooze(1)
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 68, 17, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "Alerts"))
    activateItem(waitForObjectItem(":Market-Q (qa).Alerts_JMenu_3", "__Alerts"))
    clickTab(waitForObject(":Market-Q (qa).News Alerts_TabProxy"))
    clickTab(waitForObject(":Market-Q (qa).Condition Alerts_TabProxy"))
    clickTab(waitForObject(":Market-Q (qa).Time Alerts_TabProxy"))
    test.compare(waitForObjectExists(":Market-Q (qa).Alerts_LCLabel").name, "Alerts")
    clickButton(waitForObject(":Market-Q (qa)_JButton_7"))
    test.passes("Pass")
    snooze(1)

    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 95, 20, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "Notes"))
    type(waitForObject(":Note - INDIAN RUPEE/US DOLLAR_JTextPane"), "forex notes")
    mouseClick(waitForObject(":Note - INDIAN RUPEE/US DOLLAR_LCToggleButton"), 7, 8, 0, Button.Button1)
    mouseClick(waitForObject(":Note - INDIAN RUPEE/US DOLLAR_LCToggleButton_2"), 6, 9, 0, Button.Button1)
    mouseClick(waitForObject(":Note - INDIAN RUPEE/US DOLLAR_LCToggleButton_3"), 8, 6, 0, Button.Button1)
    clickButton(waitForObject(":Note - INDIAN RUPEE/US DOLLAR. _FixedSizeButton"))
    clickButton(waitForObject(":Note - INDIAN RUPEE/US DOLLAR_FixedSizeButton_2"))
    clickButton(waitForObject(":Note - INDIAN RUPEE/US DOLLAR.OK_FixedSizeButton"))
    test.passes("Pass")
    snooze(1)
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 79, 18, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "Add New Symbol"))
    type(waitForObject(":Market-Q (qa)_LCTextField_24"), "cad a0-fx")
    type(waitForObject(":Market-Q (qa)_LCTextField_24"), "<Return>")
    snooze(1)
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/4"), 81, 59, 0, Button.Button1)
    doubleClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/4"), 81, 59, 0, Button.Button1)
    type(waitForObject(":Market-Q (qa)_LCTextField_24"), "aud a0-fx")
    type(waitForObject(":Market-Q (qa)_LCTextField_24"), "<Return>")
    snooze(1)
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 39, 18, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "Delete"))
    activateItem(waitForObjectItem(":Market-Q (qa).Delete_JMenu_3", "Selected Symbol(s)"))
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 67, 14, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "Delete"))
    activateItem(waitForObjectItem(":Market-Q (qa).Delete_JMenu_3", "All Symbols"))
    clickButton(waitForObject(":Question.Yes_FixedSizeButton"))
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 55, 53, 0, Button.Button1)
    doubleClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 55, 53, 0, Button.Button1)
    type(waitForObject(":Market-Q (qa)_LCTextField_24"), "inr a0-fx")
    type(waitForObject(":Market-Q (qa)_LCTextField_24"), "<Return>")
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/1"), 47, 45, 0, Button.Button1)
    doubleClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/1"), 47, 45, 0, Button.Button1)
    type(waitForObject(":Market-Q (qa)_LCTextField_24"), "gbp a0-fx")
    type(waitForObject(":Market-Q (qa)_LCTextField_24"), "<Return>")
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 46, 17, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "Edit"))
    activateItem(waitForObjectItem(":Market-Q (qa).Edit_JMenu_3", "Edit Selected Symbol"))
    type(waitForObject(":Market-Q (qa)_LCTextField_24"), "cad a0-fx")
    type(waitForObject(":Market-Q (qa)_LCTextField_24"), "<Return>")
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 83, 10, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "Edit"))
    activateItem(waitForObjectItem(":Market-Q (qa).Edit_JMenu_3", "Cut Selected Symbol(s)"))
    snooze(1)
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/1"), 38, 53, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "Edit"))
    activateItem(waitForObjectItem(":Market-Q (qa).Edit_JMenu_3", "Paste Symbols"))
    snooze(1)
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/1"), 105, 20, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "Edit"))
    activateItem(waitForObjectItem(":Market-Q (qa).Edit_JMenu_3", "Copy Selected Symbol(s)"))
    snooze(1)
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/2"), 55, 57, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "Edit"))
    activateItem(waitForObjectItem(":Market-Q (qa).Edit_JMenu_3", "Paste Symbols"))
    snooze(1)
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/2"), 57, 19, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "Select All"))
    snooze(1)
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/2"), 42, 13, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "Clear Selection"))
    test.passes("Pass")
    snooze(1)
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/2"), 45, 27, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "Show New Cell"))
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/2"), 78, 22, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "Show New Cell"))
    test.passes("Pass")
    snooze(1)
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/2"), 90, 13, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "Show Changed Indicator"))
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/2"), 83, 13, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "Show Changed Indicator"))
    test.passes("Pass")
    snooze(1)
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/2"), 88, 10, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "Show Alert Indicator"))
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/2"), 95, 11, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "Show Alert Indicator"))
    test.passes("Pass")
    snooze(1)
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/3"), 89, 51, 0, Button.Button1)
    doubleClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/3"), 89, 51, 0, Button.Button1)
    type(waitForObject(":Market-Q (qa)_LCTextField_24"), "inr a0-fx")
    type(waitForObject(":Market-Q (qa)_LCTextField_24"), "<Return>")
    snooze(1)
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/3"), 67, 20, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "Insert Symbols from file..."))
    mouseClick(waitForObject(":Open.Look In:_JButton"), 8, 5, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Open.ComboBox.list_JList", "Desktop"), 46, 4, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Open_JList", "forex symbols.txt"), 63, 11, 0, Button.Button1)
    clickButton(waitForObject(":Open.Open_JButton"))
    test.passes("Pass")
    snooze(1)
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 55, 15, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "Print"))
    clickButton(waitForObject(":Print Forex.OK_FixedSizeButton"))
    clickButton(waitForObject(":Print.Cancel_JButton"))
    test.passes("Pass")
    snooze(1)
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 47, 12, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "Defaults"))
    activateItem(waitForObjectItem(":Market-Q (qa).Defaults_JMenu_8", "Save Forex Properties As Default"))
    clickButton(waitForObject(":Information.OK_FixedSizeButton"))
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 79, 14, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "Display Properties..."))
    mouseClick(waitForObject(":Forex Display Properties_CommonButton"), 6, 9, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Forex Display Properties.ComboBox.list_JList", "17"), 22, 5, 0, Button.Button1)
    mouseClick(waitForObject(":Forex Display Properties.Bold_LCCheckBox"), 8, 17, 0, Button.Button1)
    clickButton(waitForObject(":Forex Display Properties.OK_FixedSizeButton"))
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 118, 25, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "Defaults"))
    activateItem(waitForObjectItem(":Market-Q (qa).Defaults_JMenu_8", "Save Forex Properties As Default"))
    clickButton(waitForObject(":Question.Yes_FixedSizeButton"))
    clickButton(waitForObject(":Information.OK_FixedSizeButton"))
    test.passes("Pass")
    snooze(1)
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 82, 21, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "Defaults"))
    activateItem(waitForObjectItem(":Market-Q (qa).Defaults_JMenu_8", "Apply Default Properties to the Forex"))
    clickButton(waitForObject(":Market-Q (qa)_JButton_5"))
    test.passes("Pass")
    snooze(1)
    
    clickButton(waitForObject(":Market-Q (qa)_JButton_4"))
    activateItem(waitForObjectItem(":Market-Q (qa)_JButton_4", "Forex"))
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 102, 70, 0, Button.Button1)
    doubleClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 102, 70, 0, Button.Button1)
    type(waitForObject(":Market-Q (qa)_LCTextField_24"), "inr a0-fx")
    type(waitForObject(":Market-Q (qa)_LCTextField_24"), "<Return>")
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 144, 10, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "Defaults"))
    activateItem(waitForObjectItem(":Market-Q (qa).Defaults_JMenu_8", "Apply Default Properties to all Forex Windows"))
    clickButton(waitForObject(":Market-Q (qa)_JButton_5"))
    test.passes("Pass")
    snooze(1)
    
    clickButton(waitForObject(":Market-Q (qa)_JButton_4"))
    activateItem(waitForObjectItem(":Market-Q (qa)_JButton_4", "Forex"))
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 79, 59, 0, Button.Button1)
    doubleClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 79, 59, 0, Button.Button1)
    type(waitForObject(":Market-Q (qa)_LCTextField_24"), "inr a0-fx")
    type(waitForObject(":Market-Q (qa)_LCTextField_24"), "<Return>")
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 92, 19, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "Defaults"))
    activateItem(waitForObjectItem(":Market-Q (qa).Defaults_JMenu_8", "Remove Default Forex Properties"))
    clickButton(waitForObject(":Question.Yes_FixedSizeButton"))
    clickButton(waitForObject(":Information.OK_FixedSizeButton"))
    clickButton(waitForObject(":Market-Q (qa)_JButton_5"))
    test.passes("Pass")
    snooze(2)
    
    clickButton(waitForObject(":Market-Q (qa)_JButton_4"))
    activateItem(waitForObjectItem(":Market-Q (qa)_JButton_4", "Forex"))
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 123, 47, 0, Button.Button1)
    doubleClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 123, 47, 0, Button.Button1)
    type(waitForObject(":Market-Q (qa)_LCTextField_24"), "inr a0-fx")
    type(waitForObject(":Market-Q (qa)_LCTextField_24"), "<Return>")
    snooze(1)
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 75, 13, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "Display Properties..."))
    mouseClick(waitForObject(":Forex Display Properties_CommonButton_2"), 8, 4, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Forex Display Properties.ComboBox.list_JList", "Times New Roman"), 28, 5, 0, Button.Button1)
    mouseClick(waitForObject(":Forex Display Properties_CommonButton"), 1, 7, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Forex Display Properties.ComboBox.list_JList", "13"), 19, 5, 0, Button.Button1)
    mouseClick(waitForObject(":Forex Display Properties.Bold_LCCheckBox"), 12, 8, 0, Button.Button1)
    mouseClick(waitForObject(":Forex Display Properties.Italic_LCCheckBox"), 3, 10, 0, Button.Button1)
    clickButton(waitForObject(":Forex Display Properties.OK_FixedSizeButton"))
    test.passes("Pass")
    snooze(2)
    
    mouseClick(waitForObject(":Market-Q (qa)_JPanel"), 394, 6, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Display Properties"))
    clickButton(waitForObject(":Forex Display Properties. _FixedSizeButton"))
    clickButton(waitForObject(":Forex Display Properties_FixedSizeButton"))
    clickButton(waitForObject(":Forex Display Properties. _FixedSizeButton_2"))
    clickButton(waitForObject(":Forex Display Properties_FixedSizeButton_2"))
    clickButton(waitForObject(":Forex Display Properties.OK_FixedSizeButton"))
    test.passes("Pass")
    snooze(2)
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/1"), 13, 62, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "Display Properties..."))
    clickButton(waitForObject(":Forex Display Properties. _FixedSizeButton_3"))
    clickButton(waitForObject(":Forex Display Properties_FixedSizeButton_3"))
    clickButton(waitForObject(":Forex Display Properties.OK_FixedSizeButton"))
    test.passes("Pass")
    snooze(2)
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/1"), 80, 57, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "Display Properties..."))
    clickButton(waitForObject(":Forex Display Properties. _FixedSizeButton_4"))
    clickButton(waitForObject(":Forex Display Properties_FixedSizeButton_4"))
    clickButton(waitForObject(":Forex Display Properties. _FixedSizeButton_5"))
    clickButton(waitForObject(":Forex Display Properties_FixedSizeButton_5"))
    clickButton(waitForObject(":Forex Display Properties.OK_FixedSizeButton"))
    test.passes("Pass")
    snooze(2)
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/1"), 33, 37, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "Display Properties..."))
    clickButton(waitForObject(":Forex Display Properties. _FixedSizeButton_6"))
    clickButton(waitForObject(":Forex Display Properties_FixedSizeButton_2"))
    clickButton(waitForObject(":Forex Display Properties. _FixedSizeButton_7"))
    clickButton(waitForObject(":Forex Display Properties_FixedSizeButton_6"))
    clickButton(waitForObject(":Forex Display Properties. _FixedSizeButton_8"))
    clickButton(waitForObject(":Forex Display Properties_FixedSizeButton_6"))
    clickButton(waitForObject(":Forex Display Properties. _FixedSizeButton_9"))
    clickButton(waitForObject(":Forex Display Properties_FixedSizeButton_7"))
    clickButton(waitForObject(":Forex Display Properties.OK_FixedSizeButton"))
    test.passes("Pass")
    snooze(2)
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/1"), 79, 58, 0, Button.Button1)
    doubleClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/1"), 79, 58, 0, Button.Button1)
    type(waitForObject(":Market-Q (qa)_LCTextField_24"), "cad a0-fx")
    type(waitForObject(":Market-Q (qa)_LCTextField_24"), "<Return>")
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/1"), 73, 7, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "Display Properties..."))
    clickButton(waitForObject(":Forex Display Properties. _FixedSizeButton_10"))
    clickButton(waitForObject(":Forex Display Properties_FixedSizeButton_8"))
    clickButton(waitForObject(":Forex Display Properties. _FixedSizeButton_11"))
    clickButton(waitForObject(":Forex Display Properties_FixedSizeButton_9"))
    clickButton(waitForObject(":Forex Display Properties. _FixedSizeButton_12"))
    clickButton(waitForObject(":Forex Display Properties_FixedSizeButton_10"))
    clickButton(waitForObject(":Forex Display Properties.OK_FixedSizeButton"))
    test.passes("Pass")
    snooze(2)
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/2"), 88, 43, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "Display Properties..."))
    mouseClick(waitForObjectItem(":Forex Display Properties.com.futuresource.livecharts.common.LCCardList$1_LCList", "Change Indicator  "), 77, 4, 0, Button.Button1)
    mouseClick(waitForObject(":Forex Display Properties.Show Changed Indicator_LCCheckBox"), 10, 6, 0, Button.Button1)
    clickButton(waitForObject(":Forex Display Properties.OK_FixedSizeButton"))
    test.passes("Pass")
    snooze(2)
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/2"), 79, 56, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "Display Properties..."))
    mouseClick(waitForObject(":Forex Display Properties.Show Changed Indicator_LCCheckBox"), 11, 10, 0, Button.Button1)
    clickButton(waitForObject(":Forex Display Properties. _FixedSizeButton_13"))
    clickButton(waitForObject(":Forex Display Properties_FixedSizeButton_8"))
    clickButton(waitForObject(":Forex Display Properties. _FixedSizeButton_14"))
    clickButton(waitForObject(":Forex Display Properties_FixedSizeButton_9"))
    clickButton(waitForObject(":Forex Display Properties.OK_FixedSizeButton"))
    test.passes("Pass")
    snooze(2)
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/2"), 90, 60, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "Display Properties..."))
    mouseClick(waitForObjectItem(":Forex Display Properties.com.futuresource.livecharts.common.LCCardList$1_LCList", "Formatting  "), 43, 10, 0, Button.Button1)
    mouseClick(waitForObject(":Forex Display Properties.com.futuresource.livecharts.common.LCComboBox_LCComboBox"), 35, 6, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Forex Display Properties.ComboBox.list_JList", "3"), 22, 6, 0, Button.Button1)
    clickButton(waitForObject(":Forex Display Properties.OK_FixedSizeButton"))
    test.passes("Pass")
    snooze(1)
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 312, 9, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "Display Properties..."))
    mouseClick(waitForObject(":Forex Display Properties.Show New Cell_LCCheckBox"), 12, 11, 0, Button.Button1)
    clickButton(waitForObject(":Forex Display Properties.OK_FixedSizeButton"))
    test.passes("Pass")
    snooze(2)
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 346, 13, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "Display Properties..."))
    mouseClick(waitForObject(":Forex Display Properties.Show New Cell_LCCheckBox"), 6, 7, 0, Button.Button1)
    mouseClick(waitForObject(":Forex Display Properties.Show Alert Indicator_LCCheckBox"), 10, 4, 0, Button.Button1)
    clickButton(waitForObject(":Forex Display Properties.OK_FixedSizeButton"))
    test.passes("Pass")
    snooze(2)
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 317, 18, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "Display Properties..."))
    mouseClick(waitForObject(":Forex Display Properties.Show Alert Indicator_LCCheckBox"), 11, 4, 0, Button.Button1)
    mouseClick(waitForObject(":Forex Display Properties.Show Flags_LCCheckBox"), 11, 4, 0, Button.Button1)
    clickButton(waitForObject(":Forex Display Properties.OK_FixedSizeButton"))
    test.passes("Pass")
    snooze(2)
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 285, 6, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "Display Properties..."))
    mouseClick(waitForObject(":Forex Display Properties.Show Flags_LCCheckBox"), 9, 10, 0, Button.Button1)
    mouseClick(waitForObject(":Forex Display Properties.Show Symbol as Description_LCCheckBox"), 9, 12, 0, Button.Button1)
    clickButton(waitForObject(":Forex Display Properties.OK_FixedSizeButton"))
    test.passes("Pass")
    snooze(2)
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 327, 15, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "Display Properties..."))
    mouseClick(waitForObject(":Forex Display Properties.Show Symbol as Description_LCCheckBox"), 8, 7, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Forex Display Properties.com.futuresource.livecharts.common.LCCardList$1_LCList", "Gridlines  "), 53, 7, 0, Button.Button1)
    setValue(waitForObject(":Forex Display Properties.Margin:_LCSpinner"), 6)
    setValue(waitForObject(":Forex Display Properties.Margin:_LCSpinner"), 7)
    setValue(waitForObject(":Forex Display Properties.Margin:_LCSpinner"), 8)
    setValue(waitForObject(":Forex Display Properties.Margin:_LCSpinner"), 9)
    setValue(waitForObject(":Forex Display Properties.Margin:_LCSpinner"), 10)
    clickButton(waitForObject(":Forex Display Properties.OK_FixedSizeButton"))
    test.passes("Pass")
    snooze(2)
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "0/0"), 336, 24, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.forex.ForexTable_ForexTable", "Display Properties..."))
    clickButton(waitForObject(":Forex Display Properties. _FixedSizeButton_15"))
    clickButton(waitForObject(":Forex Display Properties_FixedSizeButton_11"))
    clickButton(waitForObject(":Forex Display Properties.OK_FixedSizeButton"))
    test.passes("Pass")

    snooze(40)
