def QuotesGrid():
    
    testSettings.logScreenshotOnFail = True
    testSettings.logScreenshotOnError = True


    clickButton(waitForObject(":Market-Q (qa).Quotes Grid_MonsoonNewPadButton"))
    test.compare(waitForObjectExists(":Market-Q (qa).Quotes Grid_LCLabel").text, "Quotes Grid")
    snooze(1)
    
    clickButton(waitForObject(":Market-Q (qa).Fields + Bar_SmallButton"))
    snooze(1)
    activateItem(waitForObjectItem(":Market-Q (qa).Fields + Bar_SmallButton", "Header"))
    snooze(1)
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/0"), 77, 40, 0, Button.Button1)
    doubleClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/0"), 77, 40, 0, Button.Button1)
    type(waitForObject(":Market-Q (qa)_LCTextField_24"), "IBM")
    type(waitForObject(":Market-Q (qa)_LCTextField_24"), "<Return>")
    snooze(1)
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/1"), 49, 38, 0, Button.Button1)
    doubleClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/1"), 49, 38, 0, Button.Button1)
    type(waitForObject(":Market-Q (qa)_LCTextField_24"), "msft")
    type(waitForObject(":Market-Q (qa)_LCTextField_24"), "<Return>")
    snooze(1)
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/2"), 66, 35, 0, Button.Button1)
    doubleClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/2"), 66, 35, 0, Button.Button1)
    type(waitForObject(":Market-Q (qa)_LCTextField_24"), "orcl")
    type(waitForObject(":Market-Q (qa)_LCTextField_24"), "<Return>")
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/3"), 66, 40, 0, Button.Button1)
    doubleClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/3"), 66, 40, 0, Button.Button1)
    type(waitForObject(":Market-Q (qa)_LCTextField_24"), "goog")
    type(waitForObject(":Market-Q (qa)_LCTextField_24"), "<Return>")
    snooze(1)
    test.compare(waitForObjectExists(":Market-Q (qa).Header_SmallButton").actioncommand, "Header")
    clickButton(waitForObject(":Market-Q (qa).Header_SmallButton"))
    
    activateItem(waitForObjectItem(":Market-Q (qa).Header_SmallButton", "Header + Bar"))
    test.compare(waitForObjectExists(":Market-Q (qa).Header + Bar_SmallButton").actioncommand, "Header + Bar")
    snooze(1)
    
    clickButton(waitForObject(":Market-Q (qa).Header + Bar_SmallButton"))
    activateItem(waitForObjectItem(":Market-Q (qa).Header + Bar_SmallButton", "Header + Bar + Fields"))
    test.compare(waitForObjectExists(":Market-Q (qa).Header + Bar + Fields_SmallButton").actioncommand, "Header + Bar + Fields")
    snooze(1)
    
    clickButton(waitForObject(":Market-Q (qa).Header + Bar + Fields_SmallButton"))
    activateItem(waitForObjectItem(":Market-Q (qa).Header + Bar + Fields_SmallButton", "Header + Fields"))
    test.compare(waitForObjectExists(":Market-Q (qa).Header + Fields_SmallButton").actioncommand, "Header + Fields")
    snooze(1)
    
    clickButton(waitForObject(":Market-Q (qa).Header + Fields_SmallButton"))
    activateItem(waitForObjectItem(":Market-Q (qa).Header + Fields_SmallButton", "Header + Fields + Bar"))
    test.compare(waitForObjectExists(":Market-Q (qa).Header + Fields + Bar_SmallButton").actioncommand, "Header + Fields + Bar")
    snooze(1)
    
    clickButton(waitForObject(":Market-Q (qa).Header + Fields + Bar_SmallButton"))
    activateItem(waitForObjectItem(":Market-Q (qa).Header + Fields + Bar_SmallButton", "Bar + Header"))
    test.compare(waitForObjectExists(":Market-Q (qa).Bar + Header_SmallButton").actioncommand, "Bar + Header")
    snooze(1)
    
    clickButton(waitForObject(":Market-Q (qa).Bar + Header_SmallButton"))
    activateItem(waitForObjectItem(":Market-Q (qa).Bar + Header_SmallButton", "Bar + Header + Fields"))
    test.compare(waitForObjectExists(":Market-Q (qa).Bar + Header + Fields_SmallButton").actioncommand, "Bar + Header + Fields")
    snooze(1)
    
    clickButton(waitForObject(":Market-Q (qa).Bar + Header + Fields_SmallButton"))
    activateItem(waitForObjectItem(":Market-Q (qa).Bar + Header + Fields_SmallButton", "Bar + Fields"))
    test.compare(waitForObjectExists(":Market-Q (qa).Bar + Fields_SmallButton").actioncommand, "Bar + Fields")
    snooze(1)
    
    clickButton(waitForObject(":Market-Q (qa).Bar + Fields_SmallButton"))
    activateItem(waitForObjectItem(":Market-Q (qa).Bar + Fields_SmallButton", "Bar + Fields + Header"))
    test.compare(waitForObjectExists(":Market-Q (qa).Bar + Fields + Header_SmallButton").actioncommand, "Bar + Fields + Header")
    snooze(1)
    
    clickButton(waitForObject(":Market-Q (qa).Bar + Fields + Header_SmallButton"))
    activateItem(waitForObjectItem(":Market-Q (qa).Bar + Fields + Header_SmallButton", "Fields"))
    test.compare(waitForObjectExists(":Market-Q (qa).Fields_SmallButton").actioncommand, "Fields")
    snooze(1)
    
    clickButton(waitForObject(":Market-Q (qa).Fields_SmallButton"))
    activateItem(waitForObjectItem(":Market-Q (qa).Fields_SmallButton", "Fields + Bar"))
    test.compare(waitForObjectExists(":Market-Q (qa).Fields + Bar_SmallButton").actioncommand, "Fields + Bar")
    snooze(1)
    
    mouseClick(waitForObject(":Market-Q (qa).Quote Grid_QuoteGrid"), 144, 3, 0, Button.Button1)
    clickButton(waitForObject(":Market-Q (qa).Fields + Bar_SmallButton"))
    activateItem(waitForObjectItem(":Market-Q (qa).Fields + Bar_SmallButton", "Candlestick"))
    test.passes("Pass")
    snooze(1)
    
    clickButton(waitForObject(":Market-Q (qa).Fields + Bar_SmallButton"))
    activateItem(waitForObjectItem(":Market-Q (qa).Fields + Bar_SmallButton", "Thermometer"))
    test.passes("Pass")
    snooze(1)
    
    clickButton(waitForObject(":Market-Q (qa).Fields + Bar_SmallButton"))
    activateItem(waitForObjectItem(":Market-Q (qa).Fields + Bar_SmallButton", "Thermoboard"))
    test.passes("Pass")
    snooze(1)
    
    clickButton(waitForObject(":Market-Q (qa).Fields + Bar_SmallButton"))
    activateItem(waitForObjectItem(":Market-Q (qa).Fields + Bar_SmallButton", "Show Chart"))
    test.passes("Pass")
    snooze(1)
    
    clickButton(waitForObject(":Market-Q (qa).Fields + Bar_SmallButton"))
    activateItem(waitForObjectItem(":Market-Q (qa).Fields + Bar_SmallButton", "Define Fields..."))
    test.compare(waitForObjectExists(":com.futuresource.livecharts.common.LCCardList$1.General  _ListItemProxy_2").text, "General")
    clickButton(waitForObject(":Quote Grid Display Properties.OK_FixedSizeButton"))
    snooze(1)
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/0"), 214, 36, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "View"))
    activateItem(waitForObjectItem(":Market-Q (qa).View_JMenu_6", "Chart"))
    test.compare(waitForObjectExists(":Market-Q (qa).Chart_LCLabel").text, "Chart")
    clickButton(waitForObject(":Market-Q (qa)_JButton_7"))
    test.passes("Pass")
    snooze(1)
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/0"), 225, 40, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "Add To Symbol list"))
    activateItem(waitForObjectItem(":Market-Q (qa).Add To Symbol list_JMenu_7", "Workspace Symbol Lists"))
    activateItem(waitForObjectItem(":Workspace Symbol Lists_JMenu_7", "Global Financial Futures"))
    clickButton(waitForObject(":Information.OK_FixedSizeButton"))
    clickButton(waitForObject(":Market-Q (qa).Watch List_MonsoonNewPadButton"))
    clickButton(waitForObject(":Market-Q (qa).Symbol List_LCTreeButton"))
    mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Workspace Symbol Lists.Global Financial Futures"), 88, 7, 0, Button.Button1)
    setValue(waitForObject(":Market-Q (qa)_JScrollBar_4"), 157)
    test.compare(waitForObjectExists(":com.futuresource.livecharts.newquotes.QuotePad$2.40_0_TableItemProxy").text, "IBM")
    snooze(1)
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/0"), 159, 66, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "Add To Symbol list"))
    activateItem(waitForObjectItem(":Market-Q (qa).Add To Symbol list_JMenu_7", "Mobile Home Page (Phone Only)"))
    activateItem(waitForObjectItem(":Mobile Home Page (Phone Only)_JMenu_6", "World"))
    clickButton(waitForObject(":Information.OK_FixedSizeButton"))
    clickButton(waitForObject(":Market-Q (qa).Global Financial Futures_LCTreeButton"))
    mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Mobile Home Page (Phone Only).World"), 30, 7, 0, Button.Button1)
    test.compare(waitForObjectExists(":com.futuresource.livecharts.newquotes.QuotePad$2.7_0_TableItemProxy").text, "IBM")
    snooze(1)
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/0"), 146, 39, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "Add To Symbol list"))
    activateItem(waitForObjectItem(":Market-Q (qa).Add To Symbol list_JMenu_7", "Shared Symbol Lists"))
    activateItem(waitForObjectItem(":Shared Symbol Lists_JMenu_4", "List 1"))
    clickButton(waitForObject(":Information.OK_FixedSizeButton"))
    clickButton(waitForObject(":Market-Q (qa).World_LCTreeButton"))
    mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Shared Symbol Lists.List 1"), 48, 7, 0, Button.Button1)
    test.compare(waitForObjectExists(":com.futuresource.livecharts.newquotes.QuotePad$2.2_0_TableItemProxy").text, "IBM")
    clickButton(waitForObject(":Market-Q (qa)_JButton_7"))
    test.passes("Pass")
    snooze(1)
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/0"), 100, 59, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "Alerts"))
    activateItem(waitForObjectItem(":Market-Q (qa).Alerts_JMenu_4", "Add Quote Alert"))
    type(waitForObject(":Add Quote Alert_LCTextField_3"), "143")
    mouseClick(waitForObject(":Add Quote Alert_LCTextArea"), 75, 36, 0, Button.Button1)
    type(waitForObject(":Add Quote Alert_LCTextArea"), "quote frid test")
    clickButton(waitForObject(":Add Quote Alert.OK_FixedSizeButton"))
    test.passes("Pass")
    snooze(1)
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/0"), 203, 53, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "Alerts"))
    activateItem(waitForObjectItem(":Market-Q (qa).Alerts_JMenu_4", "Add News Alert"))
    mouseClick(waitForObject(":Add News Alert_LCTextArea"), 136, 28, 0, Button.Button1)
    type(waitForObject(":Add News Alert_LCTextArea"), "test")
    clickButton(waitForObject(":Add News Alert.OK_FixedSizeButton"))
    test.passes("Pass")
    snooze(1)
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/0"), 220, 54, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "Alerts"))
    activateItem(waitForObjectItem(":Market-Q (qa).Alerts_JMenu_4", "__Alerts"))
    clickTab(waitForObject(":Market-Q (qa).News Alerts_TabProxy"))
    test.compare(waitForObjectExists(":Market-Q (qa).Alerts_LCLabel").text, "Alerts")
    clickButton(waitForObject(":Market-Q (qa)_JButton_7"))
    test.passes("Pass")
    snooze(1)
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/0"), 99, 38, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "Alerts"))
    activateItem(waitForObjectItem(":Market-Q (qa).Alerts_JMenu_4", "Triggered Alerts"))
    clickButton(waitForObject(":Alert Log.Quote Alerts_LCDropDownButton"))
    activateItem(waitForObjectItem(":Alert Log.Quote Alerts_LCDropDownButton", "News Alerts"))
    clickButton(waitForObject(":Alert Log.News Alerts_LCDropDownButton"))
    activateItem(waitForObjectItem(":Alert Log.News Alerts_LCDropDownButton", "Condition Alerts"))
    clickButton(waitForObject(":Alert Log.Condition Alerts_LCDropDownButton"))
    activateItem(waitForObjectItem(":Alert Log.Condition Alerts_LCDropDownButton", "Time Alerts"))
    clickButton(waitForObject(":Alert Log.Export to CSV_FixedSizeButton"))
    type(waitForObject(":Save.File Name:_JTextField"), "quotesgrid")
    snooze(2)
    clickButton(waitForObject(":Save.Save_JButton"))
    snooze(1)
    clickButton(waitForObject(":Information.OK_FixedSizeButton"))
    clickButton(waitForObject(":Alert Log.Print_FixedSizeButton"))
    clickButton(waitForObject(":Print Alert Log.OK_FixedSizeButton"))
    clickButton(waitForObject(":Print.Cancel_JButton"))
    clickButton(waitForObject(":Alert Log.Clear_FixedSizeButton"))
    clickButton(waitForObject(":Alert Log.Close_FixedSizeButton"))
    test.passes("Pass")
    snooze(1)
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/0"), 167, 59, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "Notes"))   
    snooze(1)
    type(waitForObject(":Note - IBM_JTextPane"), "test notes")
    snooze(1)
    mouseClick(waitForObject(":Note - IBM_LCToggleButton"), 6, 11, 0, Button.Button1)
    mouseClick(waitForObject(":Note - IBM_LCToggleButton_2"), 4, 11, 0, Button.Button1)
    mouseClick(waitForObject(":Note - IBM_LCToggleButton_3"), 6, 9, 0, Button.Button1)
    clickButton(waitForObject(":Note - IBM. _FixedSizeButton"))
    clickButton(waitForObject(":Note - IBM_FixedSizeButton"))
    clickButton(waitForObject(":Note - IBM.OK_FixedSizeButton"))
    test.passes("Pass")
    snooze(2)
    


    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/0"), 160, 31, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "Reload Selected Chart(s)"))

    snooze(2)
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/0"), 167, 59, 4, Button.Button3)    
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "Conversion"))
    mouseClick(waitForObject(":Currency and Unit Conversion_CommonButton"), 8, 6, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Currency and Unit Conversion.ComboBox.list_JList", "AUD"), 141, 7, 0, Button.Button1)
    mouseClick(waitForObject(":Currency and Unit Conversion_CommonButton_2"), 10, 6, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Currency and Unit Conversion.ComboBox.list_JList", "DEFAULT"), 50, 7, 0, Button.Button1)
    clickButton(waitForObject(":Currency and Unit Conversion.OK_FixedSizeButton"))

    snooze(3)
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/0"), 87, 53, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "Insert"))
    activateItem(waitForObjectItem(":Market-Q (qa).Insert_JMenu_6", "Insert Row"))
    snooze(1)
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/0"), 100, 61, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "Insert"))
    activateItem(waitForObjectItem(":Market-Q (qa).Insert_JMenu_6", "Insert Column"))
    snooze(1)
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/0"), 123, 57, 0, Button.Button1)
    doubleClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/0"), 123, 57, 0, Button.Button1)
    type(waitForObject(":Market-Q (qa)_LCTextField_24"), "googl")
    type(waitForObject(":Market-Q (qa)_LCTextField_24"), "<Return>")
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/0"), 83, 58, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "Delete"))
    activateItem(waitForObjectItem(":Market-Q (qa).Delete_JMenu_4", "Delete"))
    snooze(1)
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/0"), 116, 78, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "Delete"))
    activateItem(waitForObjectItem(":Market-Q (qa).Delete_JMenu_4", "Delete selected row(s)"))
    snooze(1)
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/0"), 55, 51, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "Delete"))
    activateItem(waitForObjectItem(":Market-Q (qa).Delete_JMenu_4", "Delete selected column(s)"))
    snooze(1)
    test.passes("Pass")
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/0"), 106, 64, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "Edit"))
    activateItem(waitForObjectItem(":Market-Q (qa).Edit_JMenu_4", "Cut"))
    snooze(1)
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/0"), 108, 59, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "Edit"))
    activateItem(waitForObjectItem(":Market-Q (qa).Edit_JMenu_4", "Paste"))
    snooze(1)
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/0"), 95, 56, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "Edit"))
    activateItem(waitForObjectItem(":Market-Q (qa).Edit_JMenu_4", "Copy"))
    snooze(1)
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "1/0"), 113, 61, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "Edit"))
    activateItem(waitForObjectItem(":Market-Q (qa).Edit_JMenu_4", "Paste"))
    snooze(1)  

    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "1/0"), 86, 50, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "Edit"))
    activateItem(waitForObjectItem(":Market-Q (qa).Edit_JMenu_4", "Select All"))
    snooze(2)
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/0"), 84, 79, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "Edit"))
    activateItem(waitForObjectItem(":Market-Q (qa).Edit_JMenu_4", "Clear Selection"))
    test.passes("Pass")
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/0"), 66, 74, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "Insert Symbols from file..."))
    mouseClick(waitForObject(":Open.Look In:_JButton"), 7, 6, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Open.ComboBox.list_JList", "Desktop"), 50, 13, 0, Button.Button1)
    setValue(waitForObject(":Open_JScrollBar"), 133)
    mouseClick(waitForObjectItem(":Open_JList", "Symbols.txt"), 33, 7, 0, Button.Button1)
    clickButton(waitForObject(":Open.Open_JButton"))
    setValue(waitForObject(":Market-Q (qa)_JScrollBar_2"), 0)
    test.passes("Pass")
    snooze(1)
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "1/1"), 50, 60, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "Print"))
    clickButton(waitForObject(":Print Quotes Grid.OK_FixedSizeButton"))
    clickButton(waitForObject(":Print.Cancel_JButton"))
    test.passes("Pass")
    snooze(1)
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/0"), 61, 45, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "Defaults"))
    activateItem(waitForObjectItem(":Market-Q (qa).Defaults_JMenu_9", "Save Quotes Grid Properties As Default"))
    clickButton(waitForObject(":Information.OK_FixedSizeButton"))
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "1/0"), 237, 64, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "Display Properties..."))
    mouseClick(waitForObjectItem(":Quote Grid Display Properties.com.futuresource.livecharts.common.LCCardList$1_LCList", "General  "), 48, 6, 0, Button.Button1)
    mouseClick(waitForObject(":Quote Grid Display Properties_CommonButton"), 9, 5, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Quote Grid Display Properties.ComboBox.list_JList", "Times New Roman"), 60, 11, 0, Button.Button1)
    mouseClick(waitForObject(":Quote Grid Display Properties.com.futuresource.livecharts.common.LCComboBox_LCComboBox"), 16, 7, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Quote Grid Display Properties.ComboBox.list_JList", "17"), 15, 9, 0, Button.Button1)
    clickButton(waitForObject(":Quote Grid Display Properties.OK_FixedSizeButton"))
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/0"), 84, 103, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "Defaults"))
    activateItem(waitForObjectItem(":Market-Q (qa).Defaults_JMenu_9", "Save Quotes Grid Properties As Default"))
    clickButton(waitForObject(":Question.Yes_FixedSizeButton"))
    clickButton(waitForObject(":Information.OK_FixedSizeButton"))
    test.passes("Pass")
    snooze(2)
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/0"), 146, 86, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "Defaults"))
    activateItem(waitForObjectItem(":Market-Q (qa).Defaults_JMenu_9", "Apply Default Properties to the Quotes Grid"))
    clickButton(waitForObject(":Market-Q (qa)_JButton_5"))
    clickButton(waitForObject(":Market-Q (qa).Quotes Grid_MonsoonNewPadButton"))
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/0"), 163, 89, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "Insert Symbols from file..."))
    setValue(waitForObject(":Open_JScrollBar"), 238)
    mouseClick(waitForObjectItem(":Open_JList", "Symbols.txt"), 56, 5, 0, Button.Button1)
    clickButton(waitForObject(":Open.Open_JButton"))
    test.passes("Pass")
    snooze(2)
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/0"), 173, 72, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "Defaults"))
    activateItem(waitForObjectItem(":Market-Q (qa).Defaults_JMenu_9", "Apply Default Properties to all Quotes Grid Windows"))
    clickButton(waitForObject(":Market-Q (qa)_JButton_5"))
    clickButton(waitForObject(":Market-Q (qa).Quotes Grid_MonsoonNewPadButton"))
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/0"), 172, 84, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "Insert Symbols from file..."))
    setValue(waitForObject(":Open_JScrollBar"), 229)
    mouseClick(waitForObjectItem(":Open_JList", "Symbols.txt"), 48, 9, 0, Button.Button1)
    clickButton(waitForObject(":Open.Open_JButton"))
    test.passes("Pass")
    snooze(2)
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/0"), 78, 73, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "Defaults"))
    activateItem(waitForObjectItem(":Market-Q (qa).Defaults_JMenu_9", "Remove Default Quotes Grid Properties"))
    clickButton(waitForObject(":Question.Yes_FixedSizeButton"))
    clickButton(waitForObject(":Information.OK_FixedSizeButton"))
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/0"), 134, 85, 4, Button.Button3)
    clickButton(waitForObject(":Market-Q (qa)_JButton_5"))
    clickButton(waitForObject(":Market-Q (qa).Quotes Grid_MonsoonNewPadButton"))
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/0"), 51, 59, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "Insert Symbols from file..."))
    setValue(waitForObject(":Open_JScrollBar"), 308)
    mouseClick(waitForObjectItem(":Open_JList", "Symbols.txt"), 37, 7, 0, Button.Button1)
    clickButton(waitForObject(":Open.Open_JButton"))
    test.passes("Pass")
    snooze(2)
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/0"), 21, 52, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "Display Properties..."))
    test.compare(waitForObjectExists(":com.futuresource.livecharts.common.LCCardList$1.General  _ListItemProxy_2").text, "General")
    clickButton(waitForObject(":Quote Grid Display Properties.OK_FixedSizeButton"))
    test.passes("Pass")
    snooze(2)
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/0"), 75, 53, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "Display Properties..."))
    mouseClick(waitForObject(":Quote Grid Display Properties.Show: _CommonButton"), 8, 7, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Quote Grid Display Properties.ComboBox.list_JList", "Header"), 29, 4, 0, Button.Button1)
    clickButton(waitForObject(":Quote Grid Display Properties.OK_FixedSizeButton"))
    test.compare(waitForObjectExists(":Market-Q (qa).Header_SmallButton").actioncommand, "Header")
    snooze(1)
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/1"), 32, 39, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "Display Properties..."))
    mouseClick(waitForObject(":Quote Grid Display Properties.com.futuresource.livecharts.common.LCComboBox_LCComboBox_2"), 85, 13, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Quote Grid Display Properties.ComboBox.list_JList", "Header + Bar"), 81, 7, 0, Button.Button1)
    clickButton(waitForObject(":Quote Grid Display Properties.OK_FixedSizeButton"))
    test.compare(waitForObjectExists(":Market-Q (qa).Header + Bar_SmallButton").actioncommand, "Header + Bar")
    snooze(1)
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/1"), 19, 47, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "Display Properties..."))
    mouseClick(waitForObject(":Quote Grid Display Properties.com.futuresource.livecharts.common.LCComboBox_LCComboBox_2"), 68, 14, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Quote Grid Display Properties.ComboBox.list_JList", "Header + Bar + Fields"), 67, 4, 0, Button.Button1)
    clickButton(waitForObject(":Quote Grid Display Properties.OK_FixedSizeButton"))
    test.compare(waitForObjectExists(":Market-Q (qa).Header + Bar + Fields_SmallButton").actioncommand, "Header + Bar + Fields")
    snooze(1)
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/0"), 127, 33, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "Display Properties..."))
    mouseClick(waitForObject(":Quote Grid Display Properties.com.futuresource.livecharts.common.LCComboBox_LCComboBox_2"), 95, 2, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Quote Grid Display Properties.ComboBox.list_JList", "Header + Fields"), 109, 11, 0, Button.Button1)
    clickButton(waitForObject(":Quote Grid Display Properties.OK_FixedSizeButton"))
    test.compare(waitForObjectExists(":Market-Q (qa).Header + Fields_SmallButton").actioncommand, "Header + Fields")
    snooze(1)
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/1"), 104, 71, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "Display Properties..."))
    mouseClick(waitForObject(":Quote Grid Display Properties.com.futuresource.livecharts.common.LCComboBox_LCComboBox_2"), 67, 12, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Quote Grid Display Properties.ComboBox.list_JList", "Header + Fields + Bar"), 95, 1, 0, Button.Button1)
    clickButton(waitForObject(":Quote Grid Display Properties.OK_FixedSizeButton"))
    test.compare(waitForObjectExists(":Market-Q (qa).Header + Fields + Bar_SmallButton").actioncommand, "Header + Fields + Bar")
    snooze(1)
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/1"), 99, 30, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "Display Properties..."))
    mouseClick(waitForObject(":Quote Grid Display Properties.com.futuresource.livecharts.common.LCComboBox_LCComboBox_2"), 88, 2, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Quote Grid Display Properties.ComboBox.list_JList", "Bar + Header"), 87, 2, 0, Button.Button1)
    clickButton(waitForObject(":Quote Grid Display Properties.OK_FixedSizeButton"))
    test.compare(waitForObjectExists(":Market-Q (qa).Bar + Header_SmallButton").actioncommand, "Bar + Header")
    snooze(1)
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/2"), 62, 23, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "Display Properties..."))
    mouseClick(waitForObject(":Quote Grid Display Properties.com.futuresource.livecharts.common.LCComboBox_LCComboBox_2"), 66, 11, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Quote Grid Display Properties.ComboBox.list_JList", "Bar + Header + Fields"), 77, 7, 0, Button.Button1)
    clickButton(waitForObject(":Quote Grid Display Properties.OK_FixedSizeButton"))
    test.compare(waitForObjectExists(":Market-Q (qa).Bar + Header + Fields_SmallButton").actioncommand, "Bar + Header + Fields")
    snooze(1)
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/2"), 140, 71, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "Display Properties..."))
    mouseClick(waitForObject(":Quote Grid Display Properties.com.futuresource.livecharts.common.LCComboBox_LCComboBox_2"), 101, 2, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Quote Grid Display Properties.ComboBox.list_JList", "Bar + Fields"), 84, 7, 0, Button.Button1)
    clickButton(waitForObject(":Quote Grid Display Properties.OK_FixedSizeButton"))
    test.compare(waitForObjectExists(":Market-Q (qa).Bar + Fields_SmallButton").actioncommand, "Bar + Fields")
    snooze(1)
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/3"), 55, 94, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "Display Properties..."))
    mouseClick(waitForObject(":Quote Grid Display Properties.com.futuresource.livecharts.common.LCComboBox_LCComboBox_2"), 126, 9, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Quote Grid Display Properties.ComboBox.list_JList", "Bar + Fields + Header"), 100, 14, 0, Button.Button1)
    clickButton(waitForObject(":Quote Grid Display Properties.OK_FixedSizeButton"))
    test.compare(waitForObjectExists(":Market-Q (qa).Bar + Fields + Header_SmallButton").actioncommand, "Bar + Fields + Header")
    snooze(1)
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/2"), 29, 51, 4, Button.Button3)
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/2"), 155, 52, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "Display Properties..."))
    mouseClick(waitForObject(":Quote Grid Display Properties.com.futuresource.livecharts.common.LCComboBox_LCComboBox_2"), 122, 10, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Quote Grid Display Properties.ComboBox.list_JList", "Fields"), 80, 3, 0, Button.Button1)
    clickButton(waitForObject(":Quote Grid Display Properties.OK_FixedSizeButton"))
    test.compare(waitForObjectExists(":Market-Q (qa).Fields_SmallButton").actioncommand, "Fields")
    snooze(1)
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/3"), 63, 101, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "Display Properties..."))
    mouseClick(waitForObject(":Quote Grid Display Properties.Show: _CommonButton"), 5, 5, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Quote Grid Display Properties.ComboBox.list_JList", "Fields + Bar"), 84, 10, 0, Button.Button1)
    clickButton(waitForObject(":Quote Grid Display Properties.OK_FixedSizeButton"))
    test.compare(waitForObjectExists(":Market-Q (qa).Fields + Bar_SmallButton").actioncommand, "Fields + Bar")
    snooze(1)
    


    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/3"), 31, 46, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "Display Properties..."))
    mouseClick(waitForObject(":Quote Grid Display Properties.Show Chart_LCCheckBox"), 8, 10, 0, Button.Button1)
    clickButton(waitForObject(":Quote Grid Display Properties.OK_FixedSizeButton"))

    snooze(3)
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/3"), 28, 65, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "Display Properties..."))
    mouseClick(waitForObject(":Quote Grid Display Properties.com.futuresource.livecharts.common.LCComboBox_LCComboBox_3"), 78, 6, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Quote Grid Display Properties.ComboBox.list_JList", "Times New Roman"), 83, 16, 0, Button.Button1)
    mouseClick(waitForObject(":Quote Grid Display Properties_CommonButton_2"), 13, 3, 0, Button.Button1)
    mouseClick(waitForObject(":Quote Grid Display Properties_CommonButton_2"), 7, 6, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Quote Grid Display Properties.ComboBox.list_JList", "13"), 21, 7, 0, Button.Button1)
    mouseClick(waitForObject(":Quote Grid Display Properties.Bold_LCCheckBox"), 12, 10, 0, Button.Button1)
    mouseClick(waitForObject(":Quote Grid Display Properties.Italic_LCCheckBox"), 8, 7, 0, Button.Button1)
    clickButton(waitForObject(":Quote Grid Display Properties.OK_FixedSizeButton"))
    test.passes("Pass")
    snooze(2)
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/3"), 47, 60, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "Display Properties..."))
    clickButton(waitForObject(":Quote Grid Display Properties. _FixedSizeButton"))
    clickButton(waitForObject(":Quote Grid Display Properties_FixedSizeButton"))
    clickButton(waitForObject(":Quote Grid Display Properties. _FixedSizeButton_2"))
    clickButton(waitForObject(":Quote Grid Display Properties_FixedSizeButton_2"))
    clickButton(waitForObject(":Quote Grid Display Properties. _FixedSizeButton_3"))
    test.passes("Pass")
    snooze(2)
    
    mouseClick(waitForObject(":Quote Grid Display Properties.com.futuresource.livecharts.common.LCPanel_LCPanel"), 65, 248, 0, Button.Button1)
    clickButton(waitForObject(":Quote Grid Display Properties.OK_FixedSizeButton"))
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/2"), 56, 94, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "Display Properties..."))
    clickButton(waitForObject(":Quote Grid Display Properties. _FixedSizeButton_3"))
    clickButton(waitForObject(":Quote Grid Display Properties_FixedSizeButton_3"))
    clickButton(waitForObject(":Quote Grid Display Properties.OK_FixedSizeButton"))
    test.passes("Pass")
    snooze(2)
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/2"), 87, 72, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/1"), 49, 62, 0, Button.Button1)
    doubleClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/1"), 49, 62, 0, Button.Button1)
    type(waitForObject(":Market-Q (qa)_LCTextField_24"), "<Return>")
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/1"), 64, 75, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "Display Properties..."))
    mouseClick(waitForObjectItem(":Quote Grid Display Properties.com.futuresource.livecharts.common.LCCardList$1_LCList", "Header  "), 34, 5, 0, Button.Button1)
    clickButton(waitForObject(":Quote Grid Display Properties. _FixedSizeButton_4"))
    clickButton(waitForObject(":Quote Grid Display Properties_FixedSizeButton_4"))
    clickButton(waitForObject(":Quote Grid Display Properties.OK_FixedSizeButton"))
    test.passes("Pass")
    snooze(2)
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/2"), 28, 69, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "Display Properties..."))
    clickButton(waitForObject(":Quote Grid Display Properties. _FixedSizeButton_5"))
    clickButton(waitForObject(":Quote Grid Display Properties_FixedSizeButton_5"))
    clickButton(waitForObject(":Quote Grid Display Properties.OK_FixedSizeButton"))
    test.passes("Pass")
    snooze(2)
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/2"), 65, 65, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "Display Properties..."))
    mouseClick(waitForObject(":Quote Grid Display Properties.Show Month Name_LCCheckBox"), 11, 8, 0, Button.Button1)
    clickButton(waitForObject(":Quote Grid Display Properties.OK_FixedSizeButton"))
    test.passes("Pass")
    snooze(2)
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/4"), 61, 68, 0, Button.Button1)
    doubleClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/4"), 61, 68, 0, Button.Button1)
    type(waitForObject(":Market-Q (qa)_LCTextField_24"), "cl")
    type(waitForObject(":Market-Q (qa)_LCTextField_24"), "<Return>")
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/4"), 61, 68, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "Display Properties..."))
    mouseClick(waitForObject(":Quote Grid Display Properties.Show Month Name_LCCheckBox"), 6, 6, 0, Button.Button1)
    clickButton(waitForObject(":Quote Grid Display Properties.OK_FixedSizeButton"))
    test.passes("Pass")
    snooze(2)
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/5"), 42, 73, 0, Button.Button1)
    doubleClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/5"), 42, 73, 0, Button.Button1)
    type(waitForObject(":Market-Q (qa)_LCTextField_24"), "cl 1!")
    type(waitForObject(":Market-Q (qa)_LCTextField_24"), "<Return>")
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/6"), 38, 74, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "Display Properties..."))
    mouseClick(waitForObject(":Quote Grid Display Properties.Show Symbol as Description_LCCheckBox"), 8, 9, 0, Button.Button1)
    clickButton(waitForObject(":Quote Grid Display Properties.OK_FixedSizeButton"))
    test.passes("Pass")
    snooze(2)
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/4"), 78, 61, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "Display Properties..."))
    mouseClick(waitForObject(":Quote Grid Display Properties.Click Action: _CommonButton"), 10, 6, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Quote Grid Display Properties.ComboBox.list_JList", "Open in Chart"), 143, 5, 0, Button.Button1)
    clickButton(waitForObject(":Quote Grid Display Properties.OK_FixedSizeButton"))
    test.passes("Pass")
    snooze(2)
    


    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/3"), 135, 81, 0, Button.Button1)
    test.compare(waitForObjectExists(":Market-Q (qa).Chart_LCLabel").text, "Chart")
    clickButton(waitForObject(":Market-Q (qa)_JButton_7"))
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/3"), 246, 73, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "Display Properties..."))
    mouseClick(waitForObject(":Quote Grid Display Properties.Double Click Action: _LCCheckBox"), 7, 11, 0, Button.Button1)
    mouseClick(waitForObject(":Quote Grid Display Properties.Double Click Action: _CommonButton"), 2, 6, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Quote Grid Display Properties.ComboBox.list_JList", "Open in Chart"), 134, 6, 0, Button.Button1)
    clickButton(waitForObject(":Quote Grid Display Properties.OK_FixedSizeButton"))
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/3"), 131, 87, 0, Button.Button1)
    doubleClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/3"), 131, 87, 0, Button.Button1)
    test.compare(waitForObjectExists(":Market-Q (qa).Chart_LCLabel").text, "Chart")
    clickButton(waitForObject(":Market-Q (qa)_JButton_7"))
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/3"), 166, 55, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "Display Properties..."))
    clickButton(waitForObject(":Quote Grid Display Properties. _FixedSizeButton_6"))
    clickButton(waitForObject(":Quote Grid Display Properties_FixedSizeButton_4"))
    clickButton(waitForObject(":Quote Grid Display Properties. _FixedSizeButton_7"))
    clickButton(waitForObject(":Quote Grid Display Properties_FixedSizeButton_6"))
    clickButton(waitForObject(":Quote Grid Display Properties. _FixedSizeButton_8"))
    clickButton(waitForObject(":Quote Grid Display Properties_FixedSizeButton_7"))
    clickButton(waitForObject(":Quote Grid Display Properties.OK_FixedSizeButton"))
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/3"), 275, 67, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "Display Properties..."))
    mouseClick(waitForObject(":Quote Grid Display Properties.Apply To All Field Values_LCCheckBox"), 6, 6, 0, Button.Button1)
    clickButton(waitForObject(":Quote Grid Display Properties.OK_FixedSizeButton"))
    setValue(waitForObject(":Market-Q (qa)_JScrollBar_2"), 0)
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/1"), 105, 73, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "Display Properties..."))
    mouseClick(waitForObject(":Quote Grid Display Properties.Flash: _CommonButton"), 6, 4, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Quote Grid Display Properties.ComboBox.list_JList", "Whole Cell"), 58, 2, 0, Button.Button1)
    clickButton(waitForObject(":Quote Grid Display Properties.OK_FixedSizeButton"))
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/2"), 102, 66, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "Display Properties..."))
    mouseClick(waitForObjectItem(":Quote Grid Display Properties.com.futuresource.livecharts.common.LCCardList$1_LCList", "Fields  "), 43, 6, 0, Button.Button1)
    mouseClick(waitForObject(":Quote Grid Display Properties.Show Short Field Names_LCCheckBox"), 6, 9, 0, Button.Button1)
    clickButton(waitForObject(":Quote Grid Display Properties.OK_FixedSizeButton"))
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/1"), 50, 100, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "Display Properties..."))
    mouseClick(waitForObject(":Quote Grid Display Properties.Show Short Field Names_LCCheckBox"), 8, 9, 0, Button.Button1)
    clickButton(waitForObject(":Quote Grid Display Properties. _FixedSizeButton_9"))
    clickButton(waitForObject(":Quote Grid Display Properties_FixedSizeButton_8"))
    clickButton(waitForObject(":Quote Grid Display Properties. _FixedSizeButton_10"))
    clickButton(waitForObject(":Quote Grid Display Properties_FixedSizeButton_9"))
    clickButton(waitForObject(":Quote Grid Display Properties.OK_FixedSizeButton"))
    


    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/0"), 154, 33, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "Display Properties..."))
    mouseClick(waitForObjectItem(":Quote Grid Display Properties.com.futuresource.livecharts.common.DefineActiveFieldsTable_DefineActiveFieldsTable", "0/0"), 95, 5, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Quote Grid Display Properties.com.futuresource.livecharts.common.DefineActiveFieldsTable_DefineActiveFieldsTable", "0/0"), 107, 9, 0, Button.Button1)
    doubleClick(waitForObjectItem(":Quote Grid Display Properties.com.futuresource.livecharts.common.DefineActiveFieldsTable_DefineActiveFieldsTable", "0/0"), 107, 9, 0, Button.Button1)
    mouseClick(waitForObject(":Quote Grid Display Properties.com.futuresource.livecharts.common.LCComboBox_LCComboBox_5"), 107, 9, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Quote Grid Display Properties.ComboBox.list_JList", "Open Interest"), 92, 6, 0, Button.Button1)
    clickButton(waitForObject(":Quote Grid Display Properties.OK_FixedSizeButton"))

    snooze(2)
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/1"), 97, 68, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "Display Properties..."))
    mouseClick(waitForObjectItem(":Quote Grid Display Properties.com.futuresource.livecharts.common.LCCardList$1_LCList", "Bar  "), 38, 10, 0, Button.Button1)
    mouseClick(waitForObject(":Quote Grid Display Properties.Bar chooser: _CommonButton"), 5, 7, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Quote Grid Display Properties.ComboBox.list_JList", "Thermometer"), 138, 4, 0, Button.Button1)
    clickButton(waitForObject(":Quote Grid Display Properties.OK_FixedSizeButton"))
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/0"), 159, 75, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "Display Properties..."))
    mouseClick(waitForObject(":Quote Grid Display Properties.com.futuresource.livecharts.common.LCComboBox_LCComboBox_4"), 140, 7, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Quote Grid Display Properties.ComboBox.list_JList", "Thermoboard"), 134, 6, 0, Button.Button1)
    clickButton(waitForObject(":Quote Grid Display Properties.OK_FixedSizeButton"))
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/0"), 226, 92, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "Display Properties..."))
    mouseClick(waitForObject(":Quote Grid Display Properties.Bar chooser: _CommonButton"), 3, 4, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Quote Grid Display Properties.ComboBox.list_JList", "Candlestick"), 120, 9, 0, Button.Button1)
    clickButton(waitForObject(":Quote Grid Display Properties. _FixedSizeButton_11"))
    clickButton(waitForObject(":Quote Grid Display Properties_FixedSizeButton_9"))
    clickButton(waitForObject(":Quote Grid Display Properties.OK_FixedSizeButton"))
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/0"), 251, 70, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "Display Properties..."))
    clickButton(waitForObject(":Quote Grid Display Properties. _FixedSizeButton_12"))
    clickButton(waitForObject(":Quote Grid Display Properties_FixedSizeButton_7"))
    clickButton(waitForObject(":Quote Grid Display Properties.OK_FixedSizeButton"))
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/1"), 26, 57, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "Display Properties..."))
    clickButton(waitForObject(":Quote Grid Display Properties. _FixedSizeButton_13"))
    clickButton(waitForObject(":Quote Grid Display Properties_FixedSizeButton_10"))
    clickButton(waitForObject(":Quote Grid Display Properties.OK_FixedSizeButton"))
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/1"), 181, 50, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "Display Properties..."))
    clickButton(waitForObject(":Quote Grid Display Properties. _FixedSizeButton_14"))
    clickButton(waitForObject(":Quote Grid Display Properties_FixedSizeButton_11"))
    clickButton(waitForObject(":Quote Grid Display Properties.OK_FixedSizeButton"))
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/1"), 223, 36, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "Display Properties..."))
    mouseClick(waitForObject(":Quote Grid Display Properties.Bar chooser: _CommonButton"), 1, 4, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Quote Grid Display Properties.ComboBox.list_JList", "Thermometer"), 104, 4, 0, Button.Button1)
    clickButton(waitForObject(":Quote Grid Display Properties. _FixedSizeButton_15"))
    clickButton(waitForObject(":Quote Grid Display Properties_FixedSizeButton_12"))
    clickButton(waitForObject(":Quote Grid Display Properties.OK_FixedSizeButton"))
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/1"), 205, 68, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "Display Properties..."))
    clickButton(waitForObject(":Quote Grid Display Properties. _FixedSizeButton_16"))
    clickButton(waitForObject(":Quote Grid Display Properties_FixedSizeButton_13"))
    clickButton(waitForObject(":Quote Grid Display Properties.OK_FixedSizeButton"))
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/1"), 238, 54, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "Display Properties..."))
    mouseClick(waitForObject(":Quote Grid Display Properties.com.futuresource.livecharts.common.LCComboBox_LCComboBox_4"), 146, 6, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Quote Grid Display Properties.ComboBox.list_JList", "Thermoboard"), 103, 13, 0, Button.Button1)
    clickButton(waitForObject(":Quote Grid Display Properties. _FixedSizeButton_17"))
    clickButton(waitForObject(":Quote Grid Display Properties_FixedSizeButton_14"))
    clickButton(waitForObject(":Quote Grid Display Properties.OK_FixedSizeButton"))
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/1"), 218, 67, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "Display Properties..."))
    clickButton(waitForObject(":Quote Grid Display Properties. _FixedSizeButton_18"))
    clickButton(waitForObject(":Quote Grid Display Properties_FixedSizeButton_15"))
    clickButton(waitForObject(":Quote Grid Display Properties.OK_FixedSizeButton"))
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/1"), 261, 74, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "Display Properties..."))
    clickButton(waitForObject(":Quote Grid Display Properties. _FixedSizeButton_19"))
    clickButton(waitForObject(":Quote Grid Display Properties_FixedSizeButton_16"))
    clickButton(waitForObject(":Quote Grid Display Properties.OK_FixedSizeButton"))
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/2"), 56, 58, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "Display Properties..."))
    clickButton(waitForObject(":Quote Grid Display Properties. _FixedSizeButton_20"))
    clickButton(waitForObject(":Quote Grid Display Properties_FixedSizeButton_17"))
    clickButton(waitForObject(":Quote Grid Display Properties.OK_FixedSizeButton"))
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/2"), 106, 70, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "Display Properties..."))
    mouseClick(waitForObjectItem(":Quote Grid Display Properties.com.futuresource.livecharts.common.LCCardList$1_LCList", "Chart  "), 19, 9, 0, Button.Button1)
    clickButton(waitForObject(":Quote Grid Display Properties. _FixedSizeButton_21"))
    clickButton(waitForObject(":Quote Grid Display Properties_FixedSizeButton_18"))
    setValue(waitForObject(":Quote Grid Display Properties.Transparency: _LCSpinner"), 49)
    setValue(waitForObject(":Quote Grid Display Properties.Transparency: _LCSpinner"), 48)
    setValue(waitForObject(":Quote Grid Display Properties.Transparency: _LCSpinner"), 47)
    clickButton(waitForObject(":Quote Grid Display Properties. _FixedSizeButton_22"))
    clickButton(waitForObject(":Quote Grid Display Properties_FixedSizeButton_8"))
    clickButton(waitForObject(":Quote Grid Display Properties. _FixedSizeButton_23"))
    clickButton(waitForObject(":Quote Grid Display Properties_FixedSizeButton_3"))
    clickButton(waitForObject(":Quote Grid Display Properties.OK_FixedSizeButton"))
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/1"), 182, 76, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "Display Properties..."))
    mouseClick(waitForObjectItem(":Quote Grid Display Properties.com.futuresource.livecharts.common.LCCardList$1_LCList", "Flags  "), 31, 13, 0, Button.Button1)
    clickButton(waitForObject(":Quote Grid Display Properties. _FixedSizeButton_24"))
    clickButton(waitForObject(":Quote Grid Display Properties_FixedSizeButton_19"))
    clickButton(waitForObject(":Quote Grid Display Properties. _FixedSizeButton_25"))
    clickButton(waitForObject(":Quote Grid Display Properties_FixedSizeButton_20"))
    mouseClick(waitForObject(":Quote Grid Display Properties.NASDAQ Filing Status Codes_LCCheckBox"), 3, 10, 0, Button.Button1)
    clickButton(waitForObject(":Quote Grid Display Properties. _FixedSizeButton_26"))
    clickButton(waitForObject(":Quote Grid Display Properties_FixedSizeButton_21"))
    clickButton(waitForObject(":Quote Grid Display Properties.OK_FixedSizeButton"))
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/1"), 51, 52, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "Display Properties..."))
    mouseClick(waitForObjectItem(":Quote Grid Display Properties.com.futuresource.livecharts.common.LCCardList$1_LCList", "Formatting  "), 49, 13, 0, Button.Button1)
    mouseClick(waitForObject(":Quote Grid Display Properties.Show Full Precision_LCCheckBox"), 9, 9, 0, Button.Button1)
    mouseClick(waitForObject(":Quote Grid Display Properties.Show Full Price Precision_LCCheckBox"), 9, 9, 0, Button.Button1)
    clickButton(waitForObject(":Quote Grid Display Properties.OK_FixedSizeButton"))
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/1"), 261, 68, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "Display Properties..."))
    mouseClick(waitForObject(":Quote Grid Display Properties.Show Full Precision_LCCheckBox"), 11, 8, 0, Button.Button1)
    mouseClick(waitForObject(":Quote Grid Display Properties.Show Full Price Precision_LCCheckBox"), 3, 11, 0, Button.Button1)
    clickButton(waitForObject(":Quote Grid Display Properties.OK_FixedSizeButton"))
    
    mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "0/1"), 192, 77, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.quotegrid.QuoteGrid$QuoteGridTable_SpanCellTable", "Display Properties..."))
    mouseClick(waitForObjectItem(":Quote Grid Display Properties.com.futuresource.livecharts.common.LCCardList$1_LCList", "Conversion  "), 62, 11, 0, Button.Button1)
    mouseClick(waitForObject(":Quote Grid Display Properties.Use Global Settings_LCCheckBox"), 13, 8, 0, Button.Button1)
    mouseClick(waitForObject(":Quote Grid Display Properties_CommonButton_4"), 8, 6, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Quote Grid Display Properties.ComboBox.list_JList", "EUR"), 136, 11, 0, Button.Button1)
    clickButton(waitForObject(":Quote Grid Display Properties.OK_FixedSizeButton"))
    
    mouseClick(waitForObject(":Market-Q (qa).Quotes Grid_LCLabel"), 38, 2, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "New"))
    activateItem(waitForObjectItem(":Market-Q (qa).New_JMenu_9", "Watch List"))
    activateItem(waitForObjectItem(":Watch List_JMenu_6", "To the left"))
    mouseClick(waitForObject(":Market-Q (qa)_JPanel_14"), 23, 2, 4, Button.Button3)
    mouseClick(waitForObject(":Market-Q (qa). _LCLabel"), 3, 4, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa)_JPanel_4", "Show Window Title"))
    test.compare(waitForObjectExists(":Market-Q (qa).Watch List_LCLabel").text, "Watch List")
    clickButton(waitForObject(":Market-Q (qa)_JButton_5"))
    
    mouseClick(waitForObject(":Market-Q (qa).Quotes Grid_LCLabel"), 13, 7, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Show Window Title"))
    mouseClick(waitForObject(":Market-Q (qa). _LCLabel_7"), 9, 7, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Show Window Title"))
    test.compare(waitForObjectExists(":Market-Q (qa).Quotes Grid_LCLabel").text, "Quotes Grid")
    
    mouseClick(waitForObject(":Market-Q (qa).Quotes Grid_LCLabel"), 21, 8, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Show Titlebar description"))
    test.compare(waitForObjectExists(":Market-Q (qa).Quotes Grid_LCLabel_2").text, "Quotes Grid")
    
    mouseClick(waitForObject(":Market-Q (qa).Quotes Grid_LCLabel_2"), 24, 9, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Customize Titlebar Description..."))
    type(waitForObject(":Titlebar Description Settings.Quotes Grid_LCTextArea"), "Test ")
    mouseClick(waitForObject(":Titlebar Description Settings.Foreground: _LCCheckBox"), 7, 8, 0, Button.Button1)
    clickButton(waitForObject(":Titlebar Description Settings. _FixedSizeButton"))
    clickButton(waitForObject(":Titlebar Description Settings_FixedSizeButton_2"))
    mouseClick(waitForObject(":Titlebar Description Settings.Background: _LCCheckBox"), 7, 8, 0, Button.Button1)
    clickButton(waitForObject(":Titlebar Description Settings. _FixedSizeButton_2"))
    clickButton(waitForObject(":Titlebar Description Settings_FixedSizeButton_3"))
    mouseClick(waitForObject(":Titlebar Description Settings.Font: _LCCheckBox"), 10, 11, 0, Button.Button1)
    mouseClick(waitForObject(":Titlebar Description Settings.com.futuresource.livecharts.common.LCComboBox_LCComboBox_2"), 74, 15, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Titlebar Description Settings.ComboBox.list_JList", "Tempus Sans ITC"), 69, 13, 0, Button.Button1)
    mouseClick(waitForObject(":Titlebar Description Settings.com.futuresource.livecharts.common.LCComboBox_LCComboBox"), 17, 8, 0, Button.Button1)
    mouseClick(waitForObjectItem(":Titlebar Description Settings.ComboBox.list_JList", "13"), 14, 5, 0, Button.Button1)
    mouseClick(waitForObject(":Titlebar Description Settings.Bold_LCCheckBox"), 12, 9, 0, Button.Button1)
    mouseClick(waitForObject(":Titlebar Description Settings.Italic_LCCheckBox"), 8, 11, 0, Button.Button1)
    clickButton(waitForObject(":Titlebar Description Settings.OK_FixedSizeButton"))
    mouseClick(waitForObject(":Market-Q (qa).Test Quotes Grid_LCLabel"), 22, 14, 4, Button.Button3)
    test.compare(waitForObjectExists(":Market-Q (qa).Test Quotes Grid_LCLabel").text, "Test Quotes Grid")
    
    mouseClick(waitForObject(":Market-Q (qa).Test Quotes Grid_LCLabel"), 24, 5, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Copy Out"))
    test.compare(waitForObjectExists(":Quotes Grid.Test Quotes Grid_LCLabel").text, "Test Quotes Grid")
    mouseClick(waitForObject(":Quotes Grid.Test Quotes Grid_LCLabel"), 26, 12, 4, Button.Button3)
    activateItem(waitForObjectItem(":Quotes Grid_TitlebarPanel", "Attach"))
    mouseClick(waitForObject(":Market-Q (qa).Test Quotes Grid_LCLabel_2"), 586, 15, 0, Button.Button1)
    clickButton(waitForObject(":Market-Q (qa)_JButton_5"))
    
    mouseClick(waitForObject(":Market-Q (qa).Test Quotes Grid_LCLabel"), 28, 10, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Cut Window"))
    mouseClick(waitForObject(":Market-Q (qa)_JPanel_12"), 30, 1, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Paste Quotes Grid"))
    activateItem(waitForObjectItem(":Market-Q (qa).Paste Quotes Grid_JMenu", "In this window"))
    test.compare(waitForObjectExists(":Market-Q (qa).Test Quotes Grid_LCLabel").text, "Test Quotes Grid")
    
    mouseClick(waitForObject(":Market-Q (qa).Test Quotes Grid_LCLabel"), 22, 10, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Copy Window"))
    mouseClick(waitForObject(":Market-Q (qa).Test Quotes Grid_LCLabel"), 14, 2, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Paste Quotes Grid"))
    activateItem(waitForObjectItem(":Market-Q (qa).Paste Quotes Grid_JMenu", "To the left"))
    test.compare(waitForObjectExists(":Market-Q (qa).Test Quotes Grid_LCLabel").text, "Test Quotes Grid")
    mouseClick(waitForObject(":Market-Q (qa).Test Quotes Grid_LCLabel"), 594, 12, 0, Button.Button1)
    clickButton(waitForObject(":Market-Q (qa)_JButton_5"))
    
    mouseClick(waitForObject(":Market-Q (qa).Test Quotes Grid_LCLabel"), 26, 10, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Copy Window Image"))
    mouseClick(waitForObject(":Market-Q (qa).Test Quotes Grid_LCLabel"), 49, 10, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Paste Quotes Grid"))
    activateItem(waitForObjectItem(":Market-Q (qa).Paste Quotes Grid_JMenu", "To the left"))
    test.compare(waitForObjectExists(":Market-Q (qa).Test Quotes Grid_LCLabel").text, "Test Quotes Grid")
    
    mouseClick(waitForObject(":Market-Q (qa).Test Quotes Grid_LCLabel"), 12, 0, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Send Image by E-mail..."))
    
    mouseClick(waitForObject(":Market-Q (qa).Test Quotes Grid_LCLabel"), 582, 17, 0, Button.Button1)
    clickButton(waitForObject(":Market-Q (qa)_JButton_5"))
    
    mouseClick(waitForObject(":Market-Q (qa).Test Quotes Grid_LCLabel"), 39, 10, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Take Custom Screenshot"))
    
    dragItemBy(waitForObject(":Market-Q (qa).Quote Grid_QuoteGrid"), 5, 3, 1336, 531, Modifier.None, Button.Button1)
    mouseClick(waitForObject(":Market-Q (qa).Test Quotes Grid_LCLabel"), 26, 3, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Print"))
    clickButton(waitForObject(":Print Quotes Grid.OK_FixedSizeButton"))
    clickButton(waitForObject(":Print.Cancel_JButton"))
    
    mouseClick(waitForObject(":Market-Q (qa).Test Quotes Grid_LCLabel"), 5, 2, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Display Properties"))
    test.compare(waitForObjectExists(":com.futuresource.livecharts.common.LCCardList$1.Conversion  _ListItemProxy").text, "Conversion")
    clickButton(waitForObject(":Quote Grid Display Properties.OK_FixedSizeButton"))
    
    mouseClick(waitForObject(":Market-Q (qa).Test Quotes Grid_LCLabel"), 43, 8, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Empty"))
    
    clickButton(waitForObject(":Market-Q (qa).Quotes Grid_MonsoonNewPadButton"))
    mouseClick(waitForObject(":Market-Q (qa).Quotes Grid_LCLabel"), 28, 9, 4, Button.Button3)
    activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_4", "Close"))
    

    snooze(40)
