# -*- coding: utf-8 -*-
source(findFile("scripts", "Menu_Utilities_SymbolLookup.py"))
source(findFile("scripts", "Menu_Utilities_IndexConstituents.py"))
source(findFile("scripts", "Menu_Utilities_SectorOrIndustryList_Energy.py"))
source(findFile("scripts", "Menu_Utilities_Notifications.py"))
source(findFile("scripts", "Menu_Utilities_ReplceSymbols.py"))
source(findFile("scripts", "Menu_Utilities_ViewAlerts.py"))
source(findFile("scripts", "Menu_Utilities_ViewTriggeredAlerts.py"))
source(findFile("scripts", "Menu_Utilities_SectorOrIndustryList_Materials.py"))
source(findFile("scripts", "Menu_Utilities_SectorOrIndustryList_Industrials.py"))
source(findFile("scripts", "Menu_Utilities_SectorOrIndustryList_ConsumerDiscretionary.py"))
source(findFile("scripts", "Menu_Utilities_SectorOrIndustryList_ConsumerStaples.py"))
source(findFile("scripts", "Menu_Utilities_SectorOrIndustryList_HealthCare.py"))
source(findFile("scripts", "Menu_Utilities_SectorOrIndustryList_Financials.py"))
source(findFile("scripts", "Menu_Utilities_SectorOrIndustryList_InformationTechnology.py"))
source(findFile("scripts", "TimeAndSales_SymbolBox.py"))
source(findFile("scripts", "TimeAndSales_Filter.py"))
source(findFile("scripts", "TimeAndSales_FilterButton.py"))
source(findFile("scripts", "TimeAndSales_FilterOptionFields_Trades.py"))
source(findFile("scripts", "TimeAndSales_BidsAndAsks.py"))
source(findFile("scripts", "TimeAndSalesSymbolDetailsFields.py"))
source(findFile("scripts", "TimeAndSales_DisplayProperties.py"))
source(findFile("scripts", "Customize.py"))
source(findFile("scripts", "TimeAndSales_Fields_RightClick_Charts.py"))
source(findFile("scripts", "News_Filter.py"))
source(findFile("scripts", "News_DisplayProperties.py"))
source(findFile("scripts", "Hotlist_Filter.py"))
source(findFile("scripts", "Hotlist_RightClick_IndexConstituents.py"))
source(findFile("scripts", "Waterfall_Filter.py"))
source(findFile("scripts", "WaterFall_SectorAndIndustryDropDown.py"))
source(findFile("scripts", "WaterFall_DisplayProperties.py"))
source(findFile("scripts", "Marktdepth_SymbolBox.py"))
source(findFile("scripts", "MarketDepth_Displayproperties.py"))
source(findFile("scripts", "Webfeeds.py"))
source(findFile("scripts", "Create_WebFeed.py"))
source(findFile("scripts", "DividendHistory.py"))
source(findFile("scripts", "Whatsnew.py"))
source(findFile("scripts", "WatchList.py"))
source(findFile("scripts", "DataTable.py"))
source(findFile("scripts", "Quotes_Grid.py"))
source(findFile("scripts", "Alerts.py"))
source(findFile("scripts", "WaterFall.py"))
source(findFile("scripts", "Forex.py"))
source(findFile("scripts", "HotLists.py"))
source(findFile("scripts", "Menu_Bar.py"))
source(findFile("scripts", "Menu_Utilities_VwapCalculator.py"))
source(findFile("scripts", "Notes.py"))
#source(findFile("scripts", "Econoday.py"))
source(findFile("scripts", "Calendar.py"))
source(findFile("scripts", "QuotesGrid.py"))
source(findFile("scripts", "FutureOptions.py"))
#source(findFile("scripts", "Detailed_Quotes.py"))

source(findFile("scripts", "Detailed_Quotes.py"))



def main():
    #startApplication("C:\\Users\\vamsikrishnak\\Desktop\\mq_iws.bat")  
    startApplication("D:\\squish\\ICEWS.bat")
    #startApplication("javaws C:\\Users\\vamsikrishnak\\Downloads\\mq20181015.jnlp")
    
    snooze(60)
    WaterFall()
    #QuotesGrid()
    #Forex()
    #FutureOptions()
    #WatchList()


    Detailed_Quotes()
    Webfeeds()

    HotLists()

    Detailed_Quotes()
    Webfeeds()

    HotLists()

    WatchList()

    #Calendar()
    #Econoday()
    #Notes()
    #HotLists()

    #Forex()

    #WaterFall()
    #Alerts()
    #Quotes_Grid()
    #DataTable()
    #WatchList()
    #TimeAndSales_SymbolBox()
    #Menu_Utilities_IndexConstituents()    

    Detailed_Quotes()
    Webfeeds()

    Menu_Bar()
    Menu_Utilities_IndexConstituents()
    Menu_Utilities_Notifications()
    Menu_Utilities_SectorOrIndustryList_Energy()
    Menu_Utilities_Symbollookup()
    Menu_Utilities_ViewAlerts()
    Menu_Utilities_ViewTriggeredAlerts()
    Menu_Utilities_VwapCalculator()
    Marketdepth_SymbolBox()
    Marketdepth_Displayproperties()
    News_Filter()
    News_DisplayProperties()
    Detailed_Quotes()
    Quotes_Grid()
    TimeAndSales_FilterButton()
    TimeAndSales_DisplayProperties()
    TimeAndSales_SymbolBox()
    DataTable()
    WatchList()
    WaterFall()
    WaterFall_DisplayProperties
    Forex()
    HotLists()
    Hotlist_Filter()
    Marketdepth_SymbolBox()
    MarketDepth_Displayproperties()
    Webfeeds()

    #WaterFall()
    #Alerts()
    #Quotes_Grid()
    #DataTable()
    #WatchList()
    #TimeAndSales_SymbolBox()
    #Menu_Utilities_IndexConstituents()    

    Detailed_Quotes()
    Webfeeds()

    Menu_Bar()
    Menu_Utilities_IndexConstituents()
    Menu_Utilities_Notifications()
    Menu_Utilities_SectorOrIndustryList_Energy()
    Menu_Utilities_Symbollookup()
    Menu_Utilities_ViewAlerts()
    Menu_Utilities_ViewTriggeredAlerts()
    Menu_Utilities_VwapCalculator()
    Marketdepth_SymbolBox()
    Marketdepth_Displayproperties()
    News_Filter()
    News_DisplayProperties()
    Detailed_Quotes()
    Quotes_Grid()
    TimeAndSales_FilterButton()
    TimeAndSales_DisplayProperties()
    TimeAndSales_SymbolBox()
    DataTable()
    WatchList()
    WaterFall()
    WaterFall_DisplayProperties
    Forex()
    HotLists()
    Hotlist_Filter()
    Marketdepth_SymbolBox()
    MarketDepth_Displayproperties()

    Webfeeds()

#     Detailed_Quotes()
#     Webfeeds()
#     HotLists()
#     #Forex()
#     #WaterFall()
#     #Alerts()
#     #Quotes_Grid()
#     #DataTable()
#     #WatchList()
#     #TimeAndSales_SymbolBox()
#     #Menu_Utilities_IndexConstituents(
# #     Detailed_Quotes()
# #     Webfeeds()
# #     Menu_Bar()
# #     Menu_Utilities_ViewTriggeredAlerts()
# #     Menu_Utilities_ViewAlerts()
# #     Menu_Utilities_Notifications()
# #     Menu_Utilities_VwapCalculator()
# #     Menu_Utilities_SectorOrIndustryList_Energy()
# #     Menu_Utilities_IndexConstituents()
# #     Menu_Utilities_Symbollookup()
# #     Menu_Bar()
# #     TimeAndSales_FilterButton()
# #     TimeAndSales_DisplayProperties()
# #     Marktdepth_SymbolBox()
# #     MarketDepth_Displayproperties()
# #     News_Filter()
# #     News_DisplayProperties(
#     Detailed_Quotes()
#     Webfeeds()
#     Menu_Bar()
#     Menu_Utilities_IndexConstituents()
#     Menu_Utilities_Notifications()
#     Menu_Utilities_SectorOrIndustryList_Energy()
#     Menu_Utilities_Symbollookup()
#     Menu_Utilities_ViewAlerts()
#     Menu_Utilities_ViewTriggeredAlerts()
#     Menu_Utilities_VwapCalculator()
#     Marketdepth_SymbolBox()
#     Marketdepth_Displayproperties()
#     News_Filter()
#     News_DisplayProperties()
#     Detailed_Quotes()
#     Quotes_Grid()
#     TimeAndSales_FilterButton()
#     TimeAndSales_DisplayProperties()
#     TimeAndSales_SymbolBox()
#     DataTable()
#     WatchList()
#     WaterFall()
#     WaterFall_DisplayProperties
#     Forex()
#     HotLists()
#     Hotlist_Filter()
#     Marketdepth_SymbolBox()
#     MarketDepth_Displayproperties()
#     Webfeeds()

    
    
    
    
    
    
#     Detailed_Quotes()
#     Webfeeds()
#     Menu_Bar()
#     Menu_Utilities_ViewTriggeredAlerts()
#     Menu_Utilities_ViewAlerts()
#     Menu_Utilities_Notifications()
#     Menu_Utilities_VwapCalculator()
#     Menu_Utilities_SectorOrIndustryList_Energy()
#     Menu_Utilities_IndexConstituents()
#     Menu_Utilities_Symbollookup()
#     Menu_Bar()
#     TimeAndSales_FilterButton()
#     TimeAndSales_DisplayProperties()
#     Marktdepth_SymbolBox()
#     MarketDepth_Displayproperties()
#     News_Filter()
#     News_DisplayProperties()
#     TimeAndSales_Filter()
#     TimeAndSales_FilterButton()
#     activateCustomizeMenu()
#     Detailed_Quotes()


    News_Filter()
    News_DisplayProperties()
    TimeAndSales_Filter()
    TimeAndSales_FilterButton()
    activateCustomizeMenu()
    Detailed_Quotes()

    News_Filter()
    News_DisplayProperties()

    News_Filter()
    News_DisplayProperties()
    TimeAndSales_Filter()
    TimeAndSales_FilterButton()
    activateCustomizeMenu()
    Detailed_Quotes()

    News_Filter()
    News_DisplayProperties()

#     News_Filter()
#     News_DisplayProperties()
#     TimeAndSales_Filter()
#     TimeAndSales_FilterButton()
#     activateCustomizeMenu()
#     Detailed_Quotes()
# 
#     News_Filter()
#     News_DisplayProperties()

    
    #TimeAndSales_Filter()
    #TimeAndSales_FilterButton()
    #activateCustomizeMenu()

    Detailed_Quotes()


    Detailed_Quotes()


    #Detailed_Quotes()

#     TimeAndSales_FilterOptionFields_Trades()
#     TimeAndSales_BidsAndAsks()
#     TimeAndSales_DisplayProperties()
#     News_Filter()    
#     Hotlist_Filter()
#     Waterfall_Filter()
#     Marktdepth_SymbolBox()
#     Webfeeds()
#     DividendHistory()
#     