def WaterFall():
    
       testSettings.logScreenshotOnFail = True
       testSettings.logScreenshotOnError = True


       clickButton(waitForObject(":Market-Q (qa)_JButton_4"))
       activateItem(waitForObjectItem(":Market-Q (qa)_JButton_4", "Waterfall"))
       test.compare(waitForObjectExists(":Market-Q (qa).Waterfall_LCLabel").text, "Waterfall")
       snooze(2)
       


       mouseClick(waitForObject(":Market-Q (qa)_LCTextField_24"), 44, 8, 0, Button.Button1)
       type(waitForObject(":Market-Q (qa)_LCTextField_24"), "<Backspace>")
       type(waitForObject(":Market-Q (qa)_LCTextField_17"), "i")
       type(waitForObject(":Market-Q (qa)_LCTextField_24"), "bm,")
       type(waitForObject(":Market-Q (qa)_LCTextField_18"), "m")
       type(waitForObject(":Market-Q (qa)_LCTextField_24"), "sft,goog")
       type(waitForObject(":Market-Q (qa)_LCTextField_24"), "<Return>")

       snooze(3)
    

#        mouseClick(waitForObject(":Market-Q (qa).com.futuresource.livecharts.common.LCComboBox_LCComboBox"), 62, 10, 0, Button.Button1)
#        mouseClick(waitForObjectItem(":Market-Q (qa).ComboBox.list_JList_2", "Watch List"), 52, 2, 0, Button.Button1)
# 
#        snooze(3)
#        clickButton(waitForObject(":Market-Q (qa).Please select watch list_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Workspace Symbol Lists.DJ-UBS Commodity Indices"), 77, 7, 0, Button.Button1)
#        test.compare(waitForObjectExists(":Market-Q (qa).DJ-UBS Commodity Indices_LCTreeButton").actioncommand, "DJ-UBS Commodity Indices")
#        snooze(5)
#        clickButton(waitForObject(":Market-Q (qa).DJ-UBS Commodity Indices_LCTreeButton"))     
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Workspace Symbol Lists.EIA - Imports & Exports"), 59, 7, 0, Button.Button1)
#        test.compare(waitForObjectExists(":Market-Q (qa).EIA - Imports & Exports_LCTreeButton").actioncommand, "EIA - Imports & Exports")
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).EIA - Imports & Exports_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Workspace Symbol Lists.EIA - Input Production"), 69, 7, 0, Button.Button1)
#        test.compare(waitForObjectExists(":Market-Q (qa).EIA - Input Production_LCTreeButton").actioncommand, "EIA - Input Production")
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).EIA - Input Production_LCTreeButton"))       
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Workspace Symbol Lists.EIA - Stocks"), 36, 7, 0, Button.Button1)
#        test.compare(waitForObjectExists(":Market-Q (qa).EIA - Stocks_LCTreeButton").actioncommand, "EIA - Stocks")
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).EIA - Stocks_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Workspace Symbol Lists.Global Ags & Softs"), 42, 7, 0, Button.Button1)
#        test.compare(waitForObjectExists(":Market-Q (qa).Global Ags & Softs_LCTreeButton").actioncommand, "Global Ags & Softs")
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Global Ags & Softs_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Workspace Symbol Lists.Global Ags & Softs"), 26, 7, 0, Button.Button1)
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Global Ags & Softs_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Workspace Symbol Lists.Global Energy"), 42, 7, 0, Button.Button1)
#        test.compare(waitForObjectExists(":Market-Q (qa).Global Energy_LCTreeButton").actioncommand, "Global Energy")
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Global Energy_LCTreeButton"))       
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Workspace Symbol Lists.Global Financial Futures"), 41, 7, 0, Button.Button1)
#        test.compare(waitForObjectExists(":Market-Q (qa).Global Financial Futures_LCTreeButton").actioncommand, "Global Financial Futures")
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Global Financial Futures_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Workspace Symbol Lists.Global Indicies"), 33, 7, 0, Button.Button1)
#        test.compare(waitForObjectExists(":Market-Q (qa).Global Indicies_LCTreeButton").actioncommand, "Global Indicies")
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Global Indicies_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Workspace Symbol Lists.Goldman Sachs Commodity Indices"), 29, 7, 0, Button.Button1)
#        test.compare(waitForObjectExists(":Market-Q (qa).Goldman Sachs Commodity Indices_LCTreeButton").actioncommand, "Goldman Sachs Commodity Indices")
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Goldman Sachs Commodity Indices_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Workspace Symbol Lists.Market Overview"), 45, 7, 0, Button.Button1)
#        test.compare(waitForObjectExists(":Market-Q (qa).Market Overview_LCTreeButton").actioncommand, "Market Overview")
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Market Overview_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Workspace Symbol Lists.NGL's - Clearport"), 36, 7, 0, Button.Button1)
#        test.compare(waitForObjectExists(":Market-Q (qa).NGL's - Clearport_LCTreeButton").actioncommand, "NGL's - Clearport")
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).NGL's - Clearport_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Workspace Symbol Lists.USDA - Cash Prices"), 57, 7, 0, Button.Button1)
#        test.compare(waitForObjectExists(":Market-Q (qa).USDA - Cash Prices_LCTreeButton").actioncommand, "USDA - Cash Prices")
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).USDA - Cash Prices_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Predefined Screeners.Most Active Equity Calls"), 101, 7, 0, Button.Button1)
#        test.compare(waitForObjectExists(":Market-Q (qa).Most Active Equity Calls_LCTreeButton").actioncommand, "Most Active Equity Calls")
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Most Active Equity Calls_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Predefined Screeners.Most Active Equity Puts"), 34, 7, 0, Button.Button1)
#        test.compare(waitForObjectExists(":Market-Q (qa).Most Active Equity Puts_LCTreeButton").actioncommand, "Most Active Equity Puts")
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Most Active Equity Puts_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Mobile Home Page (Phone Only).Futures"), 38, 7, 0, Button.Button1)
#        test.compare(waitForObjectExists(":Market-Q (qa).Futures_LCTreeButton").actioncommand, "Futures")
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Futures_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Mobile Home Page (Phone Only).US"), 9, 7, 0, Button.Button1)
#        test.compare(waitForObjectExists(":Market-Q (qa).US_LCTreeButton").actioncommand, "US")
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).US_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Mobile Home Page (Phone Only).World"), 35, 7, 0, Button.Button1)
#        test.compare(waitForObjectExists(":Market-Q (qa).World_LCTreeButton").actioncommand, "World")
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).World_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Mobile Home Page (Phone Only).Forex"), 33, 7, 0, Button.Button1)
#        test.compare(waitForObjectExists(":Market-Q (qa).Forex_LCTreeButton").actioncommand, "Forex")
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Forex_LCTreeButton"))
#        setValue(waitForObject(":Market-Q (qa)_JScrollBar"), 166)
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Shared Symbol Lists.List 1"), 24, 7, 0, Button.Button1)
#        test.compare(waitForObjectExists(":Market-Q (qa).List 1_LCTreeButton").actioncommand, "List 1")
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).List 1_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Server Symbol Lists.Dow Jones Industrial Average"), 121, 7, 0, Button.Button1)
#        test.compare(waitForObjectExists(":Market-Q (qa).Dow Jones Industrial Average_LCTreeButton").actioncommand, "Dow Jones Industrial Average")
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Dow Jones Industrial Average_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Server Symbol Lists.Dow Jones Composite Average"), 107, 7, 0, Button.Button1)
#        test.compare(waitForObjectExists(":Market-Q (qa).Dow Jones Composite Average_LCTreeButton").actioncommand, "Dow Jones Composite Average")
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Dow Jones Composite Average_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Server Symbol Lists.Dow Transportation Average"), 88, 7, 0, Button.Button1)
#        test.compare(waitForObjectExists(":Market-Q (qa).Dow Transportation Average_LCTreeButton").actioncommand, "Dow Transportation Average")
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Dow Transportation Average_LCTreeButton"))
#        setValue(waitForObject(":Market-Q (qa)_JScrollBar"), 285)
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Server Symbol Lists.NASDAQ 100"), 43, 7, 0, Button.Button1)
#        test.compare(waitForObjectExists(":Market-Q (qa).NASDAQ 100_LCTreeButton").actioncommand, "NASDAQ 100")
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).NASDAQ 100_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Server Symbol Lists.NASDAQ Composite"), 80, 7, 0, Button.Button1)
#        test.compare(waitForObjectExists(":Market-Q (qa).NASDAQ Composite_LCTreeButton").actioncommand, "NASDAQ Composite")
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).NASDAQ Composite_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Server Symbol Lists.S&P/TSX Composite Index"), 113, 7, 0, Button.Button1)
#        test.compare(waitForObjectExists(":Market-Q (qa).S&P/TSX Composite Index_LCTreeButton").actioncommand, "S&P/TSX Composite Index")
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).S&P/TSX Composite Index_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Server Symbol Lists.S&P/TSX Venture Composite Index"), 101, 7, 0, Button.Button1)
#        test.compare(waitForObjectExists(":Market-Q (qa).S&P/TSX Venture Composite Index_LCTreeButton").actioncommand, "S&P/TSX Venture Composite Index")
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).S&P/TSX Venture Composite Index_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Server Symbol Lists.NYSE (All)"), 53, 7, 0, Button.Button1)
#        test.compare(waitForObjectExists(":Market-Q (qa).NYSE (All)_LCTreeButton").actioncommand, "NYSE (All)")
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).NYSE (All)_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Server Symbol Lists.NASDAQ (All)"), 77, 7, 0, Button.Button1)
#        test.compare(waitForObjectExists(":Market-Q (qa).NASDAQ (All)_LCTreeButton").actioncommand, "NASDAQ (All)")
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).NASDAQ (All)_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Server Symbol Lists.AMEX (All)"), 51, 7, 0, Button.Button1)
#        test.compare(waitForObjectExists(":Market-Q (qa).AMEX (All)_LCTreeButton").actioncommand, "AMEX (All)")
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).AMEX (All)_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Server Symbol Lists.US (All)"), 42, 7, 0, Button.Button1)
#        test.compare(waitForObjectExists(":Market-Q (qa).US (All)_LCTreeButton").actioncommand, "US (All)")
#        snooze(5)
#        
#        snooze(3)
#        clickButton(waitForObject(":Market-Q (qa).Please select industry_LCTreeButton"))
#        expand(waitForObjectItem(":Market-Q (qa)_LCTree", ".Energy"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Energy.Energy Equipment & Services"), 34, 7, 0, Button.Button1)
#        test.compare(waitForObjectExists(":Market-Q (qa).Energy Equipment & Services_LCTreeButton").actioncommand, "Energy Equipment & Services")
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Energy Equipment & Services_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Energy.Oil, Gas, and Consumable Fuels"), 83, 7, 0, Button.Button1)
#        test.compare(waitForObjectExists(":Market-Q (qa).Oil, Gas, and Consumable Fuels_LCTreeButton").actioncommand, "Oil, Gas, and Consumable Fuels")
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Oil, Gas, and Consumable Fuels_LCTreeButton"))
#        expand(waitForObjectItem(":Market-Q (qa)_LCTree", ".Materials"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Materials.Chemicals"), 22, 7, 0, Button.Button1)
#        test.compare(waitForObjectExists(":Market-Q (qa).Chemicals_LCTreeButton").actioncommand, "Chemicals")
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Chemicals_LCTreeButton"))
#        collapse(waitForObjectItem(":Market-Q (qa)_LCTree", ".Energy"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Materials.Construction Materials"), 19, 7, 0, Button.Button1)
#        test.compare(waitForObjectExists(":Market-Q (qa).Construction Materials_LCTreeButton").actioncommand, "Construction Materials")
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Construction Materials_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Materials.Containers & Packaging"), 59, 7, 0, Button.Button1)
#        test.compare(waitForObjectExists(":Market-Q (qa).Containers & Packaging_LCTreeButton").actioncommand, "Containers & Packaging")
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Containers & Packaging_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Materials.Metals & Mining"), 44, 7, 0, Button.Button1)
#        test.compare(waitForObjectExists(":Market-Q (qa).Metals & Mining_LCTreeButton").actioncommand, "Metals & Mining")
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Metals & Mining_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Materials.Paper & Forest Products"), 63, 7, 0, Button.Button1)
#        test.compare(waitForObjectExists(":Market-Q (qa).Paper & Forest Products_LCTreeButton").actioncommand, "Paper & Forest Products")
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Paper & Forest Products_LCTreeButton"))
#        collapse(waitForObjectItem(":Market-Q (qa)_LCTree", ".Materials"))
#        expand(waitForObjectItem(":Market-Q (qa)_LCTree", ".Industrials"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Industrials.Aerospace & Defense"), 29, 7, 0, Button.Button1)
#        test.compare(waitForObjectExists(":Market-Q (qa).Aerospace & Defense_LCTreeButton").actioncommand, "Aerospace & Defense")
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Aerospace & Defense_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Industrials.Building Products"), 65, 7, 0, Button.Button1)
#        test.compare(waitForObjectExists(":Market-Q (qa).Building Products_LCTreeButton").actioncommand, "Building Products")
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Building Products_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Industrials.Construction & Engineering"), 45, 7, 0, Button.Button1)
#        test.compare(waitForObjectExists(":Market-Q (qa).Construction & Engineering_LCTreeButton").actioncommand, "Construction & Engineering")
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Construction & Engineering_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Industrials.Electrical Equipment"), 78, 7, 0, Button.Button1)
#        test.compare(waitForObjectExists(":Market-Q (qa).Electrical Equipment_LCTreeButton").actioncommand, "Electrical Equipment")
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Electrical Equipment_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Industrials.Industrial Conglomerates"), 72, 7, 0, Button.Button1)
#        test.compare(waitForObjectExists(":Market-Q (qa).Industrial Conglomerates_LCTreeButton").actioncommand, "Industrial Conglomerates")
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Industrial Conglomerates_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Industrials.Machinery"), 51, 7, 0, Button.Button1)
#        test.compare(waitForObjectExists(":Market-Q (qa).Machinery_LCTreeButton").actioncommand, "Machinery")
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Machinery_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Industrials.Trading Companies & Distributors"), 86, 7, 0, Button.Button1)
#        test.compare(waitForObjectExists(":Market-Q (qa).Trading Companies & Distributors_LCTreeButton").actioncommand, "Trading Companies & Distributors")
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Trading Companies & Distributors_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Industrials.Commercial Services & Supplies"), 104, 7, 0, Button.Button1)
#        test.compare(waitForObjectExists(":Market-Q (qa).Commercial Services & Supplies_LCTreeButton").actioncommand, "Commercial Services & Supplies")
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Commercial Services & Supplies_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Industrials.Professional Services"), 113, 7, 0, Button.Button1)
#        test.compare(waitForObjectExists(":Market-Q (qa).Professional Services_LCTreeButton").actioncommand, "Professional Services")
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Professional Services_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Industrials.Air Freight & Logistics"), 55, 7, 0, Button.Button1)
#        test.compare(waitForObjectExists(":Market-Q (qa).Air Freight & Logistics_LCTreeButton").actioncommand, "Air Freight & Logistics")
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Air Freight & Logistics_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Industrials.Airlines"), 20, 7, 0, Button.Button1)
#        test.compare(waitForObjectExists(":Market-Q (qa).Airlines_LCTreeButton").actioncommand, "Airlines")
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Airlines_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Industrials.Road & Rail"), 55, 7, 0, Button.Button1)
#        test.compare(waitForObjectExists(":Market-Q (qa).Road & Rail_LCTreeButton").actioncommand, "Road & Rail")
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Road & Rail_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Industrials.Transportation Infrastructure"), 70, 7, 0, Button.Button1)
#        test.compare(waitForObjectExists(":Market-Q (qa).Transportation Infrastructure_LCTreeButton").actioncommand, "Transportation Infrastructure")
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Transportation Infrastructure_LCTreeButton"))
#        collapse(waitForObjectItem(":Market-Q (qa)_LCTree", ".Industrials"))
#        expand(waitForObjectItem(":Market-Q (qa)_LCTree", ".Consumer Discretionary"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Consumer Discretionary.Auto Components"), 23, 7, 0, Button.Button1)
#        test.compare(waitForObjectExists(":Market-Q (qa).Auto Components_LCTreeButton").actioncommand, "Auto Components")
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Auto Components_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Consumer Discretionary.Automobiles"), 50, 7, 0, Button.Button1)
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Automobiles_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Consumer Discretionary.Household Durables"), 67, 7, 0, Button.Button1)
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Household Durables_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Consumer Discretionary.Leisure Products"), 59, 7, 0, Button.Button1)
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Leisure Products_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Consumer Discretionary.Textiles, Apparel & Luxury Goods"), 43, 7, 0, Button.Button1)
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Textiles, Apparel & Luxury Goods_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Consumer Discretionary.Hotels, Restaurants & Leisure"), 89, 7, 0, Button.Button1)
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Hotels, Restaurants & Leisure_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Consumer Discretionary.Diversified Consumer Services"), 83, 7, 0, Button.Button1)
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Diversified Consumer Services_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Consumer Discretionary.Media"), 36, 7, 0, Button.Button1)
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Media_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Consumer Discretionary.Distributors"), 26, 7, 0, Button.Button1)
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Distributors_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Consumer Discretionary.Internet & Direct Marketing Retail"), 58, 7, 0, Button.Button1)
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Internet & Direct Marketing Retail_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Consumer Discretionary.Multiline Retail"), 69, 7, 0, Button.Button1)
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Multiline Retail_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Consumer Discretionary.Specialty Retail"), 38, 7, 0, Button.Button1)
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Specialty Retail_LCTreeButton"))
#        collapse(waitForObjectItem(":Market-Q (qa)_LCTree", ".Consumer Discretionary"))
#        expand(waitForObjectItem(":Market-Q (qa)_LCTree", ".Consumer Staples"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Consumer Staples.Food & Staples Retailing"), 28, 7, 0, Button.Button1)
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Food & Staples Retailing_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Consumer Staples.Beverages"), 48, 7, 0, Button.Button1)
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Beverages_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Consumer Staples.Food Products"), 20, 7, 0, Button.Button1)
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Food Products_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Consumer Staples.Tobacco"), 33, 7, 0, Button.Button1)
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Tobacco_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Consumer Staples.Household Products"), 64, 7, 0, Button.Button1)
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Household Products_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Consumer Staples.Personal Products"), 58, 7, 0, Button.Button1)
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Personal Products_LCTreeButton"))
#        collapse(waitForObjectItem(":Market-Q (qa)_LCTree", ".Consumer Staples"))
#        expand(waitForObjectItem(":Market-Q (qa)_LCTree", ".Healthcare"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Healthcare.Healthcare Equipment & Supplies"), 15, 7, 0, Button.Button1)
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Healthcare Equipment & Supplies_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Healthcare.Healthcare Providers & Services"), 47, 7, 0, Button.Button1)
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Healthcare Providers & Services_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Healthcare.Health Care Technology"), 122, 7, 0, Button.Button1)
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Health Care Technology_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Healthcare.Biotechnology"), 57, 7, 0, Button.Button1)
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Biotechnology_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Healthcare.Pharmaceuticals"), 46, 7, 0, Button.Button1)
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Pharmaceuticals_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Healthcare.Life Sciences Tools & Services"), 95, 7, 0, Button.Button1)
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Life Sciences Tools & Services_LCTreeButton"))
#        collapse(waitForObjectItem(":Market-Q (qa)_LCTree", ".Healthcare"))
#        expand(waitForObjectItem(":Market-Q (qa)_LCTree", ".Healthcare"))
#        collapse(waitForObjectItem(":Market-Q (qa)_LCTree", ".Healthcare"))
#        expand(waitForObjectItem(":Market-Q (qa)_LCTree", ".Financials"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Financials.Banks"), 28, 7, 0, Button.Button1)
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Banks_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Financials.Thrifts & Mortgage Finance"), 37, 7, 0, Button.Button1)
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Thrifts & Mortgage Finance_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Financials.Diversified Financial Services"), 48, 7, 0, Button.Button1)
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Diversified Financial Services_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Financials.Consumer Finance"), 59, 7, 0, Button.Button1)
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Consumer Finance_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Financials.Capital Markets"), 57, 7, 0, Button.Button1)
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Capital Markets_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Financials.Mortgage Real Estate Investment Trusts (REITs)"), 60, 7, 0, Button.Button1)
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Mortgage Real Estate Investment Trusts (REITs)_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Financials.Insurance"), 49, 7, 0, Button.Button1)
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Insurance_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Financials.Real Estate Management & Development (obsolete)"), 27, 7, 0, Button.Button1)
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Real Estate Management & Development (obsolete)_LCTreeButton"))
#        expand(waitForObjectItem(":Market-Q (qa)_LCTree", ".Information Technology"))
#        collapse(waitForObjectItem(":Market-Q (qa)_LCTree", ".Financials"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Information Technology.Internet Software & Services"), 40, 7, 0, Button.Button1)
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Internet Software & Services_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Information Technology.IT Services"), 41, 7, 0, Button.Button1)
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).IT Services_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Information Technology.Software"), 37, 7, 0, Button.Button1)
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Software_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Information Technology.Communications Equipment"), 42, 7, 0, Button.Button1)
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Communications Equipment_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Information Technology.Technology Hardware, Storage & Peripherals"), 82, 7, 0, Button.Button1)
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Technology Hardware, Storage & Peripherals_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Information Technology.Electronic Equipment, Instruments & Components"), 82, 7, 0, Button.Button1)
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Electronic Equipment, Instruments & Components_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Information Technology.Semiconductors & Semiconductor Equipment"), 91, 7, 0, Button.Button1)
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Semiconductors & Semiconductor Equipment_LCTreeButton"))
#        collapse(waitForObjectItem(":Market-Q (qa)_LCTree", ".Information Technology"))
#        expand(waitForObjectItem(":Market-Q (qa)_LCTree", ".Communication Services"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Communication Services.Diversified Telecommunication Services"), 101, 7, 0, Button.Button1)
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Diversified Telecommunication Services_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Communication Services.Wireless Telecommunication Services"), 106, 7, 0, Button.Button1)
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Wireless Telecommunication Services_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Communication Services.Media"), 73, 7, 0, Button.Button1)
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Media_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Communication Services.Entertainment"), 74, 7, 0, Button.Button1)
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Entertainment_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Communication Services.Interactive Media & Services"), 64, 7, 0, Button.Button1)
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Interactive Media & Services_LCTreeButton"))
#        collapse(waitForObjectItem(":Market-Q (qa)_LCTree", ".Communication Services"))
#        expand(waitForObjectItem(":Market-Q (qa)_LCTree", ".Utilities"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Utilities.Electric Utilities"), 37, 7, 0, Button.Button1)
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Electric Utilities_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Utilities.Gas Utilities"), 32, 7, 0, Button.Button1)
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Gas Utilities_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Utilities.Multi-utilities"), 37, 7, 0, Button.Button1)
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Multi-utilities_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Utilities.Water Utilities"), 39, 7, 0, Button.Button1)
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Water Utilities_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Utilities.Independent Power and Renewable Electricity Producers"), 135, 7, 0, Button.Button1)
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Independent Power and Renewable Electricity Producers_LCTreeButton"))
#        collapse(waitForObjectItem(":Market-Q (qa)_LCTree", ".Utilities"))
#        expand(waitForObjectItem(":Market-Q (qa)_LCTree", ".Real Estate"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Real Estate.Equity Real Estate Investment Trusts (REITs)"), 99, 7, 0, Button.Button1)
#        snooze(5)
#        
#        clickButton(waitForObject(":Market-Q (qa).Equity Real Estate Investment Trusts (REITs)_LCTreeButton"))
#        mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Real Estate.Real Estate Management & Development"), 144, 7, 0, Button.Button1)
#        snooze(5)

       mouseClick(waitForObject(":Market-Q (qa).com.futuresource.livecharts.common.LCComboBox_LCComboBox"), 75, 5, 0, Button.Button1)
       mouseClick(waitForObjectItem(":Market-Q (qa).ComboBox.list_JList_2", "Symbols"), 65, 2, 0, Button.Button1)
       clickButton(waitForObject(":Market-Q (qa)_LCAppendedButton_2"))
       type(waitForObject(":Symbol Lookup_LCTextField"), "<Backspace>")
       type(waitForObject(":Symbol Lookup_LCTextField"), "ibm")
       clickButton(waitForObject(":Symbol Lookup.Search_FixedSizeButton"))
       test.compare(waitForObjectExists(":com.futuresource.livecharts.dialogs.symbollookup.SymbolLookupDialog$SymbolsTable.IBM_TableItemProxy").text, "IBM")
       dragItemBy(waitForObject(":Symbol Lookup_LCTitlePane"), 59, 6, -507, -481, Modifier.None, Button.Button1)
       clickButton(waitForObject(":Symbol Lookup.OK_FixedSizeButton"))
       mouseClick(waitForObject(":Market-Q (qa)_LCTextField_24"), 50, 7, 0, Button.Button1)
       type(waitForObject(":Market-Q (qa)_LCTextField_24"), ",")
       type(waitForObject(":Market-Q (qa)_LCTextField_18"), "m")
       type(waitForObject(":Market-Q (qa)_LCTextField_24"), "sft")
       type(waitForObject(":Market-Q (qa)_LCTextField_24"), "<Return>")
       clickButton(waitForObject(":Market-Q (qa)_LCAppendedButton"))
       mouseClick(waitForObject(":Market-Q (qa)_LCToggleButton"), 8, 6, 0, Button.Button1)
       snooze(1)
       mouseClick(waitForObject(":Market-Q (qa)_LCToggleButton_4"), 8, 6, 0, Button.Button1)
       snooze(2)
       
       mouseClick(waitForObject(":Market-Q (qa)_LCTextField_24"), 76, 3, 0, Button.Button1)
       type(waitForObject(":Market-Q (qa)_LCTextField_24"), "goog")
       snooze(1)
       clickButton(waitForObject(":Market-Q (qa)_LCAppendedButton"))
       snooze(6)
       
       mouseClick(waitForObject(":Market-Q (qa)_LCTextField_24"), 92, 7, 0, Button.Button1)
       type(waitForObject(":Market-Q (qa)_LCTextField_24"), "ibm")
       clickButton(waitForObject(":Market-Q (qa)_LCAppendedButton"))
       snooze(8)
       
       mouseClick(waitForObject(":Market-Q (qa)_LCToggleButton"), 7, 8, 0, Button.Button1)
       snooze(2)
       mouseClick(waitForObject(":Market-Q (qa)_LCToggleButton_4"), 7, 8, 0, Button.Button1)
       snooze(2)

       clickButton(waitForObject(":Market-Q (qa)_LCAppendedButton_3"))
       snooze(2)
       mouseClick(waitForObject(":Market-Q (qa).23_JLabel"), 8, 10, 0, Button.Button1)
       snooze(2)
       mouseClick(waitForObject(":Market-Q (qa)_LCTextField_13"), 91, 13, 0, Button.Button1)
       snooze(2)
       type(waitForObject(":Market-Q (qa)_LCTextField_13"), "08:10:01")
       snooze(2)
       clickButton(waitForObject(":Market-Q (qa).Apply_SmallDialogButton"))
       snooze(1)
       clickButton(waitForObject(":Market-Q (qa).Reset_SmallDialogButton"))
       snooze(2)
       mouseClick(waitForObject(":Market-Q (qa)_LCTextField_12"), 30, 8, 0, Button.Button1)
       snooze(2)
       type(waitForObject(":Market-Q (qa)_LCTextField_12"), ">=200")
       snooze(2)
       clickButton(waitForObject(":Market-Q (qa).Apply_SmallDialogButton"))
       snooze(2)
       mouseClick(waitForObject(":Market-Q (qa)_LCTextField_11"), 55, 1, 0, Button.Button1)
       snooze(1)
       type(waitForObject(":Market-Q (qa)_LCTextField_11"), ">=1000")
       snooze(2)
       clickButton(waitForObject(":Market-Q (qa).Apply_SmallDialogButton"))
       snooze(1)
       clickButton(waitForObject(":Market-Q (qa).Reset_SmallDialogButton"))
       snooze(2)
       mouseClick(waitForObject(":Market-Q (qa)_LCTextField_10"), 79, 2, 0, Button.Button1)
       type(waitForObject(":Market-Q (qa)_LCTextField_10"), ">=137")
       snooze(1)
       clickButton(waitForObject(":Market-Q (qa).Apply_SmallDialogButton"))
       snooze(1)
       clickButton(waitForObject(":Market-Q (qa).Reset_SmallDialogButton"))
       snooze(1)
       mouseClick(waitForObject(":Market-Q (qa).Block Trades:_LCCheckBox"), 6, 6, 0, Button.Button1)
       snooze(5)
       mouseClick(waitForObject(":Market-Q (qa).Block Trades:_LCCheckBox"), 9, 11, 0, Button.Button1)
       snooze(1)
       mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.waterfall.WaterfallTable_WaterfallTable", "0/3"), 64, 7, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.waterfall.WaterfallTable_WaterfallTable", "Columns..."))
       mouseClick(waitForObjectItem(":Waterfall Column Selection.com.futuresource.livecharts.common.List2List$2_LCList", "Ask"), 7, 9, 0, Button.Button1)
       clickButton(waitForObject(":Waterfall Column Selection.Add_FixedSizeButton"))
       clickButton(waitForObject(":Waterfall Column Selection.OK_FixedSizeButton"))
       snooze(2)
       
       mouseClick(waitForObject(":Price_TableHeaderItemProxy_2"), 76, 5, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_JTableHeader_2", "Default Columns"))
       snooze(2)
       
       mouseClick(waitForObject(":Price_TableHeaderItemProxy_2"), 50, 9, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_JTableHeader_2", "Clear Selection"))
       snooze(2)
       
       mouseClick(waitForObject(":Price_TableHeaderItemProxy_2"), 65, 7, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_JTableHeader_2", "Show Filter"))
       snooze(2)
       mouseClick(waitForObject(":Price_TableHeaderItemProxy_2"), 59, 10, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_JTableHeader_2", "Show Filter"))
       snooze(2)
       mouseClick(waitForObject(":Price_TableHeaderItemProxy_2"), 60, 10, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_JTableHeader_2", "Block Trades"))
       snooze(8)
       mouseClick(waitForObject(":Price_TableHeaderItemProxy_2"), 50, 11, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_JTableHeader_2", "Block Trades"))
       snooze(2)
       
       mouseClick(waitForObject(":Price_TableHeaderItemProxy_2"), 61, 6, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_JTableHeader_2", "Pause"))
       snooze(2)
       
       mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.waterfall.WaterfallTable_WaterfallTable", "0/3"), 69, 6, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.waterfall.WaterfallTable_WaterfallTable", "View"))
       activateItem(waitForObjectItem(":Market-Q (qa).View_JMenu_7", "Chart"))
       snooze(2)
       test.compare(waitForObjectExists(":Market-Q (qa).Chart_LCLabel").text, "Chart")
       clickButton(waitForObject(":Market-Q (qa)_JButton_7"))
       snooze(2)
       
       mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.waterfall.WaterfallTable_WaterfallTable", "0/3"), 66, 8, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.waterfall.WaterfallTable_WaterfallTable", "View"))
       activateItem(waitForObjectItem(":Market-Q (qa).View_JMenu_7", "Stock Options"))
       snooze(2)
       test.compare(waitForObjectExists(":Market-Q (qa).Stock Options_LCLabel").text, "Stock Options")
       clickButton(waitForObject(":Market-Q (qa)_JButton_7"))
       snooze(2)
       
       mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.waterfall.WaterfallTable_WaterfallTable", "0/3"), 85, 8, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.waterfall.WaterfallTable_WaterfallTable", "View"))
       activateItem(waitForObjectItem(":Market-Q (qa).View_JMenu_7", "News"))
       snooze(2)
       test.compare(waitForObjectExists(":Market-Q (qa).News_LCLabel").name, "News")
       clickButton(waitForObject(":Market-Q (qa)_JButton_7"))
       snooze(2)
       
       mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.waterfall.WaterfallTable_WaterfallTable", "0/3"), 85, 1, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.waterfall.WaterfallTable_WaterfallTable", "View"))
       activateItem(waitForObjectItem(":Market-Q (qa).View_JMenu_7", "Detailed Quotes"))
       mouseClick(waitForObject(":Market-Q (qa). _LCLabel_8"), 8, 6, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_TitlebarPanel_5", "Show Window Title"))
       snooze(2)
       test.compare(waitForObjectExists(":Market-Q (qa).Detailed Quotes_LCLabel").name, "Detailed Quotes")
       clickButton(waitForObject(":Market-Q (qa)_JButton_7"))
       snooze(2)
       
       mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.waterfall.WaterfallTable_WaterfallTable", "0/3"), 96, 4, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.waterfall.WaterfallTable_WaterfallTable", "View"))
       activateItem(waitForObjectItem(":Market-Q (qa).View_JMenu_7", "Time & Sales"))
       test.compare(waitForObjectExists(":Market-Q (qa).Time & Sales_LCLabel").name, "Time & Sales")
       snooze(2)
       clickButton(waitForObject(":Market-Q (qa)_JButton_7"))
       snooze(2)
       
       mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.waterfall.WaterfallTable_WaterfallTable", "0/3"), 91, 1, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.waterfall.WaterfallTable_WaterfallTable", "View"))
       activateItem(waitForObjectItem(":Market-Q (qa).View_JMenu_7", "Market Depth"))
       test.compare(waitForObjectExists(":Market-Q (qa).Market Depth_LCLabel").name, "Market Depth")
       snooze(2)
       clickButton(waitForObject(":Market-Q (qa)_JButton_7"))
       snooze(2)

       mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.waterfall.WaterfallTable_WaterfallTable", "0/3"), 82, 9, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.waterfall.WaterfallTable_WaterfallTable", "View"))
       activateItem(waitForObjectItem(":Market-Q (qa).View_JMenu_8", "Data Table"))
       snooze(2)
       test.compare(waitForObjectExists(":Market-Q (qa).Data Table_LCLabel").name, "Data Table")
       clickButton(waitForObject(":Market-Q (qa)_JButton_7"))
       snooze(2)
       
       mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.waterfall.WaterfallTable_WaterfallTable", "0/3"), 57, 5, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.waterfall.WaterfallTable_WaterfallTable", "View"))
       activateItem(waitForObjectItem(":Market-Q (qa).View_JMenu_8", "Net House"))
       snooze(2)
       test.compare(waitForObjectExists(":Market-Q (qa).Net House_LCLabel").name, "Net House")
       clickButton(waitForObject(":Market-Q (qa)_JButton_7"))
       snooze(2)

#        mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.waterfall.WaterfallTable_WaterfallTable", "0/3"), 73, 8, 4, Button.Button3)
#        activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.waterfall.WaterfallTable_WaterfallTable", "View"))
#        activateItem(waitForObjectItem(":Market-Q (qa).View_JMenu_9", "Fundamentals"))
#        activateItem(waitForObjectItem(":Fundamentals_JMenu", "Balance Sheet"))
#        snooze(2)
#        test.compare(waitForObjectExists(":Market-Q (qa).Fundamentals_LCLabel").name, "Fundamentals")
#        clickButton(waitForObject(":Market-Q (qa)_JButton_7"))
#        snooze(2)
       
       mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.waterfall.WaterfallTable_WaterfallTable", "0/3"), 85, 7, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.waterfall.WaterfallTable_WaterfallTable", "View"))
       activateItem(waitForObjectItem(":Market-Q (qa).View_JMenu_9", "Real-Time Quote"))
       snooze(2)
       test.compare(waitForObjectExists(":Market-Q (qa).Real-Time Quote_LCLabel").text, "Real-Time Quote")
       clickButton(waitForObject(":Market-Q (qa)_JButton_7"))
       snooze(2)
       
       mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.waterfall.WaterfallTable_WaterfallTable", "0/3"), 94, 3, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.waterfall.WaterfallTable_WaterfallTable", "View"))
       activateItem(waitForObjectItem(":Market-Q (qa).View_JMenu_9", "Strip Calculator"))
       snooze(2)
       test.compare(waitForObjectExists(":Market-Q (qa).Strip Calculator_LCLabel").name, "Strip Calculator")
       clickButton(waitForObject(":Market-Q (qa)_JButton_7"))
       snooze(2)
       
       mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.waterfall.WaterfallTable_WaterfallTable", "0/3"), 95, 2, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.waterfall.WaterfallTable_WaterfallTable", "View"))
       activateItem(waitForObjectItem(":Market-Q (qa).View_JMenu_9", "S&P Research Stock Quick View"))
       clickButton(waitForObject(":Market-Q (qa)_JButton_7"))
       snooze(2)
       
       mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.waterfall.WaterfallTable_WaterfallTable", "0/3"), 98, 3, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.waterfall.WaterfallTable_WaterfallTable", "Add To Symbol list"))
       activateItem(waitForObjectItem(":Market-Q (qa).Add To Symbol list_JMenu_8", "Workspace Symbol Lists"))
       activateItem(waitForObjectItem(":Workspace Symbol Lists_JMenu_8", "Global Indicies"))
       clickButton(waitForObject(":Information.OK_FixedSizeButton"))
       clickButton(waitForObject(":Market-Q (qa).Watch List_MonsoonNewPadButton"))
       clickButton(waitForObject(":Market-Q (qa).Symbol List_LCTreeButton"))
       mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Workspace Symbol Lists.Global Indicies"), 71, 7, 0, Button.Button1)
       test.compare(waitForObjectExists(":com.futuresource.livecharts.newquotes.QuotePad$2.16_0_TableItemProxy").text, "IBM")
       snooze(2)
       
       mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.waterfall.WaterfallTable_WaterfallTable", "0/3"), 48, 4, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.waterfall.WaterfallTable_WaterfallTable", "Add To Symbol list"))
       activateItem(waitForObjectItem(":Market-Q (qa).Add To Symbol list_JMenu_8", "Mobile Home Page (Phone Only)"))
       activateItem(waitForObjectItem(":Mobile Home Page (Phone Only)_JMenu_7", "Futures"))
       clickButton(waitForObject(":Information.OK_FixedSizeButton"))
       clickButton(waitForObject(":Market-Q (qa).Global Indicies_LCTreeButton"))
       mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Mobile Home Page (Phone Only).Futures"), 36, 7, 0, Button.Button1)
       test.compare(waitForObjectExists(":com.futuresource.livecharts.newquotes.QuotePad$2.13_0_TableItemProxy").text, "IBM")
       clickButton(waitForObject(":Market-Q (qa)_JButton_7"))
       snooze(2)
       
       mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.waterfall.WaterfallTable_WaterfallTable", "0/3"), 74, 7, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.waterfall.WaterfallTable_WaterfallTable", "Add To Symbol list"))
       activateItem(waitForObjectItem(":Market-Q (qa).Add To Symbol list_JMenu_8", "Shared Symbol Lists"))
       activateItem(waitForObjectItem(":Shared Symbol Lists_JMenu_5", "List 1"))
       clickButton(waitForObject(":Information.OK_FixedSizeButton"))
       clickButton(waitForObject(":Market-Q (qa).Watch List_MonsoonNewPadButton"))
       clickButton(waitForObject(":Market-Q (qa).Symbol List_LCTreeButton"))
       setValue(waitForObject(":Market-Q (qa)_JScrollBar"), 156)
       mouseClick(waitForObjectItem(":Market-Q (qa)_LCTree", ".Shared Symbol Lists.List 1"), 17, 7, 0, Button.Button1)
       test.compare(waitForObjectExists(":com.futuresource.livecharts.newquotes.QuotePad$2.2_0_TableItemProxy").text, "IBM")
       clickButton(waitForObject(":Market-Q (qa)_JButton_7"))
       snooze(2)
       
       mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.waterfall.WaterfallTable_WaterfallTable", "0/2"), 44, 3, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.waterfall.WaterfallTable_WaterfallTable", "Alerts"))
       activateItem(waitForObjectItem(":Market-Q (qa).Alerts_JMenu_5", "Add Quote Alert"))
       type(waitForObject(":Add Quote Alert_LCTextField_3"), "134")
       mouseClick(waitForObject(":Add Quote Alert_LCTextArea"), 167, 27, 0, Button.Button1)
       type(waitForObject(":Add Quote Alert_LCTextArea"), "test")
       mouseClick(waitForObject(":Add Quote Alert.Link To:_LCCheckBox"), 14, 8, 0, Button.Button1)
       mouseClick(waitForObject(":Add Quote Alert.com.futuresource.livecharts.common.LCComboBox_LCComboBox"), 79, 7, 0, Button.Button1)
       mouseClick(waitForObjectItem(":Add Quote Alert.ComboBox.list_JList", "Page 2"), 64, 7, 0, Button.Button1)
       clickButton(waitForObject(":Add Quote Alert.OK_FixedSizeButton"))
       snooze(2)
       
       mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.waterfall.WaterfallTable_WaterfallTable", "0/3"), 57, 2, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.waterfall.WaterfallTable_WaterfallTable", "Alerts"))
       activateItem(waitForObjectItem(":Market-Q (qa).Alerts_JMenu_5", "Add News Alert"))
       mouseClick(waitForObject(":Add News Alert_LCTextArea"), 43, 44, 0, Button.Button1)
       type(waitForObject(":Add News Alert_LCTextArea"), "test news")
       mouseClick(waitForObject(":Add News Alert.Link To:_LCCheckBox"), 10, 9, 0, Button.Button1)
       mouseClick(waitForObject(":Add News Alert.com.futuresource.livecharts.common.LCComboBox_LCComboBox"), 14, 12, 0, Button.Button1)
       mouseClick(waitForObjectItem(":Add News Alert.ComboBox.list_JList", "Page 2"), 64, 9, 0, Button.Button1)
       clickButton(waitForObject(":Add News Alert.OK_FixedSizeButton"))
       snooze(2)
       
       mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.waterfall.WaterfallTable_WaterfallTable", "0/2"), 63, 7, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.waterfall.WaterfallTable_WaterfallTable", "Alerts"))
       activateItem(waitForObjectItem(":Market-Q (qa).Alerts_JMenu_5", "__Alerts"))
       clickTab(waitForObject(":Market-Q (qa).News Alerts_TabProxy"))
       test.compare(waitForObjectExists(":Market-Q (qa).Alerts_LCLabel").name, "Alerts")
       clickButton(waitForObject(":Market-Q (qa)_JButton_7"))
       snooze(2)
       
       mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.waterfall.WaterfallTable_WaterfallTable", "0/2"), 20, 2, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.waterfall.WaterfallTable_WaterfallTable", "Alerts"))
       activateItem(waitForObjectItem(":Market-Q (qa).Alerts_JMenu_5", "Triggered Alerts"))
       clickButton(waitForObject(":Alert Log.Close_FixedSizeButton"))
       snooze(2)
       
       mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.waterfall.WaterfallTable_WaterfallTable", "0/2"), 18, 4, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.waterfall.WaterfallTable_WaterfallTable", "Notes"))
       mouseClick(waitForObject(":Note - INTERNATIONAL BUSINESS MACHS_LCToggleButton"), 13, 10, 0, Button.Button1)
       snooze(1)
       mouseClick(waitForObject(":Note - INTERNATIONAL BUSINESS MACHS_LCToggleButton_2"), 6, 12, 0, Button.Button1)
       snooze(1)
       mouseClick(waitForObject(":Note - INTERNATIONAL BUSINESS MACHS_LCToggleButton_3"), 9, 13, 0, Button.Button1)
       clickButton(waitForObject(":Note - INTERNATIONAL BUSINESS MACHS. _FixedSizeButton"))
       clickButton(waitForObject(":Note - INTERNATIONAL BUSINESS MACHS_FixedSizeButton_3"))
       mouseClick(waitForObject(":Note - INTERNATIONAL BUSINESS MACHS_JTextPane"), 65, 35, 0, Button.Button1)
       type(waitForObject(":Note - INTERNATIONAL BUSINESS MACHS_JTextPane"), "test notes")
       clickButton(waitForObject(":Note - INTERNATIONAL BUSINESS MACHS.OK_FixedSizeButton"))
       snooze(2)
       
       mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.waterfall.WaterfallTable_WaterfallTable", "0/2"), 27, 5, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.waterfall.WaterfallTable_WaterfallTable", "Show Filter"))
       snooze(1)
       mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.waterfall.WaterfallTable_WaterfallTable", "0/2"), 30, 9, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.waterfall.WaterfallTable_WaterfallTable", "Show Filter"))
       snooze(2)
       
       mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.waterfall.WaterfallTable_WaterfallTable", "0/2"), 44, 3, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.waterfall.WaterfallTable_WaterfallTable", "Stream"))
       snooze(1)
       mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.waterfall.WaterfallTable_WaterfallTable", "0/2"), 27, 6, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.waterfall.WaterfallTable_WaterfallTable", "Pause"))
       snooze(2)
       
       mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.waterfall.WaterfallTable_WaterfallTable", "0/2"), 50, 9, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.waterfall.WaterfallTable_WaterfallTable", "Print"))
       clickButton(waitForObject(":Print Waterfall.OK_FixedSizeButton"))
       snooze(2)
       
       mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.waterfall.WaterfallTable_WaterfallTable", "0/2"), 20, 9, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.waterfall.WaterfallTable_WaterfallTable", "Display Properties..."))
       mouseClick(waitForObject(":Waterfall Display Properties_CommonButton"), 2, 11, 0, Button.Button1)
       mouseClick(waitForObjectItem(":Waterfall Display Properties.ComboBox.list_JList", "15"), 20, 16, 0, Button.Button1)
       mouseClick(waitForObject(":Waterfall Display Properties.Bold_LCCheckBox"), 10, 12, 0, Button.Button1)
       mouseClick(waitForObject(":Waterfall Display Properties.Italic_LCCheckBox"), 4, 10, 0, Button.Button1)
       clickButton(waitForObject(":Waterfall Display Properties.OK_FixedSizeButton"))
       mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.waterfall.WaterfallTable_WaterfallTable", "0/2"), 71, 2, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.waterfall.WaterfallTable_WaterfallTable", "Defaults"))
       activateItem(waitForObjectItem(":Market-Q (qa).Defaults_JMenu_10", "Save Waterfall Properties As Default"))
       clickButton(waitForObject(":Information.OK_FixedSizeButton"))
       snooze(2)
       
       mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.waterfall.WaterfallTable_WaterfallTable", "0/3"), 17, 0, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.waterfall.WaterfallTable_WaterfallTable", "Defaults"))
       activateItem(waitForObjectItem(":Market-Q (qa).Defaults_JMenu_10", "Apply Default Properties to the Waterfall"))
       clickButton(waitForObject(":Market-Q (qa)_JButton_5"))
       clickButton(waitForObject(":Market-Q (qa)_JButton_4"))
       activateItem(waitForObjectItem(":Market-Q (qa)_JButton_4", "Waterfall"))
       mouseClick(waitForObject(":Price_TableHeaderItemProxy_2"), 49, 16, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa)_JTableHeader_2", "Defaults"))
       activateItem(waitForObjectItem(":Market-Q (qa).Defaults_JMenu_10", "Apply Default Properties to all Waterfall Windows"))
       clickButton(waitForObject(":Market-Q (qa)_JButton_4"))
       activateItem(waitForObjectItem(":Market-Q (qa)_JButton_4", "Waterfall"))
       clickButton(waitForObject(":Market-Q (qa)_JButton_7"))
       snooze(2)
       
       mouseClick(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.waterfall.WaterfallTable_WaterfallTable", "0/3"), 77, 7, 4, Button.Button3)
       activateItem(waitForObjectItem(":Market-Q (qa).com.futuresource.livecharts.waterfall.WaterfallTable_WaterfallTable", "Defaults"))
       activateItem(waitForObjectItem(":Market-Q (qa).Defaults_JMenu_10", "Remove Default Waterfall Properties"))
       clickButton(waitForObject(":Question.Yes_FixedSizeButton"))
       clickButton(waitForObject(":Information.OK_FixedSizeButton"))
       clickButton(waitForObject(":Market-Q (qa)_JButton_5"))
       clickButton(waitForObject(":Market-Q (qa)_JButton_4"))
       activateItem(waitForObjectItem(":Market-Q (qa)_JButton_4", "Waterfall"))
       snooze(2)

       snooze(40)
